// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rand;
use rand::Rng;
#[derive(Clone, Debug, PartialEq)]
enum Pet {
    Dog = 0,
    Cat = 1,
    Bird = 2,
}

impl std::fmt::Display for Pet {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Pet::Dog => write!(f, "Dog"),
            Pet::Cat => write!(f, "Cat"),
            Pet::Bird => write!(f, "Bird"),
        }
    }
}

fn random_pet() -> Pet {
    let mut rng = rand::thread_rng();
    let n = rng.gen_range(0..3);
    match n {
        0 => Pet::Dog,
        1 => Pet::Cat,
        _ => Pet::Bird,
    }
}

fn main() {
    let pet: Pet = random_pet();

    let is_valid = pet == Pet::Dog || pet == Pet::Cat || pet == Pet::Bird;
    assert!(is_valid);
}
