// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let x: i32 = 10;
    if x > 5 {
        if x > 8 {
            println!("large");
        } else {
            println!("medium");
        }
    } else {
        println!("small");
    }

}
