// Auto-generated by a2r transpiler

/// Plan 610 ⑥: `use.c <engine_face_full.json>` → S-form static FFI face (manifest shared IR, auto-bindgen).
/// Safe wrappers carry Auto-side widths (int = i64, cast at the ABI edge);
/// every unsafe op stays inside this module.
mod engine_face_full_json_c {
    mod ffi_raw {
        #[link(name = "autoterm_core")]
        extern "C" {
            pub fn autoterm_engine_spawn(cols: i32, rows: i32, program: *const std::os::raw::c_char) -> *const std::os::raw::c_void;
            pub fn autoterm_engine_write_input(h: *const std::os::raw::c_void, bytes: *const std::os::raw::c_char, len: usize);
            pub fn autoterm_engine_feed_ready(h: *const std::os::raw::c_void) -> i32;
            pub fn autoterm_engine_take_dirty_rows(h: *const std::os::raw::c_void, out_rows: *mut std::os::raw::c_void, cap: i32) -> i32;
            pub fn autoterm_engine_row_text(h: *const std::os::raw::c_void, row: i32, out_buf: *mut std::os::raw::c_void, cap: i32) -> i32;
            pub fn autoterm_engine_row_style(h: *const std::os::raw::c_void, row: i32, out: *mut std::os::raw::c_void, cap: i32) -> i32;
            pub fn autoterm_engine_cursor(h: *const std::os::raw::c_void, out_row: *mut std::os::raw::c_void, out_col: *mut std::os::raw::c_void) -> i32;
            pub fn autoterm_engine_resize(h: *const std::os::raw::c_void, cols: i32, rows: i32);
            pub fn autoterm_engine_interrupt(h: *const std::os::raw::c_void) -> i32;
            pub fn autoterm_engine_is_exited(h: *const std::os::raw::c_void) -> i32;
            pub fn autoterm_engine_kill(h: *const std::os::raw::c_void);
            pub fn autoterm_engine_free(h: *const std::os::raw::c_void);
        }
    }
    pub fn autoterm_engine_spawn(cols: i64, rows: i64, program: &str) -> *const std::os::raw::c_void {
        let program_c = std::ffi::CString::new(program).unwrap_or_default();
        unsafe {
            ffi_raw::autoterm_engine_spawn(cols as i32, rows as i32, program_c.as_ptr())
        }
    }
    pub fn autoterm_engine_write_input(h: *const std::os::raw::c_void, bytes: &str, len: usize) {
        let bytes_c = std::ffi::CString::new(bytes).unwrap_or_default();
        unsafe {
            ffi_raw::autoterm_engine_write_input(h, bytes_c.as_ptr(), len)
        }
    }
    pub fn autoterm_engine_feed_ready(h: *const std::os::raw::c_void) -> i64 {
        (unsafe {
            ffi_raw::autoterm_engine_feed_ready(h)
        }) as i64
    }
    pub fn autoterm_engine_take_dirty_rows(h: *const std::os::raw::c_void, out_rows: *mut std::os::raw::c_void, cap: i64) -> i64 {
        (unsafe {
            ffi_raw::autoterm_engine_take_dirty_rows(h, out_rows, cap as i32)
        }) as i64
    }
    pub fn autoterm_engine_row_text(h: *const std::os::raw::c_void, row: i64, out_buf: *mut std::os::raw::c_void, cap: i64) -> i64 {
        (unsafe {
            ffi_raw::autoterm_engine_row_text(h, row as i32, out_buf, cap as i32)
        }) as i64
    }
    pub fn autoterm_engine_row_style(h: *const std::os::raw::c_void, row: i64, out: *mut std::os::raw::c_void, cap: i64) -> i64 {
        (unsafe {
            ffi_raw::autoterm_engine_row_style(h, row as i32, out, cap as i32)
        }) as i64
    }
    pub fn autoterm_engine_cursor(h: *const std::os::raw::c_void, out_row: *mut std::os::raw::c_void, out_col: *mut std::os::raw::c_void) -> i64 {
        (unsafe {
            ffi_raw::autoterm_engine_cursor(h, out_row, out_col)
        }) as i64
    }
    pub fn autoterm_engine_resize(h: *const std::os::raw::c_void, cols: i64, rows: i64) {
        unsafe {
            ffi_raw::autoterm_engine_resize(h, cols as i32, rows as i32)
        }
    }
    pub fn autoterm_engine_interrupt(h: *const std::os::raw::c_void) -> i64 {
        (unsafe {
            ffi_raw::autoterm_engine_interrupt(h)
        }) as i64
    }
    pub fn autoterm_engine_is_exited(h: *const std::os::raw::c_void) -> i64 {
        (unsafe {
            ffi_raw::autoterm_engine_is_exited(h)
        }) as i64
    }
    pub fn autoterm_engine_kill(h: *const std::os::raw::c_void) {
        unsafe {
            ffi_raw::autoterm_engine_kill(h)
        }
    }
    pub fn autoterm_engine_free(h: *const std::os::raw::c_void) {
        unsafe {
            ffi_raw::autoterm_engine_free(h)
        }
    }
    // Plan 610 ⑥ helper kit: pointer/buffer access from safe Auto code.
    pub fn cffi_handle_is_null(h: *const std::os::raw::c_void) -> bool {
        h.is_null()
    }
    pub fn cffi_buf_new_u32(len: i64) -> *mut std::os::raw::c_void {
        if len <= 0 { return std::ptr::null_mut(); }
        Box::into_raw(vec![0u32; len as usize].into_boxed_slice()) as *mut _
    }
    pub fn cffi_buf_get_u32(p: *const std::os::raw::c_void, idx: i64) -> u32 {
        if p.is_null() { return 0; }
        unsafe { *(p as *const u32).add(idx as usize) }
    }
    pub fn cffi_buf_new_u8(len: i64) -> *mut std::os::raw::c_void {
        if len <= 0 { return std::ptr::null_mut(); }
        Box::into_raw(vec![0u8; len as usize].into_boxed_slice()) as *mut _
    }
    pub fn cffi_cstr_read(p: *const std::os::raw::c_void) -> String {
        if p.is_null() { return String::new(); }
        unsafe { std::ffi::CStr::from_ptr(p as *const std::os::raw::c_char) }.to_string_lossy().into_owned()
    }
}
pub use engine_face_full_json_c::*;

fn main() {
    let h = autoterm_engine_spawn(80, 24, "cmd");
    println!("{}", cffi_handle_is_null(h));
    autoterm_engine_free(h);
}
