// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Calculator {
    pub value: i64,
}

impl Calculator {
    fn add(&self, a: i64, b: i64) -> i64 {
        a + b
    }
    fn multiply(&self, a: i64, b: i64) -> i64 {
        a * b
    }
}

fn main() {
    let calc = Calculator { value: 0 };
    let sum = calc.add(5, 3);
    let product = calc.multiply(4, 7);
    println!("Sum: {} {} {}", sum, "Product:", product);
}
