// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Calculator {
    value: i32,
}

impl Calculator {
    fn add(&self, a: i32, b: i32) -> i32 {
        a + b
    }
    fn multiply(&self, a: i32, b: i32) -> i32 {
        a * b
    }
}

fn main() {
    let calc = Calculator { value: 0 };
    let sum = calc.add(5, 3);
    let product = calc.multiply(4, 7);
    println!("Sum: {} {} {}", sum, "Product:", product);
}
