// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

#[derive(Clone, Debug)]
enum GreeterMsg {
    Greet(String),
    Count(i64),
}

#[derive(Clone, Debug)]
struct Greeter {
}

impl Greeter {
    pub fn new() -> Self {
        Self {}
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: GreeterMsg, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg {
            GreeterMsg::Greet(name) => {
                println!("hi {}", name);
            }
            GreeterMsg::Count(n) => {
                println!("count {}", n);
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_greeter() -> a2r_std::task::TaskRef<GreeterMsg> {
    let (taskref, mut rx) = a2r_std::task::channel::<GreeterMsg>();
    let join = tokio::spawn(async move {
        let mut actor = Greeter::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}


#[tokio::main]
async fn main() {
    let h = spawn_greeter();
    h.send(GreeterMsg::Greet("bob".to_string()));
    h.send(GreeterMsg::Count(7));
    a2r_std::task::drain_all().await;
}
