// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {

    let obj = {x: 1, y: 2};
    println!("obj");


    let pair = x: 10;
    println!("pair");
}
