// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

#[derive(Clone, Debug)]
enum FilterMsg {
    Add(i64),
}

#[derive(Clone, Debug)]
struct Filter {
}

impl Filter {
    pub fn new() -> Self {
        Self {}
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: FilterMsg, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg {
            FilterMsg::Add(val) if val > 1 => {
                println!("big");
            }
            FilterMsg::Add(val) => {
                println!("small");
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_filter() -> a2r_std::task::TaskRef<FilterMsg> {
    let (taskref, mut rx) = a2r_std::task::channel::<FilterMsg>();
    let join = tokio::spawn(async move {
        let mut actor = Filter::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}


#[tokio::main]
async fn main() {
    let h = spawn_filter();
    h.send(FilterMsg::Add(5));
    h.send(FilterMsg::Add(0));
    a2r_std::task::drain_all().await;
}
