// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Point {
    pub x: i64,
    pub y: i64,
}

#[derive(Clone, Debug, PartialEq)]
struct Circle {
    pub radius: f64,
    pub border: u32,
    pub center: Point,
}

fn main() {
    let mut p = Point { x: 1, y: 2 };
    p.x = 3;
    println!("P: {}, {}", p.x, p.y);

    let circle = Circle { radius: 5.0, border: 1, center: Point { x: 50, y: 50 } };
    println!("C: {}, {}, {}", circle.center.x, circle.center.y, circle.radius);
}
