// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Flyer {
    fn fly(&self);
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Pigeon {}

impl Flyer for Pigeon {
    fn fly(&self) {
        println!("Flap");
    }
}

fn main() {
    let p = Pigeon {};
    p.fly();
}
