// Auto-generated by a2r transpiler

fn get_headers() -> std::collections::HashMap<String, String> {
    let h: std::collections::HashMap<String, String> = {Accept: "application/json"};
    return h;
}

fn process(data: std::collections::HashMap<String, i32>) -> i32 {
    return 0;
}

fn main() {
    let m: std::collections::HashMap<String, i32> = {count: 10, total: 100};
    let result = process(m.clone());
}
