// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use chrono::Utc;
use chrono::TimeZone;
fn main() {
    let dt = Utc::timestamp_opt(1700000000, 0).single().unwrap();
    println!("From timestamp: {}", dt);
    let now = Utc::now();
    let ts = now.timestamp();
    println!("Current timestamp: {}", ts);
}
