// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use reqwest;
use scraper::Html;
use scraper::Selector;
fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    let html_content: String = "<html><body><a href='https://httpbin.org/status/200'>OK</a><a href='https://httpbin.org/status/404'>Missing</a></body></html>".to_string();
    let html = Html::parse_document(html_content);
    let selector = Selector::parse("a[href]")?;
    let client = reqwest.Client.new();

    for element in html.select(selector) {
        let href: String = element.attr("href").unwrap_or("".to_string());
        let response = client.head(href).send().await?;
        let status = response.status().as_u16();
        if status >= 400 {
            println!("BROKEN: {} ({})", href, status)
        } else {
            println!("OK: {} ({})", href, status)
        }

    }
    Ok(())
}
