// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use regex::Regex;
fn main() {

    let re = Regex::new("#\\w+").unwrap();
    let text: String = "Love #rust and #programming!".to_string();
    for cap in re.captures_iter(text) {
        println!("Hashtag: {}", cap[0].clone());
    }
}
