// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use serde_json::{from_str, to_string};
fn main() {
    let json = to_string("hello");
    let parsed = from_str(json);
}
