// Blueprint catalog. Reads the real package files via Vite ?raw imports so the
// gallery always reflects blueprints/ on disk. As the catalog grows this can be
// generated by `auto bp export-gallery-meta` (Plan 343); for the seed set
// it's a small manifest.

import loginSpec from '../../../blueprints/form/login/spec.md?raw'
import loginGotchas from '../../../blueprints/form/login/gotchas.md?raw'
import loginMinimal from '../../../blueprints/form/login/reference/minimal.at?raw'
import loginSso from '../../../blueprints/form/login/reference/with_sso.at?raw'

import noteListSpec from '../../../blueprints/data-display/note-list/spec.md?raw'
import noteListGotchas from '../../../blueprints/data-display/note-list/gotchas.md?raw'
import noteListDefault from '../../../blueprints/data-display/note-list/reference/default.at?raw'

export interface BpEntry {
  kind: string
  name: string
  spec: string
  gotchas: string
  references: Record<string, string>
}

export const bps: BpEntry[] = [
  {
    kind: 'form',
    name: 'login',
    spec: loginSpec,
    gotchas: loginGotchas,
    references: { minimal: loginMinimal, with_sso: loginSso },
  },
  {
    kind: 'data-display',
    name: 'note-list',
    spec: noteListSpec,
    gotchas: noteListGotchas,
    references: { default: noteListDefault },
  },
]

export const kindOrder = ['form', 'data-display', 'feedback', 'layout', 'composite']
