// Auto-generated by a2r transpiler

impl Counter {
    pub fn get_value(&self) -> u32 {
        return (self.count() as u32);
    }
}

fn main() {
    let c = Counter { field0: 10 };
    println!("{}", c.get_value());
}
