// Auto-generated by a2r transpiler

use mime::Mime;
fn main() {
    let mime = "text/html".parse().unwrap();
    println!("MIME: {}", mime);
    let is_text: bool = mime::type_() == mime.TEXT;
    assert!(is_text == true);
}
