// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use mime::Mime;
fn main() {
    let mime = "text/html".parse().unwrap();
    println!("MIME: {}", mime);
    let is_text: bool = mime.type_() == mime.TEXT;
    println!("Is text: {}", is_text);
}
