// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Storage<T> {
    fn data(&self) -> *mut T;
    fn capacity(&self) -> u32;
    fn try_grow(&self, min_cap: u32) -> bool;
}


struct Heap<T> {
    ptr: *mut T,
    cap: u32,
}

struct InlineInt64 {
    buffer: [i32; 64],
}

struct List<T, S> {
    len: u32,
    store: S,
}

fn main() {

    let heap_list = List<int, Heap>.new();
    let heap_len = heap_list.len();
    let heap_cap = heap_list.capacity();


    let inline_list = List<int, InlineInt64>.new();
    let inline_len = inline_list.len();
    let inline_cap = inline_list.capacity();

    return 0;
}
