// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

trait Storage<T> {
    fn data(&self) -> *mut T;
    fn capacity(&self) -> u32;
    fn try_grow(&self, min_cap: u32) -> bool;
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Heap<T> {
    ptr: *mut T,
    cap: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct InlineInt64 {
    buffer: Vec<i32>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct List<T, S> {
    len: u32,
    store: S,
}

fn main() {

    let heap_list = List<int, Heap>.new();
    let heap_len = (heap_list.len() as i32);
    let heap_cap = heap_list.capacity();


    let inline_list = List<int, InlineInt64>.new();
    let inline_len = (inline_list.len() as i32);
    let inline_cap = inline_list.capacity();

    return 0;
}
