// Auto-generated by a2r transpiler

fn mk() -> Vec<i64> {
    return vec![7, 8, 9];
}

fn main() {
    let a: Vec<i64> = vec![10, 20, 30];
    let mut total: i64 = 0;
    for v in &a {
        total = total + v;
    }
    println!("{}", total);
    for n in vec![1, 2, 3, 4] {
        println!("{}", n);
    }
    for w in mk() {
        println!("{}", w * 2);
    }
}
