// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn main() {
    let output: String = "30,Alice\n25,Bob".to_string();
    assert!(a2r_std::str_contains(output.as_str(), "Alice"));
    assert!(a2r_std::str_contains(output.as_str(), "Bob"));
    println!("30,Alice");
    println!("25,Bob");
}
