// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::time::{Instant, Duration};
fn main() {
    let start = Instant::now();
    let d = Duration::from_secs(5);
    let d2 = Duration::from_millis(500);
    println!("{}", d2);
}
