// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::fs;
fn main() {
    let content: String = "line1\nline2\nline3".to_string();
    let path: String = "test_temp.txt".to_string();
    File::write_text(path.as_str(), content.as_str());
    let lines = File::read_text(path.as_str());
    let mut line_count: i32 = 0;
    for line in lines.lines() {
        line_count += 1;
    }
    assert!(line_count == 3);
    File::delete(path.as_str());
}
