// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let data: String = "name,age\nAlice,30\nBob,25\nCharlie,35".to_string();
    let mut lines = data.split("\n").collect::<Vec<_>>();
    assert!((lines.len() as i32) == 4);

    let mut filtered_count: i32 = 0;
    if 30 > 28 {
        filtered_count += 1
    }
    if 35 > 28 {
        filtered_count += 1
    }
    assert!(filtered_count == 2);
}
