// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

#[derive(Clone, Debug)]
struct Sink {
}

impl Sink {
    pub fn new() -> Self {
        Self {}
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: i64, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg {
            1i64 => {
                println!("sink got one");
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_sink() -> a2r_std::task::TaskRef<i64> {
    let (taskref, mut rx) = a2r_std::task::channel::<i64>();
    let join = tokio::spawn(async move {
        let mut actor = Sink::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}


#[derive(Debug)]
struct Worker {
    pub handle: a2r_std::task::TaskRef<i64>,
}

impl Worker {
    fn emit(&self) {
        self.handle.send(1);
        self.handle.send(1);
    }
}

#[tokio::main]
async fn main() {
    let h = spawn_sink();
    let w = Worker { handle: h };
    w.emit();
    a2r_std::task::drain_all().await;
}
