// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::vec::Vec;
fn main() {
    let mut vec: Vec<i32> = vec![1, 5, 10, 2, 15];
    vec.sort();
    println!("{}", vec);
}
