// Auto-generated by a2r transpiler

use std::fs::{File, read_to_string};
use std::io::{BufRead, BufReader};
fn main() {
    let content = read_to_string("test.txt");
    let file = File::open("test.txt");
    let reader = BufReader::new(file);
    for line in reader.lines() {
        println!("{}", line);
    }
}
