// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn test_propagate() -> MayInt {
    let x: MayInt = Some(10);
    let y: MayInt = x;
    y
}

fn main() {
    let _result: MayInt = test_propagate();
}