// Auto-generated by a2r transpiler

use regex::Regex;
fn main() {
    let re = Regex::new("\\d+").unwrap();
    let text: String = "abc 123 def 456".to_string();
    let replaced = re.replace_all(text, "NUM");
    assert!(replaced == "abc NUM def NUM");
}
