// Auto-generated by a2r transpiler

use chrono::Local;
fn main() {
    let now = Local::now();
    let year = now.year();
    let month = now.month();
    let day = now.day();
    let hour = now.hour();
    assert!(year > 2000);
    assert!(month >= 1);
    assert!(day >= 1);
}
