// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::cell::RefCell;
fn main() {
    let cell = RefCell::new(0);
    let current = cell.borrow();
    println!("Initial: {}", current);
    cell.replace(42);
    let updated = cell.borrow();
    println!("Updated: {}", updated);
}
