// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use chrono::DateTime;
use chrono::Duration;
use chrono::Utc;
fn main() {
    let now = Utc::now();
    println!("Current time: {}", now);
    let future = now.checked_add_signed(Duration::days(30));
    println!("30 days from now: {}", future);
}
