// Auto-generated by a2r transpiler

use chrono::{Utc, Duration};
fn main() {
    let now = Utc::now();
    println!("Current time: {}", now);
    let future = now.checked_add_signed(Duration::days(30));
    assert!(true);
}
