// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use csv::Reader;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let csv_str: String = "name,age\nAlice,30\nBob,25".to_string();
    let mut reader = Reader::from_reader(csv_str.as_bytes());
    for result in reader.records() {
        let record: i32 = result?;
        println!("Name: {}, Age: {}", record.get(0).cloned(), record.get(1).cloned());
    }
    Ok(())
}
