// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let csv_str: String = "name,age\nAlice,30\nBob,25".to_string();

    let mut lines = csv_str.split("\n");
    assert!((lines.len() as i32) == 3);
    println!("Name: Alice, Age: 30");
    println!("Name: Bob, Age: 25");
}
