// Auto-generated by a2r transpiler

use walkdir;
use std::fs;
fn main() {
    let mut total_size: u32 = 0;
    for entry in walkdir::WalkDir::new("src") {
        let entry = entry.unwrap();
        if entry.file_type().is_file() {
            let meta = fs::metadata(entry.path()).unwrap();
            total_size = total_size + (meta.len() as i32)
        }
    }

    let has_size: bool = total_size >= 0;
    assert!(has_size);
}
