// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use walkdir;
use std::fs;
fn main() {
    let mut total_size: u32 = 0 as u32;
    for entry in walkdir::WalkDir::new("src") {
        let entry = entry.unwrap();
        if entry.file_type().is_file() {
            


            let meta = a2r_std::fs::file_size(entry.path().as_str());
            total_size = total_size + meta;
        }
    }

    let has_size: bool = total_size >= 0;
    assert!(has_size);
}
