// Auto-generated by a2r transpiler

use clap::Parser;
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Args {
    name: String,
    count: i32,
}

fn main() {
    let args = Args::parse();

    assert!(true);
}
