// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
pub enum ToolError {
    ExecutionFailed(String),
    InvalidInput(String),
}


pub fn handle(err: ToolError) -> String {
    match err {
        ToolError::ExecutionFailed(msg) => return msg,
        ToolError::InvalidInput(msg) => return msg,
    }
}
