// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use log::info;
use log::debug;
fn process() {
    debug.collect()("processing step 1");
    debug.collect()("processing step 2");
    info.collect()("processing complete");
}

fn main() {
    info.collect()("app started");
    process();
    println!("done");
}
