// Auto-generated by a2r transpiler

use std::collections::HashMap;
#[derive(Debug, Clone)]
pub struct TierCandidate {
    pub provider: String,
    pub model: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum ModelTier {
    Fast = 0,
    Balanced = 1,
    Deep = 2,
}

impl std::fmt::Display for ModelTier {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            ModelTier::Fast => write!(f, "Fast"),
            ModelTier::Balanced => write!(f, "Balanced"),
            ModelTier::Deep => write!(f, "Deep"),
        }
    }
}
impl ModelTier {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Fast" | "fast" => ModelTier::Fast,
            "Balanced" | "balanced" => ModelTier::Balanced,
            "Deep" | "deep" => ModelTier::Deep,
            _ => ModelTier::Fast
        }
    }
}

pub fn candidates(mut routing: HashMap<ModelTier, Vec<TierCandidate>>, tier: ModelTier) -> Vec<TierCandidate> {
    match routing.get(&tier) {
        Some(v) => return v.clone(),
        None => return vec![],
    };
    return vec![];
}

pub fn find_chain(mut routing: HashMap<ModelTier, Vec<TierCandidate>>, tier: ModelTier) -> Result<Vec<TierCandidate>, String> {
    match routing.get(&tier) {
        Some(v) => return Ok(v.clone()),
        None => return Err("missing".into()),
    };
    return Err("missing".into());
}

pub fn grow(mut routing: HashMap<ModelTier, Vec<TierCandidate>>, tier: ModelTier, mut tc: TierCandidate) {
    match routing.get(&tier) {
        Some(list) => {
            let mut updated = list.clone();
            updated.push(tc.clone());
            routing.insert(tier, updated.clone());
        },
        None => { routing.insert(tier, vec![tc.clone()]); },
    };
}

pub fn lookup(mut routing: HashMap<String, Vec<TierCandidate>>, key: &str) -> Vec<TierCandidate> {
    match routing.get(key) {
        Some(v) => return v.clone(),
        None => return vec![],
    };
    return vec![];
}
