// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use log::debug;
fn main() {
    debug!("starting operation");
    let value: i32 = 42;
    debug!("value = {}", value);
    println!("done");
}
