// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Config {
    env: std::collections::HashMap<&str, &str>,
    ports: Vec<i32>,
}

fn main() {
    let headers: std::collections::HashMap<&str, &str> = {Authorization: "Bearer xxx", Content-Type: "application/json"};
    let counts: std::collections::HashMap<&str, i32> = {hello: 3, world: 5};
    let x: i32 = 42;
}
