// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
struct Config {
    pub env: std::collections::HashMap<String, String>,
    pub ports: Vec<i64>,
}

fn main() {
    let headers: std::collections::HashMap<String, String> = std::collections::HashMap::from([(String::from("Authorization"), String::from("Bearer xxx")), (String::from("Content-Type"), String::from("application/json"))]);
    let counts: std::collections::HashMap<String, i64> = std::collections::HashMap::from([(String::from("hello"), 3), (String::from("world"), 5)]);
    let x: i64 = 42;
}
