// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let x: i32 = 42;
    let y: u32 = (x as u32);
    let z: i64 = (x as i64);
    let f: f64 = (x as f64);
    println!("{}", y);
}
