# -*- coding: utf-8 -*-
# R1 F-3/F-4/F-5 wire e2e tests (chunked / quota 503 / health latency / disconnect cleanup)
import io

p = 'crates/auto-lang/src/tests/plan730_http_upload_tests.rs'
src = io.open(p, encoding='utf-8').read()
assert 'http_e2e_plan730_vm_chunked' not in src, 'already applied'

anchor = '''    /// T-08 互通闭环：727 客户端 transfer_upload（multipart/raw/字段）→'''
assert anchor in src

BS = chr(92)
tests = (
    '    /// R1 F-3：chunked 上传（Transfer-Encoding，无声明 Content-Length）——\n'
    '    /// 逐块 wire 计数承载总量（不能只信声明值）；raw 201 字节一致。\n'
    '    #[test]\n'
    '    fn http_e2e_plan730_vm_chunked_upload() {\n'
    '        let (root, staging) = temp_roots("chunked");\n'
    '        let port = start_server(&upload_program(&root, &staging), 18981);\n'
    '        let payload: Vec<u8> = (0..300_000usize).map(|i| (i % 251) as u8).collect();\n'
    '        let mut stream = connect(port);\n'
    '        stream.set_read_timeout(Some(Duration::from_secs(30))).ok();\n'
    '        let head = "POST /api/uploads/raw HTTP/1.1{BS}r{BS}nHost: 127.0.0.1{BS}r{BS}nConnection: close{BS}r{BS}n{BS}r{BS}nContent-Type: application/octet-stream{BS}r{BS}nTransfer-Encoding: chunked{BS}r{BS}n{BS}r{BS}n";\n'
    '        stream.write_all(head.as_bytes()).unwrap();\n'
    '        for chunk in payload.chunks(64 * 1024) {\n'
    '            let frame = format!("{:x}{BS}r{BS}n", chunk.len());\n'
    '            stream.write_all(frame.as_bytes()).unwrap();\n'
    '            stream.write_all(chunk).unwrap();\n'
    '            stream.write_all(b"{BS}r{BS}n").unwrap();\n'
    '        }\n'
    '        stream.write_all(b"0{BS}r{BS}n{BS}r{BS}n").unwrap();\n'
    '        let (status, _h, b) = read_response(&mut stream);\n'
    '        assert_eq!(status, 201, "{}", String::from_utf8_lossy(&b));\n'
    '        assert_eq!(std::fs::read(root.join("raw/data.bin")).unwrap(), payload);\n'
    '    }\n'
    '\n'
    '    /// R1 F-2/F-4：quoted boundary wire + 配额满 503（active=1/queue=1 旋钮：\n'
    '    /// 慢上传占住 active，第二笔在队列 600ms 期限后 503）+ 慢传输期间\n'
    '    /// 20 次 health 独立连接均 <500ms（owner 不被接收阻塞）。\n'
    '    #[test]\n'
    '    fn http_e2e_plan730_vm_quota_and_health_under_load() {\n'
    '        std::env::set_var("AUTO_HTTP_UPLOAD_ACTIVE", "1");\n'
    '        std::env::set_var("AUTO_HTTP_UPLOAD_QUEUE", "1");\n'
    '        std::env::set_var("AUTO_HTTP_UPLOAD_QUEUE_TIMEOUT_MS", "600");\n'
    '        let (root, staging) = temp_roots("quota");\n'
    '        let port = start_server(&upload_program(&root, &staging), 18982);\n'
    '        // 占位连接：raw 慢上传（占住唯一 active 许可）。\n'
    '        let mut holder = connect(port);\n'
    '        holder.set_read_timeout(Some(Duration::from_secs(60))).ok();\n'
    '        let head = "POST /api/uploads/raw HTTP/1.1{BS}r{BS}nHost: x{BS}r{BS}nConnection: close{BS}r{BS}nContent-Type: application/octet-stream{BS}r{BS}nContent-Length: 1048576{BS}r{BS}n{BS}r{BS}n";\n'
    '        holder.write_all(head.as_bytes()).unwrap();\n'
    '        holder.write_all(&vec![b' + "'H'" + '; 64 * 1024]).unwrap();\n'
    '        // health 探测（20 次独立连接，每次 <500ms——owner 在接收 park 期仍服务）。\n'
    '        for i in 0..20 {\n'
    '            let t0 = std::time::Instant::now();\n'
    '            let (s, _h, b) = raw_request_with_body(port, "GET", "/plain", &[], b"");\n'
    '            let dt = t0.elapsed();\n'
    '            assert_eq!(s, 200, "health #{i}: {}", String::from_utf8_lossy(&b));\n'
    '            assert!(dt.as_millis() < 500, "health #{i} took {dt:?} (owner blocked?)");\n'
    '            std::thread::sleep(Duration::from_millis(60));\n'
    '        }\n'
    '        // 第二笔上传：queue=1 满且 active 被占 → 600ms 队列期限 → 503。\n'
    '        let t0 = std::time::Instant::now();\n'
    '        let (s2, h2, b2) = raw_request_with_body(\n'
    '            port,\n'
    '            "POST",\n'
    '            "/api/uploads/raw",\n'
    '            &[("Content-Type", "application/octet-stream")],\n'
    '            b"SECOND",\n'
    '        );\n'
    '        let dt2 = t0.elapsed();\n'
    '        assert_eq!(s2, 503, "{}", String::from_utf8_lossy(&b2));\n'
    '        assert!(\n'
    '            String::from_utf8_lossy(&b2).contains("queue_full") || dt2.as_millis() >= 500,\n'
    '            "queue wait bounded: {dt2:?} {b2:?}"\n'
    '        );\n'
    '        assert!(h2.iter().any(|(k, _)| k == "content-type"), "receipt JSON reply");\n'
    '        // quoted boundary wire（同一服务上补 F-2 wire 面）：holder 仍占额——\n'
    '        // 等其完成（发完剩余 body）后测。\n'
    '        let rest = vec![b' + "'H'" + '; 1048576 - 64 * 1024];\n'
    '        holder.write_all(&rest).unwrap();\n'
    '        let (sh, _hh, bh) = read_response(&mut holder);\n'
    '        assert_eq!(sh, 201, "holder completes: {}", String::from_utf8_lossy(&bh));\n'
    '        assert_eq!(std::fs::read(root.join("raw/data.bin")).unwrap().len(), 1048576);\n'
    '        // quoted boundary multipart：boundary 参数带引号 → 201。\n'
    '        let payload: Vec<u8> = (0..4096usize).map(|i| (i % 251) as u8).collect();\n'
    '        let body = multipart_body("QB730", "hi", &payload);\n'
    '        let (sq, _hq, bq) = raw_request_with_body(\n'
    '            port,\n'
    '            "POST",\n'
    '            "/api/uploads/mp",\n'
    '            &[\n'
    '                (\n'
    '                    "Content-Type",\n'
    '                    "multipart/form-data; boundary={BS}"QB730{BS}"",\n'
    '                )\n'
    '            ],\n'
    '            &body,\n'
    '        );\n'
    '        assert_eq!(sq, 201, "quoted boundary: {}", String::from_utf8_lossy(&bq));\n'
    '        assert_eq!(std::fs::read(root.join("mp/blob.bin")).unwrap(), payload);\n'
    '        std::env::remove_var("AUTO_HTTP_UPLOAD_ACTIVE");\n'
    '        std::env::remove_var("AUTO_HTTP_UPLOAD_QUEUE");\n'
    '        std::env::remove_var("AUTO_HTTP_UPLOAD_QUEUE_TIMEOUT_MS");\n'
    '    }\n'
    '\n'
    '    /// R1 F-5：断连收口——接收中途客户端关连接 → staging 清理（无残留）。\n'
    '    #[test]\n'
    '    fn http_e2e_plan730_vm_disconnect_cleans_staging() {\n'
    '        let (root, staging) = temp_roots("disc");\n'
    '        let port = start_server(&upload_program(&root, &staging), 18383 + 600);\n'
    '        let mut s = connect(port);\n'
    '        let head = "POST /api/uploads/raw HTTP/1.1{BS}r{BS}nHost: x{BS}r{BS}nConnection: close{BS}r{BS}nContent-Type: application/octet-stream{BS}r{BS}nContent-Length: 1048576{BS}r{BS}n{BS}r{BS}n";\n'
    '        s.write_all(head.as_bytes()).unwrap();\n'
    '        s.write_all(&vec![b' + "'D'" + '; 128 * 1024]).unwrap();\n'
    '        let _ = s.flush();\n'
    '        // 确证断连：drop（close）客户端侧。\n'
    '        drop(s);\n'
    '        let deadline = std::time::Instant::now() + Duration::from_secs(10);\n'
    '        while (std::fs::read_dir(&staging).unwrap().next().is_some()\n'
    '            || crate::http_upload_service::upload_session_count() > 0)\n'
    '            && std::time::Instant::now() < deadline\n'
    '        {\n'
    '            std::thread::sleep(Duration::from_millis(100));\n'
    '        }\n'
    '        assert!(\n'
    '            std::fs::read_dir(&staging).unwrap().next().is_none(),\n'
    '            "disconnect mid-upload cleans staging"\n'
    '        );\n'
    '        assert_eq!(crate::http_upload_service::upload_session_count(), 0);\n'
    '        assert!(!root.join("raw/data.bin").exists(), "nothing published");\n'
    '    }\n'
    '\n'
)
tests = tests.replace('{BS}', BS)
src = src.replace(anchor, tests + anchor, 1)
io.open(p, 'w', encoding='utf-8', newline='\n').write(src)
print('R1 wire tests added')
