// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Engine {
    hp: i32,
}

trait EngineTrait {
}

struct Car {
    hp: i32,
}

impl EngineTrait for Car {
}
