// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum May<T> {
    val(T),
}


fn main() {
    let x = May::val(42);
    x;
}
