// Auto-generated by a2r transpiler

use memmap2::MmapOptions;
fn main() {
    let mut mmap = MmapOptions::new().len(4).map_anon().unwrap();
    mmap[0] = 42;
    let byte0 = mmap[0].clone();
    let n = (mmap.len() as i64);
    println!("len: {}, first byte: {}", n, byte0);
    assert!(byte0 == 42);
    assert!(n == 4);
}
