// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Event {
    A,
    B(String),
}


#[derive(Clone, Debug)]
struct Sink {
}

impl Sink {
    pub fn new() -> Self {
        Self {}
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: Event, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg {
            ev => {
                match ev {
                    Event::A => println!("got A"),
                    Event::B(s) => {
                        println!("got B");
                        println!("{}", s);
                    },
                };
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_sink() -> a2r_std::task::TaskRef<Event> {
    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<Event>();
    let join = tokio::spawn(async move {
        let mut actor = Sink::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
        }
    });
    a2r_std::task::track_join(join);
    a2r_std::task::TaskRef::new(tx)
}


#[tokio::main]
async fn main() {
    let h = spawn_sink();
    h.send(Event::A);
    h.send(Event::B("hello".to_string()));
    a2r_std::task::drain_all().await;
}
