// Auto-generated by a2r transpiler

fn main() {


    let n: i64 = 42;
    println!("{}", format!("{}{}", "BENCH first ", n.to_string()));
    println!("{}", format!("{}{}", format!("{}{}", "a", "b"), "c"));
    let tag: String = "tag-".to_string();
    println!("{}", format!("{}{}", tag, n.to_string()));
}
