// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Engine {
    pub hp: i32,
}

trait EngineTrait {
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Car {
    pub hp: i32,
}

impl EngineTrait for Car {
}
