// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Engine {
    hp: i32,
}

trait EngineTrait {
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Car {
    hp: i32,
}

impl EngineTrait for Car {
}
