// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Counter {
    count: i32,
}

impl Counter {
    fn new() -> Counter {
        return Counter { count: 0 };
    }
    fn increment(&mut self) {
        self.count() = self.count() + 1;
    }
    fn get_count(&self) -> i32 {
        return self.count();
    }
}

fn main() {
    let c = Counter::new();
    c.increment();
    c.increment();
    println!("{}", c.get_count());
}
