// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use num::bigint::BigInt;
fn main() {
    let a = BigInt::from(100);
    let b = BigInt::from(200);
    let sum = a + b;
    let product = a * b;
    println!("Sum: {}", sum);
    println!("Product: {}", product);
}
