// Auto-generated by a2r transpiler

use num::bigint::BigInt;
fn main() {
    let a = BigInt::from(100);
    let b = BigInt::from(200);
    let sum = a + b;
    let product = a * b;
    assert!(sum == 300);
    assert!(product == 20000);
}
