/** @deprecated 兼容别名——分层拆解为 PlaygroundCard + SnippetRunner（Plan 581，Playground 设计 §4），过渡期后移除。 */
export { default as AutoPlayground } from './AutoPlayground.vue'
export { default as AutoPlaygroundFull } from './AutoPlaygroundFull.vue'
export { default as SnippetRunner } from './components/SnippetRunner.vue'
export { default as PlaygroundCard } from './components/PlaygroundCard.vue'
export { default as CodeEditor } from './components/CodeEditor.vue'
export { default as CodePreview } from './components/CodePreview.vue'
export { default as BytecodePanel } from './components/BytecodePanel.vue'
export { default as ConsoleOutput } from './components/ConsoleOutput.vue'
export { default as ScrollArea } from './components/ScrollArea.vue'
export { default as ExampleSelector } from './components/ExampleSelector.vue'
export { default as PlaygroundLayout } from './components/PlaygroundLayout.vue'
export { usePlayground } from './composables/usePlayground'
export { usePlaygroundFull } from './composables/usePlaygroundFull'
export { useDebugger } from './composables/useDebugger'
export { useReplayPlayer } from './composables/useReplayPlayer'
export { autoLanguage } from './lang/auto'
export type * from './types'
