// Auto-generated by a2r transpiler

fn main() {
    let mut entries: Vec<String> = Vec::new();
    entries.push("file1.txt".to_string());
    entries.push("file2.txt".to_string());
    entries.push("subdir/file3.txt".to_string());
    assert!((entries.len() as i64) == 3);

    let mut count: i64 = 0;
    for entry in &entries {
        count = count + 1;
    }
    assert!(count == 3);
}
