// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut entries = List::new();
    entries.push("file1.txt");
    entries.push("file2.txt");
    entries.push("subdir/file3.txt");
    println!("Extracted {} files", (entries.len() as i32));
    for file in entries {
        println!("  {}", file);
    }
}
