// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn get_literal() -> MayInt {
    Some(42)
}

fn main() {
    let val: MayInt = get_literal();
}