// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use crossbeam::channel::unbounded;
fn main() {
    let ch = unbounded();
    let tx = ch.sender;
    let rx = ch.receiver;
    tx.send(42).unwrap();
    let received = rx.recv().unwrap();
    println!("Received: {}", received);
}
