// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut channel = List::new();
    channel.push("msg1");
    channel.push("msg2");
    for msg in channel {
        println!("Received: {}", msg);
    }
}
