// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut unique_links: Vec<String> = List::new();
    unique_links.push("https://en.wikipedia.org/wiki/Auto");
    unique_links.push("https://en.wikipedia.org/wiki/Rust");

    for u in unique_links {
        println!("Unique link: {}", u);
    }
}
