// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut urls: Vec<String> = List::new();
    urls.push("https://httpbin.org/status/200");
    urls.push("https://httpbin.org/status/404");

    let mut status200: i32 = 200;
    let mut status404: i32 = 404;

    println!("OK: {} ({})", urls.get(0).cloned(), status200);
    println!("BROKEN: {} ({})", urls.get(1).cloned(), status404);
}
