// Auto-generated by a2r transpiler

fn main() {

    let x: i64 = 42;
    let simple: String = format!("Value: {}", x);
    println!("{}", simple);


    let a: i64 = 5;
    let b: i64 = 10;
    let expr: String = format!("Sum: {}", a + b);
    println!("{}", expr);


    let name: String = "World".to_string();
    println!("Hello {}", name);
}
