// Auto-generated by a2r transpiler

use regex::Regex;
fn main() {
    let re = Regex::new("[a-z]+@[a-z]+\\.[a-z]+").unwrap();
    let text: String = "Contact user@example.com for info".to_string();
    let matched = re.is_match(text);
    assert!(matched == true);
}
