// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::error::Error;
fn main() -> Result<(), String> {
    let result: Result<String, String> = Ok("hello");
    let val: Result<String, String> = result?;
    println!("{}", val);
    Ok(())
}
