// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rayon::prelude::*;
fn main() {
    let mut v = vec![];
    for i in 1..10 {
        v.push(i);
    }
    let target: i32 = 7;
    let found = v.par_iter().find_any(|x| x == target);
    match found {
        Some(val) => println!("Found: {}", val),
        None => println!("Not found"),
    }
}
