// Auto-generated by a2r transpiler

fn main() {
    let v: Vec<i64> = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    let target: i64 = 7;
    let mut found: bool = false;
    for x in &v {
        if x == target {
            found = true;
        }
    }
    assert!(found == true);
}
