// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rayon::prelude;
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    let target: i32 = 7;
    let found = v.par_iter().find_any(|x| x == target);
    match found {
        Some(ref val) => println!("Found: {}", val),
        None => println!("Not found"),
    }
}
