// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use log::info;
use env_logger;
fn main() {
    env_logger::init();
    info!("this is an info message");
    assert!(true);
}
