// Auto-generated by a2r transpiler

fn main() {
    let x: f64 = 2.0;
    let y: f64 = 3.0;
    let power = x.powf(y);
    let sqrt_val = x.sqrt();
    let abs_val: f64 = -5.0;
    let abs_result = abs_val.abs();
    assert!(power == 8.0);
    let sqrt_ok: bool = sqrt_val > 1.414;
    assert!(sqrt_ok);


}
