// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn check_value() -> MayBool {
    let result: bool = true;
    Some(result)
}

fn check_nil() -> MayBool {
    None
}

fn main() {
    let a: MayBool = check_value();
    let b: MayBool = check_nil();
}