// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use log::info;
use log::LevelFilter;
use log::Log;
use log::Metadata;
use log::Record;
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct SimpleLogger {}

impl SimpleLogger {
    fn new() -> SimpleLogger {
        SimpleLogger {}
    }
}

impl log::Log for SimpleLogger {
    fn enabled(&self, metadata: &Metadata) -> bool {
        metadata.level() <= log::Level::Debug
    }
    fn log(&self, record: &Record) {
        if self.enabled(record.metadata()) {
            println!("{} - {}", record.level(), record.args());
        }
    }
    fn flush(&self) {
    }
}

fn main() {
    static LOGGER: SimpleLogger = SimpleLogger {};
    log::set_logger(&LOGGER).unwrap();
    log::set_max_level(LevelFilter::Debug);
    info!("custom logger active");
    println!("done");
}
