// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use log;
fn main() {
    log.set_max_level(log.LevelFilter.Debug);
    log.info("custom logger active");
    println!("done");
}
