// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

pub enum ToolError {
    ExecutionFailed(&str),
    InvalidInput(&str),
}


impl ToolError {
    pub fn to_string(&self) -> &str {
        match self {
            ToolError::ExecutionFailed(msg) => return msg,
            ToolError::InvalidInput(msg) => return msg,
        }
    }
}
