// Auto-generated by a2r transpiler

fn main() {
    let s: String = "ABC".to_string();
    println!("{}", (s.chars().nth(0).unwrap_or('\0') as i64).to_string());
    println!("{}", (s.chars().nth(1).unwrap_or('\0') as i64).to_string());
    println!("{}", (s.chars().nth(2).unwrap_or('\0') as i64).to_string());
    let mut i: i64 = 1;
    println!("{}", format!("{}{}", (s.chars().nth((i) as usize).unwrap_or('\0') as i64).to_string(), (s.chars().nth(2).unwrap_or('\0') as i64).to_string()));
}
