// Auto-generated by a2r transpiler

trait Tool {
    fn name(&self) -> String;
}


#[derive(Clone)]
pub struct Registry {
    pub tools: std::collections::HashMap<String, Arc<dyn Tool>>,
}

impl Registry {
    pub fn new() -> Registry {
        return Registry { tools: std::collections::HashMap::new() };
    }
    pub fn register(&mut self, tool: Box<dyn Tool>) {
        let n = tool.name();
        self.tools.insert(n, Arc::from(tool));
    }
    pub fn get(&self, name: &str) -> Option<Arc<dyn Tool>> {
        return self.tools.get(name);
    }
}

fn main() {
    let r = Registry::new();
    println!("ok");
}
