//! 生成器:MarshalPlan → shim Rust 源码(std 追加段)。
//! 产物是 crates/auto-lang/src/vm/ffi/generated_std.rs,由
//! shim_rust_stdlib_dispatch 在手写臂之前优先调用(plan-430 D1 接线)。
//! 引用的 API 均为 auto-lang 既有公开/同 crate 路径(见函数头 use 列表)。

use crate::types::*;

pub fn emit_std_append_segment(plans: &[MarshalPlan]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by shim-metadata (plan-430). DO NOT EDIT BY HAND.\n");
    out.push_str("// Regenerate: cargo run -p shim-metadata -- std-emit > this file\n");
    out.push_str("#[allow(unused_variables, clippy::all)]\n");
    out.push_str("pub fn generated_std_dispatch(\n");
    out.push_str("    type_name: &str,\n    method: &str,\n");
    out.push_str("    task: &mut crate::vm::task::AutoTask,\n    vm: &crate::vm::engine::AutoVM,\n");
    out.push_str(") -> Result<Option<()>, crate::vm::engine::VMError> {\n");
    out.push_str("    use crate::vm::ffi::convert::VMConvertible;\n");
    out.push_str("    use crate::vm::ffi::rust_stdlib::RustStdlibObject;\n");
    out.push_str("    use crate::vm::ffi::stdlib::push_rust_obj;\n");
    out.push_str("    use crate::vm::engine::VMError;\n");
    out.push_str("    fn ferr(ctx: &str, e: impl std::fmt::Display) -> VMError {\n");
    out.push_str("        VMError::RuntimeError(format!(\"{ctx}: {e}\"))\n    }\n");
    out.push_str("    match (type_name, method) {\n");
    for p in plans {
        out.push_str(&emit_arm(p));
    }
    out.push_str("        _ => Ok(None),\n    }\n}\n");
    out
}

fn emit_arm(p: &MarshalPlan) -> String {
    let m = &p.method;
    let (ty, name) = (&m.type_name[..], &m.method[..]);
    let ctx = format!("{ty}.{name}");
    let mut body = String::new();

    // 1) 参数弹出(源码顺序;调用时按借用/转移传参)
    let mut argdefs = Vec::new();
    for (i, a) in p.args.iter().enumerate() {
        let nm = format!("a{i}");
        argdefs.push((
            nm.clone(),
            matches!(a, ArgPlan::BorrowStr),
            matches!(a, ArgPlan::TakeStr),
        ));
        let pop = match a {
            ArgPlan::BorrowStr | ArgPlan::TakeStr => {
                format!("String::pop_from_stack(task, vm).map_err(|e| ferr(\"{ctx} pop\", e))?")
            }
            ArgPlan::ScalarI32 => {
                format!("i32::pop_from_stack(task, vm).map_err(|e| ferr(\"{ctx} pop\", e))?")
            }
            ArgPlan::ScalarI64 => {
                format!("i64::pop_from_stack(task, vm).map_err(|e| ferr(\"{ctx} pop\", e))?")
            }
            ArgPlan::ScalarF64 => {
                format!("f64::pop_from_stack(task, vm).map_err(|e| ferr(\"{ctx} pop\", e))?")
            }
            ArgPlan::ScalarBool => "task.ram.pop_nv(); bool::default() // scalar-bool".into(),
            ArgPlan::ScalarUsize => format!("i64::pop_from_stack(task, vm).map_err(|e| ferr(\"{ctx} pop\", e))? as usize"),
            ArgPlan::SelfHandle | ArgPlan::OpaqueHandle => "task.ram.pop_i32()".into(),
        };
        if matches!(a, ArgPlan::ScalarBool) {
            // 简化:布尔参数用 pop_nv 判定
            body.push_str(&format!(
                "        let {nm} = auto_val::decode_bool(task.ram.pop_nv());\n"
            ));
        } else {
            body.push_str(&format!("        let {nm}: {t} = {pop};\n", t = arg_rust_type(a)));
        }
    }
    let callargs: Vec<String> = argdefs
        .iter()
        .enumerate()
        .map(|(i, (n, borrow, take))| {
            if *borrow {
                format!("&{n}")
            } else if *take {
                format!("{n}.clone()")
            } else {
                // 数值参数按宽槽弹出,调用处按真实宽度收窄(u64/usize/f32 等;
                // ScalarUsize 弹出时已 as usize)
                let cast = match p.method.params.get(i) {
                    Some(Ty::U64) => " as u64",
                    Some(Ty::U32) => " as u32",
                    Some(Ty::U16) => " as u16",
                    Some(Ty::U8) => " as u8",
                    Some(Ty::F32) => " as f32",
                    _ => "",
                };
                format!("{n}{cast}")
            }
        })
        .collect();

    // 2) 调用(self 处理 + 借用块作用域)
    match m.self_kind {
        SelfKind::Static => {
            body.push_str(&format!(
                "        let __r = {}::{}({});\n",
                turbofish(&rust_recv_type(ty)),
                name,
                callargs.join(", ")
            ));
        }
        SelfKind::Read => {
            body.push_str(&format!(
"        let __r = {{
            let Some(obj) = vm.get_heap_object(task.ram.pop_i32() as u64) else {{
                return Err(ferr(\"{ctx}\", \"bad handle\"));
            }};
            let guard = obj.read().unwrap();
            let Some(ro) = guard.as_any().downcast_ref::<RustStdlibObject>() else {{
                return Err(ferr(\"{ctx}\", \"not RustStdlibObject\"));
            }};
            let Some(recv) = ro.downcast_ref::<{recv_ty}>() else {{
                return Err(ferr(\"{ctx}\", \"downcast failed\"));
            }};
            recv.{name}({args}){copy}{wrap}
        }};\n",
                recv_ty = rust_recv_type(ty),
                name = name,
                args = callargs.join(", "),
                copy = if p.copy_result { ".copied()" } else { "" },
                wrap = if matches!(p.ret, RetPlan::ScalarStr) {
                    ".to_string()"
                } else if matches!((ty, name), ("String", "strip_prefix" | "strip_suffix")) {
                    ".map(|s| s.to_string())"
                } else {
                    ""
                }
            ));
        }
        // Write(&mut self)与 Move(按值 self)共用:recv 是 &mut T,
        // 方法解析对 (*recv) 自动解引用,按值 self 亦可从该位置移出。
        SelfKind::Write | SelfKind::Move => {
            body.push_str(&format!(
"        let __r = {{
            let handle = task.ram.pop_i32() as u64;
            let Some(obj) = vm.get_heap_object(handle) else {{
                return Err(ferr(\"{ctx}\", \"bad handle\"));
            }};
            let mut guard = obj.write().unwrap();
            let Some(ro) = guard.as_any_mut().downcast_mut::<RustStdlibObject>() else {{
                return Err(ferr(\"{ctx}\", \"not RustStdlibObject\"));
            }};
            let Some(recv) = ro.downcast_mut::<{recv_ty}>() else {{
                return Err(ferr(\"{ctx}\", \"downcast failed\"));
            }};
            recv.{name}({args}){wrap}
        }};\n",
                recv_ty = rust_recv_type(ty),
                name = name,
                args = callargs.join(", "),
                wrap = if matches!(p.ret, RetPlan::ScalarStr) { ".to_string()" } else { "" }
            ));
        }
    }

    // 3) 返回值压栈
    body.push_str(&match &p.ret {
        RetPlan::Void => "        task.ram.push_i32(0);\n".into(),
        RetPlan::ScalarI32 => "        task.ram.push_i32(__r as i32);\n".into(),
        RetPlan::ScalarI64 => "        task.ram.push_i64(__r as i64);\n".into(),
        RetPlan::ScalarF64 => "        task.ram.push_f64(__r as f64);\n".into(),
        RetPlan::ScalarBool => "        task.ram.push_nv(auto_val::encode_bool(__r));\n".into(),
        RetPlan::ScalarStr => "        let __s = __r.to_string();\n        let idx = vm.add_string(__s.into_bytes());\n        vm.rc_push_str_idx(task, idx);\n".into(),
        RetPlan::ChainSelf | RetPlan::ChainInPlace => {
            "        drop(__r);\n        task.ram.push_i32(handle as i32);\n".into()
        }
        RetPlan::Opaque(t) => format!(
            "        push_rust_obj(task, vm, \"{t}\", __r)?;\n"
        ),
    });
    format!("        (\"{ty}\", \"{name}\") => {{\n{body}            Ok(Some(()))\n        }}\n")
}

fn rust_recv_type(ty: &str) -> String {
    match ty {
        "String" => "String".into(),
        "Vec" => "Vec<i64>".into(), // v1:元素按 i64(Auto int 值)
        "HashMap" => "std::collections::HashMap<String, i64>".into(),
        "HashSet" => "std::collections::HashSet<String>".into(),
        "Duration" => "std::time::Duration".into(),
        "Instant" => "std::time::Instant".into(),
        "PathBuf" => "std::path::PathBuf".into(),
        other => other.into(),
    }
}

fn arg_rust_type(a: &ArgPlan) -> &'static str {
    match a {
        ArgPlan::BorrowStr | ArgPlan::TakeStr => "String",
        ArgPlan::ScalarI32 => "i32",
        ArgPlan::ScalarI64 => "i64",
        ArgPlan::ScalarF64 => "f64",
        ArgPlan::ScalarBool => "bool",
        ArgPlan::SelfHandle | ArgPlan::OpaqueHandle => "i32",
        _ => "_",
    }
}

/// Vec<i64> -> Vec::<i64>(静态调用路径的 turbofish 形式)
fn turbofish(ty: &str) -> String {
    if ty.contains('<') {
        ty.replace('<', "::<").replace('>', ">")
    } else {
        ty.to_string()
    }
}
