// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let url: String = "https://example.com/path?query=1".to_string();
    println!("Scheme: {}", Url::scheme(url));
    println!("Host: {}", Url::host(url));
    println!("Path: {}", Url::path(url));
}
