// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::fs::File;
use flate2::read::GzDecoder;
use tar::Archive;
fn main() -> Result<(), String> {
    let file = File::open("archive.tar.gz")?;
    let dec = GzDecoder::new(file);
    let mut archive = Archive::new(dec);
    archive.unpack("target")?;
    println!("Unpacked archive.tar.gz");
    Ok(())
}
