// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut dirs = Vec::new();
    dirs.push("src/");
    dirs.push("docs/");
    dirs.push("test/");
    for d in dirs {
        println!("Walking: {}", d);
    }
    println!("Walked {} directories", (dirs.len() as i32));
}
