// Auto-generated by a2r transpiler

use walkdir::WalkDir;
fn main() {
    let mut dirs: Vec<String> = Vec::new();
    dirs.push("src/".to_string());
    dirs.push("docs/".to_string());
    dirs.push("test/".to_string());
    let count = (dirs.len() as i32);
    assert!(count == 3);
    for d in dirs {
        assert!((d.len() as i32) > 0);
    }
}
