// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let messages: Vec<String> = vec!["hello".to_string(), "world".to_string()];
    let mut msg_count: i32 = 0;
    for msg in messages {
        msg_count += 1;
        if msg == "world" {
            break;
        }
    }
    assert!(msg_count == 2);
}
