// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Box<T> {
    pub value: T,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Container {
    pub data: Box<i32>,
}

fn main() {
    let x: i32 = 42;
}
