// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
struct Box<T> {
    value: T,
}

#[derive(Clone, Debug, PartialEq)]
struct Container {
    data: Box<i32>,
}

fn main() {
    let x: i32 = 42;
}
