// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn mean(data: &[i32]) -> Option<f64> {
    let count = (data.len() as i32);
    if count == 0 {
        return None;
    }
    let mut sum: i32 = 0;
    for val in data {
        sum += val;
    }
    Some((sum as f64) / (count as f64))
}

fn std_deviation(data: &[i32]) -> Option<f64> {
    let data_mean = mean(data)?;
    let count = (data.len() as i32);
    let mut variance: f64 = 0.0;
    for val in data {
        let diff: f64 = data_mean - (val as f64);
        variance += diff * diff;
    }
    variance = variance / (count as f64);
    Some(variance.sqrt())
}

fn main() {
    let data: Vec<i32> = vec![3, 1, 6, 1, 5, 8, 1, 8, 10, 11];

    let m = mean(data);
    println!("Mean: {}", m);

    let sd = std_deviation(data);
    println!("Standard deviation: {}", sd);
}
