// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn create_file(name: &str) -> String {
    return format!("created {}", name);
}

fn main() {
    println!("{}", create_file("data.txt"));
    println!("{}", create_file("my_dir"));
    println!("{}", create_file("my_dir/sub_dir/inner"));
}
