// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use tokio::fs::read;
use tokio::fs::read_to_string;
fn process_data(data: &[u8]) {
    println!("Data Length: {}", data.len() as i32);
}

#[tokio::main]
async fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    let content = read("data.txt").await?;
    process_data(content);

    let str_content = read_to_string("data.txt").await?;
    println!("Text: {}", str_content);
    Ok(())
}
