// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use tokio::fs::File;
use tokio::io::AsyncReadExt;
use tokio::io::AsyncWriteExt;
#[tokio::main]
async fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    let mut file = File::create("data.txt").await?;
    file.write_all("Generated Data!".as_bytes()).await?;

    let mut file2 = File::open("data.txt").await?;
    let mut contents: Vec<u8> = List::new();
    file2.read_to_end(contents).await?;
    println!("Data Length: {}", contents.len() as i32);
    Ok(())
}
