// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use tokio::fs::write;
#[tokio::main]
async fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    write("data.txt", "Generic data from program!").await?
}
