// Auto-generated by a2r transpiler

fn main() {
    let s: String = "hello world".to_string();
    let upper = s.to_uppercase();
    let trimmed = "  hello  ".trim().to_string();
    let parts = "a,b,c".split(",").collect::<Vec<_>>();
    let x: i32 = 42;
}
