// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut count: i32 = 0;
    loop {
        if count >= 10 { break; }
        println!("{}", count);
        count = count + 1;
    }
    println!("done");
}
