// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::sync::atomic::AtomicUsize;
use std::sync::atomic::Ordering;
use std::sync::Arc;
use std::thread;
fn main() {
    let counter = Arc::new(AtomicUsize::new(0));
    let c1 = counter.clone();
    let c2 = counter.clone();
    let t1 = thread.spawn(|_| { /* unsupported stmt in block */ });
    let t2 = thread.spawn(|_| { /* unsupported stmt in block */ });
    t1.join().unwrap();
    t2.join().unwrap();
    println!("Final count: {}", counter.load(Ordering::SeqCst));
}
