// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::time::Duration;
fn main() {
    let d = Duration::from_millis(100);
}
