// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use urlencoding::encode;
fn main() {
    let input: String = "hello world! foo=bar&baz=qux".to_string();
    let encoded = encode(input);
    println!("Encoded: {}", encoded);
}
