// Auto-generated by a2r transpiler

use urlencoding::encode;
fn main() {
    let input: String = "hello world! foo=bar&baz=qux".to_string();
    let encoded = encode(input);
    assert!(encoded.contains("hello"));
}
