// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use percent_encoding::percent_encode;
use percent_encoding;
fn main() {
    let input: String = "hello world! foo@bar.com".to_string();
    let encoded = percent_encode(input.as_bytes(), percent_encoding::NON_ALPHANUMERIC).to_string();
    assert!(a2r_std::str_contains(encoded.as_str(), "hello"));
}
