// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::error::Error;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let msg: String = "hello".to_string();
    let result: Result<String, &str> = Ok(msg);
    let val = result?;
    println!("{:?}", val);
    Ok(())
}
