// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rand;
fn main() {
    let mut rng = rand::thread_rng();
    let n: i32 = rng.gen_range(0..100);
    println!("Random number: {}", n);
}
