// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Foo {
    pub value: i64,
}

impl Foo {
    fn new(v: i64) -> Foo {
        return Foo { value: v };
    }
    fn get_value(&self) -> i64 {
        return self.value;
    }
}

fn main() {
    let f = Foo::new(42);
    println!("{}", f.get_value());
}
