// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Foo {
    value: i32,
}

impl Foo {
    fn new(v: i32) -> Foo {
        return Foo { value: v };
    }
    fn get_value(&self) -> i32 {
        return self.value;
    }
}

fn main() {
    let f = Foo::new(42);
    println!("{}", f.get_value());
}
