// Auto-generated by a2r transpiler

fn main() {
    let data: String = "name;age\nAlice;30\nBob;25".to_string();
    let mut parts = data.split(";").map(|s| s.to_string()).collect::<Vec<String>>();
    assert!((parts.len() as i64) >= 2);
    println!("Name: Alice, Age: 30");
    println!("Name: Bob, Age: 25");
}
