// Auto-generated by a2r transpiler

trait Tool {
    fn name(&self) -> String;
}


pub fn free_register(tool: Box<dyn Tool>) {
    println!("{}", tool.name());
}

#[derive(Clone)]
pub struct Reg {
    pub tools: std::collections::HashMap<String, Arc<dyn Tool>>,
}

impl Reg {
    pub fn new() -> Reg {
        return Reg { tools: std::collections::HashMap::new() };
    }
    pub fn register(&mut self, tool: Box<dyn Tool>) {
        let n = tool.name();
        self.tools.insert(n, Arc::from(tool));
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct EchoTool {}

impl Tool for EchoTool {
    fn name(&self) -> String {
        return "echo".to_string();
    }
}

fn main() {

    let t = EchoTool {};
    free_register(Box::new(t.clone()));


    let r = Reg::new();
    r.register(Box::new(t));
}
