// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use std::sync::{Arc, Mutex};

pub trait Handler {
    fn run(&self, cb: Arc<dyn Fn(i64) + Send + Sync>);
    fn on_event(&self, ev: Arc<dyn Fn(i64) -> String + Send + Sync>) -> String;
}


fn main() {
    let x: i64 = 42;
}
