// Auto-generated by a2r transpiler


pub trait Handler {
    fn run(&self, cb: Arc<dyn Fn(i32) + Send + Sync>);
    fn on_event(&self, ev: Arc<dyn Fn(i32) -> String + Send + Sync>) -> String;
}


fn main() {
    let x: i32 = 42;
}
