// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let result: Result<String, Box<dyn std::error::Error>> = Ok("hello");
    match result {
        Ok(val) => assert!(val == "hello"),
        Err(e) => assert!(false),
    }
}
