// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use anyhow::Context;
fn read_config() -> Result<(), Box<dyn std::error::Error>> {
    let path: String = "config.toml".to_string();
    let result = read_to_string(path);
    let content = result.context("Failed to read config")?;
    Ok(content)
}

fn main() {
    let result = read_config();
    println!("Config result: {}", result);
}
