// Auto-generated by a2r transpiler

fn main() {
    let result: Result<String, Box<dyn std::error::Error>> = Ok("hello");
    match result {
        Ok(val) => assert!(val == "hello"),
        Err(e) => assert!(false),
    }
}
