// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    for j in 0..10 {
        println!("{}", j);
    }

    let arr: [i32; 3] = vec![1, 2, 3];
    for n in arr {
        println!("{}", n);
    }
}
