// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Point {
    x: i32,
    y: i32,
}

impl Point {
    pub fn distance(&self) -> i32 {
        return self.x * self.x + self.y * self.y;
    }
}

pub fn get_origin() -> Point {
    return Point { x: 0, y: 0 };
}

fn main() {
    let p = get_origin();
    println!("{}", p.distance());
}
