// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
pub struct Point {
    x: i32,
    y: i32,
}

impl Point {
    pub fn distance(&self) -> i32 {
        return self.x * self.x + self.y * self.y;
    }
}

pub fn get_origin() -> Point {
    return Point { x: 0, y: 0 };
}

fn main() {
    let p = get_origin();
    println!("{}", p.distance());
}
