// Auto-generated by a2r transpiler
// NOTE: This test uses C-specific features (printf, cstr)
// which don't translate directly to idiomatic Rust

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;



fn println(msg: &str) {
    println!("{}", msg);
}

fn main() {
    let s: &str = "Hello!";
    println(s);
}
