// Auto-generated by a2r transpiler

use sha2::Sha256;
use sha2::Digest;

fn main() {
    let password: String = "secret_password".to_string();
    let salt: String = "random_salt".to_string();

    let mut hasher = Sha256::new();
    hasher.update(b { content: "salt".to_string() });
    hasher.update(b { content: "secret_password".to_string() });
    let result = hasher.finalize();

    assert!(true);
}
