// Auto-generated by a2r transpiler

fn helper(ev: &str, cb: fn(String) -> ()) {
    cb(ev);
}

fn sink(p: &str) {
    println!("{}", p);
}

fn main() {

    let f = |ev: String| { helper(ev.as_str(), sink); };
    f("hi");
}
