// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Book {
    title: String,
}

impl Book {
    fn new(title: &str) -> Book {
        return Book { title: title };
    }
}

fn main() {
    let mut shelf: Vec<Book> = List::new();
    shelf.push(Book::new("Shawshank Redemption"));
    shelf.push(Book::new("Secret Recipe"));

    for book in shelf {
        println!("Title: {}", book.title);
    }
}
