// Auto-generated by a2r transpiler

use semver::Version;
fn main() {
    let versions: Vec<String> = vec!["1.0.0".to_string(), "2.1.0".to_string(), "1.5.0".to_string(), "2.0.1".to_string()];
    let mut max = Version::parse(versions[0].clone()).unwrap();
    for v in versions {
        let parsed = Version::parse(v).unwrap();
        if parsed > max {
            max = parsed
        }
    }
    assert!(max.major == 2);
    assert!(max.minor == 1);
}
