// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn abs(x: i32) -> i32 {
    if x < 0 {
        return -x;
    }
    return x;
}

fn main() {
    println!("{}", abs(-5));
}
