// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use ansi_term::Colour;
fn main() {
    println!("{}", Colour::Red.paint("Error: something went wrong"));
    println!("{}", Colour::Green.paint("Success: operation completed"));
    println!("{}", Colour::Yellow.paint("Warning: check your input"));
}
