// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use ansi_term::Colour::Red;
use ansi_term::Colour::Green;
use ansi_term::Colour::Yellow;
fn main() {
    let err = Red::paint("Error: something went wrong");
    let ok = Green::paint("Success: operation completed");
    let warn = Yellow::paint("Warning: check your input");
    assert!(err.contains(&"Error"));
    assert!(ok.contains(&"Success"));
    assert!(warn.contains(&"Warning"));
}
