// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let value: u16 = 4660;
    let bytes = value.to_be_bytes();
    println!("BE bytes: {}, {}", bytes[0], bytes[1]);
    let le_bytes = value.to_le_bytes();
    println!("LE bytes: {}, {}", le_bytes[0], le_bytes[1]);
    let from_be = u16::from_be_bytes(bytes);
    println!("From BE: {}", from_be);
}
