// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn test_fn_with_const_param(capacity: u32) -> i32 {
    return 0;
}

fn main() {
    return 0;
}
