import { test, expect, type Page } from '@playwright/test'

// PLAN-715 T-07：首页演示行为测试。
// mock 只证明网站反馈（同源请求/成功/失败/超时/取消/诚实降级）；
// 示例内容的真实性由仓内金样（docs/reports/p715-website-ui-baseline.md §4）另证。

const EXAMPLES = [
  {
    id: 'csv-delimiter',
    auto: 'fn main() {',
    autoFile: 'csv_delimiter.at',
    output: 'Name: Alice, Age: 30',
    rust: 'Auto-generated by a2r transpiler',
  },
  {
    id: 'classify-ash',
    auto: 'fn bucket(n) {',
    autoFile: 'classify.ash',
    output: '95:high',
    rust: null,
  },
]

test.describe('home demo: preset (no network)', () => {
  for (const locale of ['/', '/zh/']) {
    test(`preset example visible and no initial API request (${locale})`, async ({ page }) => {
      const apiCalls: string[] = []
      await page.route('**/api/**', (route) => {
        apiCalls.push(route.request().url())
        return route.abort()
      })
      await page.goto(locale)
      const demo = page.locator('.home-demo')
      await expect(demo).toBeVisible()
      // 预置源码可见（v-show 三份 pane 常驻 DOM，断言可视那份）
      await expect(demo.locator('.demo-pane:visible')).toContainText('fn main()')
      // 未发任何 API 请求
      expect(apiCalls, 'no API request on load').toHaveLength(0)
      // 切到输出 tab：预置输出 + 来源标注（不显示为实时成功）
      await demo.getByRole('button', { name: /Output|输出/ }).click()
      await expect(demo.locator('.demo-output')).toContainText(EXAMPLES[0].output)
      await expect(demo.locator('.demo-output-source')).toContainText(/Preset output|预置输出/)
      await expect(demo.locator('.demo-output-source')).not.toContainText(/Live result|实时运行结果/)
    })
  }

  test('three views on csv-delimiter: Auto/Output/Rust with golden content', async ({ page }) => {
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await expect(demo.locator('.demo-pane:visible')).toContainText('data.split(";")')
    await demo.getByRole('button', { name: 'Rust (a2r)' }).click()
    await expect(demo.locator('.demo-pane:visible')).toContainText(EXAMPLES[0].rust!)
    // 证据链接指向仓内文件
    await expect(demo.locator('.demo-evidence-link').first()).toHaveAttribute(
      'href', /github\.com\/zhaopuming\/auto-lang\/blob\/master\/crates\/auto-lang\/test\/cookbook/)
  })

  test('classify-ash has no Rust tab (no fabricated transpile)', async ({ page }) => {
    await page.goto('/')
    await page.locator('.demo-picker').getByRole('tab', { name: /Functions & loops|函数与循环/ }).click()
    const demo = page.locator('.home-demo')
    await expect(demo.locator('.demo-pane:visible')).toContainText('fn bucket(n)')
    await expect(demo.getByRole('button', { name: 'Rust (a2r)' })).toHaveCount(0)
  })

  test('copy button writes source to clipboard', async ({ page, context }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write'])
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await demo.getByRole('button', { name: 'Copy', exact: true }).click()
    const text = await page.evaluate(() => navigator.clipboard.readText())
    expect(text).toContain('fn main()')
  })
})

test.describe('home demo: run feedback (mocked same-origin API)', () => {
  test('successful run replaces output and marks it live', async ({ page }) => {
    let requestUrl = ''
    let requestBody = ''
    await page.route('**/api/run', async (route) => {
      requestUrl = route.request().url()
      requestBody = route.request().postData() ?? ''
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ stdout: 'LIVE-RUN-OK\n', stderr: '' }),
      })
    })
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await demo.getByRole('button', { name: /^Run$|^运行$/ }).click()
    await expect(demo.locator('.demo-output')).toContainText('LIVE-RUN-OK')
    // 同源请求
    expect(requestUrl).toContain(new URL(page.url()).origin)
    expect(requestUrl).toContain('/api/run')
    // 请求体携带示例源码
    expect(requestBody).toContain('source')
    expect(requestBody).toContain('fn main()')
    // 来源标注变为实时
    await expect(demo.locator('.demo-output-source')).toContainText(/Live result|实时运行结果/)
  })

  test('stderr shown separately, not as stdout', async ({ page }) => {
    await page.route('**/api/run', (route) => route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ stdout: '', stderr: 'boom: runtime failure' }),
    }))
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await demo.getByRole('button', { name: /^Run$|^运行$/ }).click()
    await expect(demo.locator('.demo-error')).toContainText('boom: runtime failure')
  })

  test('failure keeps preset example reachable and reports honestly', async ({ page }) => {
    await page.route('**/api/run', (route) => route.fulfill({ status: 500, body: 'server error' }))
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await demo.getByRole('button', { name: /^Run$|^运行$/ }).click()
    await expect(demo.locator('.demo-error')).toContainText(/Could not reach|无法连接/)
    // 示例仍可查看/复制
    await demo.getByRole('button', { name: /Auto source|Auto 源码/ }).click()
    await expect(demo.locator('.demo-pane:visible')).toContainText('fn main()')
    await expect(demo.getByRole('button', { name: /^Run( again)?$|^运行$|^再次运行$/ })).toBeEnabled()
  })

  test('static hosting (no mock): connection failure degrades honestly', async ({ page }) => {
    // 不挂 mock——preview 服务没有 /api，正是静态部署形态
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await demo.getByRole('button', { name: /^Run$|^运行$/ }).click()
    await expect(demo.locator('.demo-error')).toContainText(/Could not reach|无法连接/, { timeout: 15000 })
    await expect(demo.locator('.demo-output-source')).toContainText(/Preset output|预置输出/)
  })

  test('timeout aborts after 10s with honest message', async ({ page }) => {
    test.setTimeout(25_000)
    await page.route('**/api/run', async (route) => {
      await new Promise((r) => setTimeout(r, 12_000))
      return route.fulfill({ status: 200, body: '{"stdout":"too late"}' })
    })
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await demo.getByRole('button', { name: /^Run$|^运行$/ }).click()
    await expect(demo.locator('.demo-error')).toContainText(/10 seconds|10 秒/, { timeout: 15000 })
    await expect(demo.locator('.demo-output')).toContainText('Name: Alice')
  })

  test('cancel stops the run and shows cancelled notice', async ({ page }) => {
    await page.route('**/api/run', async (route) => {
      await new Promise((r) => setTimeout(r, 5_000))
      return route.fulfill({ status: 200, body: '{"stdout":"nope"}' })
    })
    await page.goto('/')
    const demo = page.locator('.home-demo')
    await demo.getByRole('button', { name: /^Run$|^运行$/ }).click()
    await demo.getByRole('button', { name: /Cancel|取消/ }).click()
    await expect(demo.locator('.demo-error')).toContainText(/cancelled|已取消/)
  })

  test('zh locale shows zh run labels', async ({ page }) => {
    await page.route('**/api/run', (route) => route.fulfill({
      status: 200, contentType: 'application/json', body: '{"stdout":"ok"}',
    }))
    await page.goto('/zh/')
    const demo = page.locator('.home-demo')
    await expect(demo.getByRole('button', { name: /^运行$/ })).toBeVisible()
    await demo.getByRole('button', { name: /^运行$/ }).click()
    await expect(demo.locator('.demo-output-source')).toContainText('实时运行结果')
  })
})
