// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {

    let mut output_lines = Vec::new();
    output_lines.push("hello");
    output_lines.push("world");
    assert!((output_lines.len() as i32) == 2);
    assert!(output_lines.get(0) == "hello");
}
