// Auto-generated by a2r transpiler

use serde_json::Value;
fn mk_num(n: i64) {
    let a = Value::Number(serde_json::Number::from(n));
    println!("{}", a);
}

fn mk_temp(t: f64) {
    let b = Value::Number(serde_json::Number::from_f64(t).unwrap_or(serde_json::Number::from(0)));
    println!("{}", b);
}

fn main() {
    let s: String = "bob".to_string();
    let v = Value::String(s.to_string());
    let i = Value::Number(serde_json::Number::from(4096));
    let f = Value::Number(serde_json::Number::from_f64(0.7).unwrap_or(serde_json::Number::from(0)));
    mk_num(1);
    mk_temp(0.5);
    println!("{}", v);
    println!("{}", i);
    println!("{}", f);
}
