// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

async fn fetch_and_summarize(url: &str) -> String {
    let res = a2r_std::http::post_async(url, "async-post-payload").await;
    let code = res.status_code();
    let body = a2r_std::str::from_bytes(res.body_bytes());
    return body;
}

#[tokio::main]
async fn main() {
    let base = a2r_std::env::get("PLAN724_URL");


    let res = a2r_std::http::get_async(base.as_str()).await;
    let code = res.status_code();
    let ct = res.header_get("X-Plan724");
    println!("get status: {}", code);
    println!("get header: {}", ct);


    let body = fetch_and_summarize(base.as_str()).await;
    println!("helper body: {}", body);


    let req = a2r_std::http::request("POST", base.as_str());
    let req2 = req.header("X-Plan724", "async-builder");
    let req3 = req2.body("async-builder-payload");
    let bres = req3.send_async().await;
    let bbody = a2r_std::str::from_bytes(bres.body_bytes());
    println!("builder body: {}", bbody);


    let s = a2r_std::http::get_stream_async(base.as_str()).await;
        loop {
        let c = a2r_std::http::stream_next_async(&s).await;
        if c.is_empty() { break; }
        println!("chunk: {}", c);
    }
    s.close();


    let auth = { let __resp = a2r_std::http::post_sync_async(base.as_str(), "auth-payload", "").await; a2r_std::http::set_last_status(__resp.0); __resp.1 };
    println!("auth status: {}", a2r_std::http::last_status() as i64);
    println!("auth body: {}", auth);
}
