// Auto-generated by a2r transpiler

use walkdir;
use std::fs;
fn main() {
    for entry in walkdir::WalkDir::new("src").into_iter().filter_map(|e| e.ok()) {
        if entry.file_type().is_file() {
            let meta = fs::metadata(entry.path()).unwrap();
            let modified = meta.modified().unwrap();
            println!("{}: {}", entry.path().display(), modified);
        }
    }
    assert!(true);
}
