// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    println!("CREATE TABLE author (id SERIAL PRIMARY KEY, name VARCHAR NOT NULL, nationality VARCHAR)");
    println!("CREATE TABLE book (id SERIAL PRIMARY KEY, title VARCHAR NOT NULL, author_id INTEGER REFERENCES author(id))");
    println!("Tables created successfully");
}
