// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use postgres::Client;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::connect("host=localhost user=postgres")?;

    let authors = std::collections::HashMap::new();
    authors.set("J.G. Ballard", "UK");
    authors.set("George R.R. Martin", "USA");

    for name in authors.keys() {
        let nationality = authors.get(name).cloned();
        println!("Author: {} from {}", name, nationality);
    }
    Ok(())
}
