// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Author {
    name: String,
    nationality: String,
}

fn main() {
    let mut authors: Vec<Author> = List::new();
    authors.push(Author { name: "J.G. Ballard".to_string(), nationality: "UK".to_string() });
    authors.push(Author { name: "George R.R. Martin".to_string(), nationality: "USA".to_string() });

    for author in authors {
        println!("{} ({})", author.name, author.nationality);
    }
}
