// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut counts: std::collections::HashMap<String, i32> = std::collections::HashMap::new();
    counts.set("UK", 1);
    counts.set("USA", 2);

    for key in counts.keys() {
        let val = counts.get(key).cloned();
        println!("{}: {} authors", key, val);
    }
}
