// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use postgres::Client;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::connect("host=localhost user=postgres")?;
    println!("Connected to postgres");
    Ok(())
}
