// DO NOT EDIT — generated by `auto ui build --target gallery-stubs`.
// Widget names + routes, derived from LIBRARY_WIDGETS (sorted).
export interface GeneratedWidgetEntry {
  name: string
  route: string
}

export const generatedWidgets: GeneratedWidgetEntry[] = [
  { name: 'avatar', route: '/avatar' },
  { name: 'badge', route: '/badge' },
  { name: 'button', route: '/button' },
  { name: 'card', route: '/card' },
  { name: 'checkbox', route: '/checkbox' },
  { name: 'dialog', route: '/dialog' },
  { name: 'input', route: '/input' },
  { name: 'label', route: '/label' },
  { name: 'separator', route: '/separator' },
  { name: 'switch', route: '/switch' },
  { name: 'tabs', route: '/tabs' },
  { name: 'textarea', route: '/textarea' },
]
