// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::fs;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let entries = fs::read_dir(".")?;
    let mut count: i32 = 0;
    for entry in entries {
        let entry = entry?;
        count += 1;
    }

    assert!(count > 0)
}
