// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use log::info;
use log::debug;
fn process() {
    debug!("processing step 1");
    debug!("processing step 2");
    info!("processing complete");
}

fn main() {
    env_logger::init();
    info!("app started");
    network.connect();
    process();
    println!("done");
    assert!(true);
}
