// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn get_uint() -> MayUint {
    let u: u32 = 100;
    Some(u)
}

fn main() {
    let a: MayUint = get_uint();
}