// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

pub fn check(x: i32) -> String {
    match x {
        0 => return "zero".to_string(),
        1 => return "one".to_string(),
    }
    return "other".to_string();
}
