// Auto-generated by a2r transpiler

pub fn check(x: i64) -> String {
    match x {
        0 => return "zero".to_string(),
        1 => return "one".to_string(),
    };
    return "other".to_string();
}
