// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use heapless::Vec;
fn main() {

    let mut buf = Vec::new();
    let data = "hello".as_bytes();
    for byte in data {
        buf.push(byte).unwrap();
    }
    println!("Buffer: {} bytes", (buf.len() as i32));
}
