// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn main() {

    let mut buf = Vec::new();
    buf.push(1);
    buf.push(2);
    buf.push(3);
    assert!(a2r_std::value_len(&buf) == 3);
}
