// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut buf: Vec<i32> = vec![0, 0, 0, 0, 0];
    let data: Vec<i32> = vec![104, 101, 108, 108, 111];
    for i in 0..5 {
        buf[(i) as usize] = data[(i) as usize];
    }
    println!("Buffer: {} bytes", buf.len());
}
