// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let a: Vec<Vec<i32>> = vec![vec![1, 2], vec![3, 4]];
    let b: Vec<Vec<i32>> = vec![vec![5, 6], vec![7, 8]];
    let mut c: Vec<Vec<i32>> = vec![vec![0, 0], vec![0, 0]];
    for i in 0..2 {
        for j in 0..2 {
            c[(i) as usize].clone()[(j) as usize].clone() = a[(i) as usize].clone()[(j) as usize].clone() + b[(i) as usize].clone()[(j) as usize].clone();
        }
    }
    assert!(c[0].clone()[0].clone() == 6);
    assert!(c[0].clone()[1].clone() == 8);
    assert!(c[1].clone()[0].clone() == 10);
    assert!(c[1].clone()[1].clone() == 12);
}
