// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn test_fn_with_const_param(_capacity: u32) -> i32 {
    return 0;
}

fn main() {
    let _ = test_fn_with_const_param(10);
}
