// Auto-generated by a2r transpiler

fn main() {
    let v: Vec<f64> = vec![3.0, 4.0];
    let mut sum_sq: f64 = 0.0;
    for i in 0..2 {
        sum_sq = sum_sq + v[(i) as usize].clone() * v[(i) as usize].clone();
    }
    let norm = sum_sq.sqrt();
    assert!(norm == 5.0);
}
