// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use sha2::Sha256;
use sha2::Digest;
fn main() {
    let mut hasher = Sha256::new();
    hasher.update(b { content: "hello world".to_string() });
    let result = hasher.finalize();
    println!("SHA256: {result:x}");
}
