// Auto-generated by a2r transpiler

fn inc(a: *mut i32) {
    *a += 1;
}

fn main() {
    let mut x: i32 = 5;
    println!("x =  {}", x);
    let mut y: *mut i32 = x as *mut _;
    println!("y =  {}", *y);
    *y += 1;
    println!("now x is {}", x);

    inc(x as *mut _);
    println!("now x is {}", x);
}
