// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut names = List::new();
    names.push("Alice");
    names.push("Bob");
    names.push("Charlie");
    let mut ages = List::new();
    ages.push(30);
    ages.push(25);
    ages.push(35);
    for i in 0..names.len() as i32 {
        let age = ages.get(i).cloned();
        println!("{},{},{}s", names.get(i).cloned(), age, age / 10 * 10);
    }
}
