// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use csv::Reader;
use csv::Writer;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let data: String = "name,age\nAlice,30\nBob,25".to_string();
    let mut reader = Reader::from_reader(data.as_bytes());
    let mut writer = Writer::from_writer(Vec::new());
    writer.write_record(vec!["name", "age", "decade"])?;
    for result in reader.records() {
        let record = result?;
        let name = record.get(0)?;
        let age = record.get(1)?.parse()?;
        let decade: i32 = age / 10 * 10;
        writer.write_record(vec![name, age.to_string(), decade.to_string()])?;
    }
    let output = String::from_utf8(writer.into_inner()?)?;
    println!("{}", output);
    Ok(())
}
