// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rayon::prelude;
use rand::seq::SliceRandom;
use rand::thread_rng;
fn main() {
    let mut v = vec![0..100].collect();
    let mut rng = thread_rng();
    v.shuffle(&mut rng);
    v.par_sort();
    println!("Sorted first: {}, last: {}", v[0], v[99]);
}
