// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut v: Vec<i32> = vec![99, 98, 97, 3, 2, 1, 0];
    v.sort();
    assert!(v[0].clone() == 0);
    assert!(v[6].clone() == 99);
}
