// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use url::Url;
fn main() {
    let url = Url::parse("https://example.com/path?query=1").unwrap();
    let new_url = url.join("sub/page").unwrap();
    println!("Original: {}", url);
    println!("Joined: {}", new_url);
}
