// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let url: String = "https://example.com/path?query=1".to_string();
    let encoded = Url::encode("hello world");
    let decoded = Url::decode("hello%20world");
    println!("Scheme: {}", Url::scheme(url));
    println!("Encoded: {}", encoded);
    println!("Decoded: {}", decoded);
}
