// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use url::Url;
fn main() {
    let url = Url::parse("https://example.com/page#section").unwrap();
    let fragment = url.fragment();
    println!("Fragment: {}", fragment);
}
