// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let u = url.parse("https://example.com/rust?name=hello&age=20");
    let query = u.query();
    println!("Query: {}", query);
}
