// Auto-generated by a2r transpiler

use log::info;
use simplelog::WriteLogger;
use simplelog::LevelFilter;
use simplelog::Config;
fn main() {
    let file = File::create("app.log").unwrap();
    WriteLogger::init(LevelFilter::Info, Config::default(), file).unwrap();
    info!("logging to custom file");
    assert!(true);
}
