<!-- Generated by AutoUI from widgets/dialog.at. Visual layer derived from shadcn-vue (MIT). See NOTICES. -->
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { DialogClose, type DialogCloseProps } from 'reka-ui'
import { cn } from '../utils'

const props = defineProps<DialogCloseProps & { class?: HTMLAttributes['class'] }>()
</script>

<template>
  <DialogClose v-bind="props" :class="cn(props.class)"><slot /></DialogClose>
</template>
