// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rand;
use rand_distr;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut rng = rand.thread_rng();
    let mut normal = Normal::new(2.0, 3.0)?;
    let v: f64 = normal.sample(rng);
    println!("Random from Normal(2, 3): {}", v);
    Ok(())
}
