// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Message {
    from: String,
    text: String,
}

impl Message {
    fn new(from: &str, text: &str) -> Message {
        return Message { from: from, text: text };
    }
}

fn main() {
    let mut inbox: Vec<Message> = List::new();
    inbox.push(Message::new("Alice", "Meeting postponed"));
    inbox.push(Message::new("Bob", "Secret Leaked"));

    for msg in inbox {
        println!("{} says: {}", msg.from, msg.text);
    }
}
