// Auto-generated by a2r transpiler


trait Tool {
    fn name(&self) -> String;
}


#[allow(dead_code)]
pub struct Callback {
    pub on_ev: Box<dyn Fn(i64) + Send + Sync>,
    pub on_done: Box<dyn Fn + Send + Sync>,
    pub on_named: Box<dyn Fn(i64) -> String + Send + Sync>,
}

pub fn set_cb(cb: Box<dyn Fn(i64) + Send + Sync>) {
    println!("set");
}

pub fn get_cb() -> Box<dyn Fn(i64) + Send + Sync> {
    return Callback { on_ev: None, on_done: None, on_named: None }.on_ev;
}

fn main() {
    let c = Callback { on_ev: None, on_done: None, on_named: None };
    set_cb(c.on_ev);
    println!("{}", get_cb() != None);
}
