// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
pub struct Settings {
    env: std::collections::HashMap<String, String>,
}

impl Settings {
    pub fn default() -> Settings {
        return Settings { env: {} };
    }
}

const SETTINGS_DIR: String = ".auto-code-rs";
