// Auto-generated by a2r transpiler

use log::debug;
use log::info;
fn main() {
    env_logger::init();
    debug!("starting operation");
    let value: i32 = 42;
    debug!("value = {}", value);
    assert!(value == 42);
}
