// Auto-generated by a2r transpiler

trait Comparable {
    fn compare(&self, other: i64) -> i64;
}


fn max_of<T: Comparable>(a: T, b: T) -> T {
    if a.compare(0) >= b.compare(0) {
        a
    } else {
        b
    }

}

fn idf<T>(x: T) -> T {
    return x;
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Score {
    pub val: i64,
}

impl Comparable for Score {
    fn compare(&self, other: i64) -> i64 {
        return self.val - other;
    }
}

fn main() {
    let mut x: Score = Score { val: 3 };
    let mut y: Score = Score { val: 9 };
    println!("{}", max_of(x.clone(), y.clone()).val);
    println!("{}", idf(7));
}
