// Auto-generated by a2r transpiler
// Plan 394 Phase C structural golden (nested async await in ~{}).

async fn work(n: i64) -> i64 {
    n
}

fn main() {
    let f = async move { work(1).await + work(2).await };
    println!("{}", f.await);
}
