// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use a2r_std::io::{say};
pub use a2r_std::io::{say};
fn main() {
    say("hello from pub use");
}
