// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct WingStruct {}

impl WingStruct {
    fn fly(&self) {
        println!("flying");
    }
}

trait WingTrait {
    fn fly(&self);
}

struct Duck {}

impl WingTrait for Duck {
    fn fly(&self) {
        println!("flying");
    }
}

fn main() {
    let d = Duck {};
    d.fly();
}
