// Auto-generated by a2r transpiler

use semver::Version;
fn main() {
    let mut v = Version::parse("1.2.3").unwrap();
    assert!(v.major == 1);
    assert!(v.minor == 2);
    assert!(v.patch == 3);
}
