// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use data_encoding::HEXLOWER;
fn main() {
    let encoded = HEXLOWER::encode(b { content: "hello world".to_string() });
    println!("Hex: {}", encoded);
    let decoded = HEXLOWER::decode(encoded.as_bytes()).unwrap();
    println!("Decoded: {} bytes", decoded.len());
}
