// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use walkdir::WalkDir;
use std::thread;
fn main() {
    let mut count: i32 = 0;
    for entry in WalkDir::new(".") {
        let entry = entry.unwrap();
        count = count + 1;
    }
    println!("Total entries: {}", count);
}
