// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut i: i32 = 0;
    let mut max: i32 = 5;

    while i < max {
        println!("{}", i);
        i = i + 1;
    }

    println!("done!");
}
