// Auto-generated by a2r transpiler

fn main() {
    let x: i64 = 42;


    let s: String = format!("{:?}", x);


    let n: i64 = "123".parse::<i64>().unwrap();


    let f: f64 = (x as f64);


    let u: u32 = (x as u32);

    println!("{}", s);
    println!("{}", n);
}
