// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let x: i32 = 42;


    let s: String = x.to_string();


    let n: i32 = "123".parse::<i32>().unwrap();


    let f: f64 = (x as f64);


    let u: u32 = (x as u32);

    println!("{}", s);
    println!("{}", n);
}
