// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
struct Complex {
    real: f64,
    imag: f64,
}

fn main() {
    let c = Complex { real: 3.0, imag: 4.0 };
    let norm = c.real * c.real + c.imag * c.imag;
    println!("Norm squared: {}", norm);
}
