// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
struct Complex {
    real: f64,
    imag: f64,
}

fn main() {
    let c = Complex { real: 3.0, imag: 4.0 };
    let norm = c.real * c.real + c.imag * c.imag;
    assert!(norm == 25.0);
}
