// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {

    let r1 = 0..10;
    let r2 = 0..=10;

    println!("r1");
    println!("r2");
}
