// Auto-generated by a2r transpiler

fn make_counter() {
    let count = std::rc::Rc::new(std::cell::RefCell::new(0));
    let inc = { let count = std::rc::Rc::clone(&count); move || { *count.borrow_mut() = *count.borrow() + 1; } };
    inc();
    inc();
    *count.borrow();
}

fn main() {
    let c = make_counter();
    println!("{}", c);
}
