// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn main() {
    let root = a2r_std::env::get("PLAN729_ROOT");


    let fr = a2r_std::http::file_response(root.as_str(), "docs/report.pdf", "{}");


    let dl = a2r_std::http::file_response(root.as_str(), "a.bin", "{\"download_name\":\"a.bin\",\"disposition\":\"inline\"}");


    let r = file_endpoint("name.txt");


    let v = a2r_std::http::file_response(root.as_str(), "v.bin", "{\"etag\":\"\\\"v1\\\"\"}");
}

fn file_endpoint(name: &str) -> a2r_std::http::FileResponse {
    return a2r_std::http::file_response("files", name, "{}");
}
