// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use std::string::String;
fn main() {
    let mut s: String = String::from("hello");
    s.push_str(" world");
    let len = a2r_std::value_len(&s);
    let trimmed = "  hi  ".trim().to_string();
    let replaced = s.replace("world", "auto");
}
