// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::string::String;
fn main() {
    let mut s: String = String::from("hello");
    s.push_str(" world");
    let len = s.len();
    let trimmed = "  hi  ".trim();
    let replaced = s.replace("world", "auto");
}
