// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use log::info;
fn main() -> Result<(), String> {
    let file = std.fs.create("app.log")?;
    info!("logging to custom file");
    println!("log written to app.log");
    Ok(())
}
