// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let status: i32 = 200;
    println!("Status: {}", status);
    println!("Content-Type: application/json");
    println!("Content-Length: 1234");
}
