// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let add = |a: i32, b: i32| a + b;
    let result = add(5, 3);
    println!("{:?}", result);
}
