// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Animal {
    name: &str,
}

impl Animal {
    fn speak(&self) {
        println!("Animal sound");
    }
}

struct Dog {
    name: &str,
    breed: &str,
}

impl Dog {
    fn bark(&self) {
        println!("Woof!");
    }
    fn speak(&self) {
        println!("Animal sound");
    }
}

fn main() {
    let dog = Dog {};
    dog.name = "Buddy";
    dog.breed = "Labrador";

    dog.speak();
    dog.bark();
}
