// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let text: String = "hello".to_string();
    let chars = text.chars();
    let count = chars.count();
    assert!(count == 5);
    assert!((text.len() as i32) == 5);
}
