// Auto-generated by a2r transpiler

fn main() {
    let text: String = "hello".to_string();
    let chars = text.chars();
    let count = chars.count();
    assert!(count == 5);
    assert!((text.len() as i32) == 5);
}
