// Auto-generated by a2r transpiler

fn find(n: i64) -> Option<i64> {
    if n > 0 {
        return Some(n * 10);
    }
    return None;
}

fn main() {
    let a = find(3);
    match a {
        Some(v) => println!("{}", v),
        None => println!("none"),
    };
    let b = find(0);
    match b {
        Some(v) => println!("{}", v),
        None => println!("none"),
    };
}
