// Auto-generated by a2r transpiler

fn main() {
    let total: i64 = 0;
    let items = List<int>.new(vec![1, 2, 3]);
    for i in &items {
        total = total + i;
    }
    println!("{}", total);
}
