// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Point {
    pub x: i64,
    pub y: i64,
}

#[derive(Clone, Debug, PartialEq)]
enum Shape {
    Circle(i64),
    Rect(Point),
    None,
}


fn main() {
    let p = Point { x: 3, y: 4 };


    match p {
        Point { x, y } => println!("{}", x),
    };


    let s = Shape::Rect(p);
    match s {
        Shape::Circle(r) => println!("{}", r),
        Shape::Rect(pt) => {
            match pt {
                Point { x, y } => println!("{}", x),
            };
        },
        Shape::None => println!("none"),
    };
}
