// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use a2r_std::redis;
fn main() {
    let mut r: a2r_std::redis::RedisClient = a2r_std::redis::open("redis://127.0.0.1:6379");
    let alive: bool = r.ping();
    r.set("greeting", "hello");
    let v: String = r.get("greeting");
    println!("{}", v);
    let n: i64 = r.del("greeting");
    println!("{}", n);
    let has: bool = r.exists("greeting");
    println!("{}", has);
}
