// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::fs::File;
use std::process::{Command, Stdio};
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let outputs = File::create("out.txt")?;
    let errors = outputs.try_clone()?;

    Command::new("ls").args(vec![".", "oops"]).stdout(Stdio::from(outputs)).stderr(Stdio::from(errors)).spawn()?.wait_with_output()?
}
