// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::fs::File;
use std::process::Command;
use std::process::Stdio;
fn main() {
    let result = Command::new("echo").arg("test output").output();
    let stdout = result.stdout;
    assert!((stdout.len() as i32) > 0);
}
