// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::fs::File;
use std::process::Command;
use std::process::Stdio;
fn main() {
    let outputs = File::create("out.txt").unwrap();
    let errors = outputs.try_clone().unwrap();
    Command::new("ls").args(vec![".", "oops"]).stdout(Stdio::from(outputs)).stderr(Stdio::from(errors));
    self.spawn().unwrap();
    self.wait_with_output().unwrap();
    println!("Output written to out.txt");
}
