// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn main() {
    let base = a2r_std::env::get("PLAN724_URL");


    let res = a2r_std::http::get(base.as_str());
    let code = res.status_code();
    let ct = res.header_get("X-Plan724");
    let body = a2r_std::str::from_bytes(res.body_bytes());
    println!("get status: {}", code);
    println!("get header: {}", ct);
    println!("get body: {}", body);


    let req = a2r_std::http::request("POST", base.as_str());
    let req2 = req.header("X-Plan724", "builder");
    let req3 = req2.body("builder-payload");
    let bres = req3.send();
    let bcode = bres.status_code();
    let bbody = a2r_std::str::from_bytes(bres.body_bytes());
    println!("builder status: {}", bcode);
    println!("builder body: {}", bbody);


    let pres = a2r_std::http::post(base.as_str(), "post-payload");
    let pcode = pres.status_code();
    let pbody = a2r_std::str::from_bytes(pres.body_bytes());
    println!("post status: {}", pcode);
    println!("post body: {}", pbody);


    let s = a2r_std::http::get_stream(base.as_str());
        loop {
        let c = a2r_std::http::stream_next(&s);
        if c.is_empty() { break; }
        println!("chunk: {}", c);
    }
    s.close();


    let code2 = a2r_std::http::last_status() as i64;
    println!("last_status: {}", code2);
}
