//! Auto-generated types from api.at
//!
//! This file is generated by a2r transpiler from:
//!   - examples/api-example/back/api.at

use serde::{Deserialize, Serialize};

/// User information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub email: String,
}

/// Create user request
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateUserRequest {
    pub name: String,
    pub email: String,
}

// Implement From<CreateUserRequest> for tuple (name, email)
// This allows the command to pass parameters directly to db::create_user
impl From<CreateUserRequest> for (String, String) {
    fn from(req: CreateUserRequest) -> Self {
        (req.name, req.email)
    }
}
