# Auto-generated from main.at.at — do not edit

extends Node

func _ready():
	print("Hello from Auto!")
	print("This GDScript was generated by a2gd")
	var score: int = 100
	var lives: int = 3
	var total: int = score * lives
	print(total)
