// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::cmp::{min, max};
fn main() {
    let x = a2r_std::math::min(3, 7);
    let y = a2r_std::math::max(3, 7);
    let z = a2r_std::math::min(-1, 1);
}
