// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::cmp::{min, max};
fn main() {
    let x = std::cmp::min(3, 7);
    let y = std::cmp::max(3, 7);
    let z = std::cmp::min(-1, 1);
}
