// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rand;
use rand_distr;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut rng = rand.thread_rng();
    let mut normal = Normal::new(0.0, 1.0)?;
    let mut sum: f64 = 0.0;
    for _ in 0..1000 {
        let val: f64 = normal.sample(rng);
        sum = sum + val;
    }
    let avg: f64 = sum / 1000.0;
    println!("Average of 1000 normal samples: {}", avg);
    Ok(())
}
