// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use log::info;
fn main() {
    info.collect()("sending to syslog");
    info.collect()("daemon started");
    println!("syslog configured");
}
