// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Color {
    RED = 1,
    GREEN = 2,
    BLUE = 3,
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Color::RED => write!(f, "RED"),
            Color::GREEN => write!(f, "GREEN"),
            Color::BLUE => write!(f, "BLUE"),
        }
    }
}
impl Color {
    pub fn from_id(id: &str) -> Self {
        match id {
            "RED" | "red" => Color::RED,
            "GREEN" | "green" => Color::GREEN,
            "BLUE" | "blue" => Color::BLUE,
            _ => Color::RED
        }
    }
}

fn main() {
    let color: Color = Color::BLUE;
    println!("The color is {}", color);
}
