// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

#[derive(Clone, Debug)]
enum CounterMsg {
    Add(i64),
    Reset,
}

#[derive(Clone, Debug)]
struct Counter {
    count: i64,
}

impl Counter {
    pub fn new() -> Self {
        Self {
            count: 0,
        }
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: CounterMsg, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg {
            CounterMsg::Add(val) => {
                self.count = self.count + val;
                if self.count == 8 {
                    println!("reached eight");
                }
            }
            CounterMsg::Reset => {
                self.count = 0;
                println!("reset");
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_counter_with(count: i64) -> a2r_std::task::TaskRef<CounterMsg> {
    let (taskref, mut rx) = a2r_std::task::channel::<CounterMsg>();
    let join = tokio::spawn(async move {
        let mut actor = Counter { count: count };
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}

pub fn spawn_counter() -> a2r_std::task::TaskRef<CounterMsg> {
    let (taskref, mut rx) = a2r_std::task::channel::<CounterMsg>();
    let join = tokio::spawn(async move {
        let mut actor = Counter::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}


#[tokio::main]
async fn main() {
    let h = spawn_counter();
    h.send(CounterMsg::Add(3));
    h.send(CounterMsg::Add(5));
    h.send(CounterMsg::Reset);
    a2r_std::task::drain_all().await;
}
