// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let red: String = "\\x1b[31m".to_string();
    let green: String = "\\x1b[32m".to_string();
    let yellow: String = "\\x1b[33m".to_string();
    let reset: String = "\\x1b[0m".to_string();
    println!("{}", format!("{}{}", format!("{}{}", format!("{}", red), "Error: something went wrong"), "$reset"));
    println!("{}", format!("{}{}", format!("{}{}", format!("{}", green), "Success: operation completed"), "$reset"));
    println!("{}", format!("{}{}", format!("{}{}", format!("{}", yellow), "Warning: check your input"), "$reset"));
}
