// Auto-generated by a2r transpiler

/// This is a test function
/// With multiple lines
fn test_func(x: i32) -> i32 {
    x + 1
}

fn main() {
    let result = test_func(5);
    println!("{}", result);
}
