// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let u = url.parse("https://user:pass@example.com:8080/path?query=1#frag");
    println!("Scheme: {}", u.scheme());
    println!("Host: {}", u.host());
    println!("Port: {}", u.port());
}
