// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {

    let x: i32 = 42;
    let simple: String = format!("Value: {}", x);
    println!("{}", simple);


    let a: i32 = 5;
    let b: i32 = 10;
    let expr: String = format!("Sum: {}", a + b);
    println!("{}", expr);


    let name: String = "World".to_string();
    println!("Hello {}", name);
}
