// Auto-generated by a2r transpiler

fn main() {
    println!("{}", true);
    println!("{}", false);
    println!("{}", 1 == 2);
    println!("{}", 3 > 2);
    println!("{}", !(true));
    println!("{}", true && false);
    println!("{}", true || false);
    println!("flag={}", true);
    println!("cmp={}", 1 == 1);
}
