// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::process::{Command, Stdio};
use std::io::{BufRead, BufReader};
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let stdout = Command::new("echo").arg("hello world").arg("usb device found").stdout(Stdio::piped()).spawn()?.stdout?;

    let reader = BufReader::new(stdout);

    for line in reader.lines() {
        let l: i32 = line?;
        if l.contains("usb") {
            println!("{}", l);
        }
    }
    Ok(())
}
