// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Counter {
    count: i32,
}

impl Counter {
    pub fn increment(&self) {
        self.count() = self.count() + 1;
    }
    pub fn get(&self) -> i32 {
        return self.count();
    }
}
