// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Counter {
    count: i32,
}

impl Counter {
    pub fn increment(&self) {
        self.count() = self.count() + 1;
    }
    pub fn get(&self) -> i32 {
        return self.count();
    }
}
