// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use url::Url;
fn main() {
    let url = Url::parse("https://user:pass@example.com:8080/path?query=1#frag").unwrap();
    let scheme = url::scheme();
    let host = url::host_str();
    assert!(scheme == "https");
    assert!(host == "example.com");
}
