// Auto-generated by a2r transpiler

fn main() {
    let buf: Vec<i32> = vec![0];
    let ptr: *mut i32 = buf.as_mut_ptr();
    if ptr.is_null() {
        println!("null");
    }
    if (!ptr.is_null()) {
        println!("not null");
    }
    ptr.write(42);
    let val = ptr.read();
    println!("{}", val);
}
