// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let buf: [i32; 10] = vec![0];
    let ptr: *mut i32 = buf.as_mut_ptr();
    if ptr.is_null() {
        println!("null");
    }
    if (!ptr.is_null()) {
        println!("not null");
    }
    ptr.write(42);
    let val = ptr.read();
    println!("{}", val);
}
