// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
struct Complex {
    real: f64,
    imag: f64,
}

fn main() {
    let a = Complex { real: 1.0, imag: 2.0 };
    let b = Complex { real: 3.0, imag: 4.0 };
    let mut sum = Complex { real: a.real + b.real, imag: a.imag + b.imag };
    assert!(sum.real == 4.0);
    assert!(sum.imag == 6.0);
}
