// Auto-generated by a2r transpiler

fn main() {
    if std::fs::write(&"lines.txt", &"Rust\nFun\nAuto").is_ok() { 0 } else { -1 };
    let data = std::fs::read_to_string("lines.txt").unwrap_or_default();
    assert!((data.len() as i64) == 13);
    assert!(data == "Rust\nFun\nAuto");
    File::delete("lines.txt");
}
