// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    File::write_text("lines.txt", "Rust\nFun\nAuto");
    let data = File::read_text("lines.txt");
    println!("Read {} chars", (data.len() as i32));
    File::delete("lines.txt");
}
