// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use semver::Version;
fn main() {
    let mut v = Version::parse("1.2.3").unwrap();
    v.patch += 1;
    println!("Next patch: {}", v);
    v.minor += 1;
    v.patch = 0;
    println!("Next minor: {}", v);
}
