// Auto-generated by a2r transpiler

use semver::Version;
fn main() {
    let mut v = Version::parse("1.2.3").unwrap();
    v.patch = v.patch + 1;
    assert!(v.patch == 4);
    v.minor = v.minor + 1;
    v.patch = 0;
    assert!(v.minor == 3);
    assert!(v.patch == 0);
}
