// Auto-generated by a2r transpiler

use same_file;
use std::path::Path;
fn main() {
    let path1 = Path::new("a.txt");
    let path2 = Path::new("a.txt");
    if same_file::is_same_file(path1, path2).unwrap() {
        assert!(true);
    }
}
