// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use same_file;
use std::path::Path;
fn main() {
    let path1 = Path::new("a.txt");
    let path2 = Path::new("a.txt");
    if same_file::is_same_file(path1, path2).unwrap() {
        println!("Same file, skipping copy");
    }
}
