// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Message {
    role: String,
    content: String,
}

pub fn load() -> Result<Vec<Message>, String> {
    let mut messages = Vec::new();
    return Ok(messages);
}
