// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use log::info;
use chrono::Local;
fn main() {
    let now = Local::now();
    println!("[{}] application started", now);
    info.collect()("with timestamp logging");
}
