// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

#[derive(Clone, Debug)]
struct Sink {
    log: String,
    cb: Box<dyn Fn(String)>,
}

impl Sink {
    pub fn new() -> Self {
        Self {
            log: "",
            cb: Box::new(move |e: String| { println!("cb:{e}"); }),
        }
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: String, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg.as_str() {
            ev => {
                self.cb(ev);
                self.log = ev;
                println!("{}", self.log);
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_sink_with(log: String, cb: Box<dyn Fn(String)>) -> a2r_std::task::TaskRef<String> {
    let (taskref, mut rx) = a2r_std::task::channel::<String>();
    let join = tokio::spawn(async move {
        let mut actor = Sink { log: log, cb: cb };
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}

pub fn spawn_sink() -> a2r_std::task::TaskRef<String> {
    let (taskref, mut rx) = a2r_std::task::channel::<String>();
    let join = tokio::spawn(async move {
        let mut actor = Sink::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}


#[tokio::main]
async fn main() {
    let h = spawn_sink();
    h.send("x".to_string());
    a2r_std::task::drain_all().await;
}
