// Auto-generated by a2r transpiler

fn main() {
    let name: String = "World".to_string();;
    let age: i32 = 25;;
    let msg: String = format!("Hello {},
you are {} years old.", name, age);;
    println!("{}", msg);
    let result: String = format!("Sum: {}", age + 1);;
    println!("{}", result);
}
