// Auto-generated by a2r transpiler

fn main() {
    let x: i64 = 10;
    let y: i64 = 20;
    let z: i64 = 30;

    let result1: i64 = x + y * z;
    let result2: i64 = x + y * z;
    let result3: i64 = x + y * z - x;

    println!("Result1: {}", result1);
    println!("Result2: {}", result2);
    println!("Result3: {}", result3);

    let a: i64 = 5;
    let b: i64 = a * 2 + a / 2 - 1;
    println!("b: {}", b);
}
