// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn main() {
    let base = a2r_std::env::get("PLAN727_URL");
    let dst = a2r_std::env::get("PLAN727_DST");
    let src = a2r_std::env::get("PLAN727_SRC");


    let t = a2r_std::http::transfer_download(base.as_str(), dst.as_str(), "{}");
    let receipt = a2r_std::http::transfer_wait(&t);
    println!("receipt: {}", receipt);


    let up = a2r_std::http::transfer_upload(base.as_str(), src.as_str(), "{\"fields\":{\"note\":\"plan727\"}}");
    let up_receipt = a2r_std::http::transfer_wait(&up);
    println!("up_receipt: {}", up_receipt);
    let err = a2r_std::http::transfer_error(&up);
    println!("error: {}", err);


    let c = a2r_std::http::transfer_download(base.as_str(), dst.as_str(), "{}");
    let p = a2r_std::http::transfer_next_progress(&c);
    println!("progress: {}", p);
    a2r_std::http::transfer_cancel(&c);
    let c_receipt = a2r_std::http::transfer_wait(&c);
    println!("c_receipt: {}", c_receipt);
}
