// Auto-generated by a2r transpiler

fn main() {
    let f = async move { let mut found: i64 = 0; for i in 0..3 {
        found = found + i;
    } if found > 0 {
        println!("nonempty");
    } found; };
    println!("{}", f);
}
