// Auto-generated by a2r transpiler

fn handler(Path(id): Path<String>) -> Path<String> {
    return id;
}

fn full_handler(Path(id): Path<String>, body: &str) -> Path<String> {
    return id;
}

fn multi(Path(id): Path<String>, Json(data): Json<String>) -> Path<String> {
    return id;
}

fn normal(name: &str, count: i64) -> String {
    return name.to_string();
}
