// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let s: String = "hello";


    let v1: String = &s;
    let v2: String = &s;



    println!("{}", v1);
    println!("{}", v2);
}
