// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let s: &str = "hello";


    let v1: &str = &s;
    let v2: &str = &s;



    println!("{}", v1);
    println!("{}", v2);
}
