// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

#[derive(Clone, Debug)]
struct Counter {
    count: i64,
    label: String,
}

impl Counter {
    pub fn new() -> Self {
        Self {
            count: 0,
            label: "default",
        }
    }

    pub async fn start(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn stop(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        Ok(())
    }

    pub async fn handle_msg(&mut self, msg: i64, reply_tx: a2r_std::task::NopReply) -> Result<(), Box<dyn std::error::Error>> {
        match msg {
            n => {
                self.count = self.count + n;
                println!("{label}: {count}");
            }
            _ => {
                let _ = msg;
            }
        };
        Ok(())
    }
}

pub fn spawn_counter_with(count: i64, label: String) -> a2r_std::task::TaskRef<i64> {
    let (taskref, mut rx) = a2r_std::task::channel::<i64>();
    let join = tokio::spawn(async move {
        let mut actor = Counter { count: count, label: label };
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}

pub fn spawn_counter() -> a2r_std::task::TaskRef<i64> {
    let (taskref, mut rx) = a2r_std::task::channel::<i64>();
    let join = tokio::spawn(async move {
        let mut actor = Counter::new();
        let _ = actor.start().await;
        while let Some(msg) = rx.recv().await {
            let reply_tx = a2r_std::task::NopReply;
            let _ = actor.handle_msg(msg, reply_tx).await;
            rx.mark_processed();
        }
    });
    a2r_std::task::track_join(join);
    taskref
}


#[tokio::main]
async fn main() {

    let h = spawn_counter_with(10, "mycounter");
    h.send(5);
    a2r_std::task::drain_all().await;
}
