// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use a2r_std::sqlite;
fn main() {
    let db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open("notes_415b.db");
    db.exec("CREATE TABLE notes (id INTEGER PRIMARY KEY, body TEXT); INSERT INTO notes (body) VALUES ('first')");
    let err: String = a2r_std::sqlite::last_error();
    println!("{}", err);
}
