// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn precise_value() -> MayDouble {
    let e: f64 = 2.718281828;
    Some(e)
}

fn main() {
    let val: MayDouble = precise_value();
}