// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let a: Vec<Vec<f64>> = vec![vec![1.0, 2.0], vec![3.0, 4.0]];
    let det: f64 = a[0][0] * a[1][1] - a[0][1] * a[1][0];
    let mut inv: Vec<Vec<f64>> = vec![vec![0.0, 0.0], vec![0.0, 0.0]];
    inv[0][0] = a[1][1] / det;
    inv[0][1] = -a[0][1] / det;
    inv[1][0] = -a[1][0] / det;
    inv[1][1] = a[0][0] / det;
    println!("Inverse: {} {}", inv[0][0], inv[0][1]);
    println!("         {} {}", inv[1][0], inv[1][1]);
}
