// Auto-generated by a2r transpiler

use ndarray::arr2;
use ndarray_linalg::Inverse;
fn main() {
    let a = arr2(vec![vec![1.0, 2.0], vec![3.0, 4.0]]);
    let inv = a.inv().unwrap();
    assert!(true);
}
