// Auto-generated by a2r transpiler
// NOTE: Type aliases in AutoLang transpile differently in Rust

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

// Type alias: In Rust, we use the List from a2r_std
// type List<T> = List<T, Heap> -> just use List<T> from a2r_std

fn main() {
    let list: List<i32> = List::new();
    list.push(1);
    list.push(2);
}
