// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Blob {
    pub data: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct ToolCallRec {
    pub tool: String,
    pub blob: Blob,
    pub note: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct WorkProduct {
    pub path: String,
    pub description: String,
}

#[derive(Clone, Debug, PartialEq)]
struct AgentRes {
    pub tool_calls: Vec<ToolCallRec>,
    pub total_tokens: i64,
}

fn take_blob(b: Blob) -> String {
    return b.data;
}

fn take_note(note: &str) -> String {
    return note.to_string();
}

fn build_handoff(result: AgentRes) -> String {
    let mut acc: String = "".to_string();
    for tc in &result.tool_calls {
        acc = take_blob(tc.blob.clone());
        let wp = WorkProduct { path: acc.to_string(), description: tc.tool.clone() };
        acc = wp.description;
        acc = take_note(tc.note);
    }
    let mut total: i64 = result.total_tokens.clone();
    total = total + 1;
    return acc;
}

fn main() {
    let r = AgentRes { tool_calls: vec![], total_tokens: 5 };
    println!("{}", build_handoff(r.clone()));
}
