// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use chrono::Local;
fn main() {
    let now = Local::now();
    let formatted = now.format("%Y-%m-%d %H:%M:%S");
    println!("Formatted: {}", formatted);
}
