// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct ChannelListener {
    pub count: i64,
}

impl ForeignTrait for ChannelListener {
    fn on_event(&self, evt: i64) -> i64 {
        return self.count + evt;
    }
}

fn main() {
    let l = ChannelListener { count: 1 };
    let r = l.on_event(2);
    println!("trait_impl_ok  {}", r);
}
