// Auto-generated by a2r transpiler

fn main() {
    let a: Vec<f64> = vec![1.0, 2.0, 3.0];
    let b: Vec<f64> = vec![1.0, 2.0, 3.0];
    let mut equal: bool = true;
    for i in 0..3 {
        if a[(i) as usize].clone() != b[(i) as usize].clone() {
            equal = false
        }
    }
    assert!(equal == true);
}
