// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Tree {
    value: i32,
    children: Vec<Tree>,
}

fn main() {
    let t = Tree { value: 1, children: vec![] };
}
