// Auto-generated by a2r transpiler

fn counter(start: i64, count: i64) -> impl futures::Stream<Item = i64> { async_stream::stream! {{
    let mut i: i64 = 0;
    while i < count {
        yield start + i;
        i = i + 1;
    }
} } }

#[tokio::main]
pub async fn main() {
    let mut sum: i64 = 0;
        let mut __s = counter(10, 3);
    tokio::pin!(__s);
    while let Some(n) = futures::StreamExt::next(&mut __s).await {
        sum = sum + n;
    }
    println!("{}", sum);
}
