// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn inc(a: *mut i32) {
    unsafe { *a += 1; }
}

fn main() {
    let mut x: i32 = 5;
    println!("x =  {}", x);
    let y: *mut i32 = &mut x as *mut _;
    unsafe {
        println!("y =  {}", *y);
        *y += 1;
    }
    println!("now x is {}", x);

    inc(&mut x as *mut _);
    println!("now x is {}", x);
}
