// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let config_path = a2r_std::env::get_or("CONFIG", "/etc/myapp/config");
    let config = File::read_text(config_path);
    println!("Config: {}", config);
}
