// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::env;
use std::fs;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let config_path = a2r_std::env::get_or("CONFIG", "/etc/myapp/config");
    let config = a2r_std::fs::read_to_string(config_path.as_str())?;
    println!("Config: {}", config);
    Ok(())
}
