// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;


fn main() {
    let list: List<i32> = List::new();
    list.push(100);
    list.push(200);


    // In AutoLang, list[i] returns May<T>, so ?? becomes unwrap_or
    // list[0] ?? 0 -> list.get(0).unwrap_or(0)
    let val1 = list.get(0).unwrap_or(0);
    let val2 = list.get(5).unwrap_or(999);
}
