// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use semver::VersionReq;
fn main() {
    let req = VersionReq::parse(">=1.2.0, <2.0.0").unwrap();
    let v1 = semver.Version.parse("1.5.0").unwrap();
    let v2 = semver.Version.parse("2.0.0").unwrap();
    println!("1.5.0 matches: {}", req.matches(v1));
    println!("2.0.0 matches: {}", req.matches(v2));
}
