// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn get_value() -> MayInt {
    let x: i32 = 42;
    Some(x)
}

fn get_nil() -> MayInt {
    None
}

fn main() {
    let a: MayInt = get_value();
    let b: MayInt = get_nil();
}