// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use semver::Version;
fn main() {
    let v = Version::parse("1.2.3").unwrap();
    let threshold = Version::parse("1.0.0").unwrap();
    let mut is_greater: bool = false;
    if v > threshold {
        is_greater = true
    }
    assert!(is_greater == true);
}
