// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use std::rc::Rc;
#[allow(unused_imports)]
use std::cell::{RefCell, Cell};
fn main() {
    let hits = std::rc::Rc::new(std::cell::RefCell::new(0));
    let bump = { let hits = std::rc::Rc::clone(&hits); move || { *hits.borrow_mut() = *hits.borrow() + 1} };
    bump();
    println!("{}", *hits.borrow());
}
