// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Settings {
    env: std::collections::HashMap<String, String>,
}

impl Settings {
    pub fn default() -> Settings {
        return Settings { env: {} };
    }
    pub fn inject_env(settings: Settings) {

    }
}
