// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
pub struct Settings {
    pub env: std::collections::HashMap<String, String>,
}

impl Settings {
    pub fn default() -> Settings {
        return Settings { env: std::collections::HashMap::new() };
    }
    pub fn inject_env(settings: Settings) {

    }
}
