// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::collections::HashMap;
fn main() {
    let mut map: HashMap<String, i32> = HashMap::new();
    map.insert("a".to_string(), 1);
    map.insert("b".to_string(), 2);
    let val = map.get("a").cloned();
    let has = map.contains_key("b");
    let len = a2r_std::value_len(&map);
    map.remove("a");
}
