// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use crossbeam;
fn main() {
    crossbeam::scope(|s| { s.spawn(|_| { println!("Hello from scoped thread 1"); }); s.spawn(|_| { println!("Hello from scoped thread 2"); }); }).unwrap();
    println!("All threads completed");
}
