// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;


fn main() {
    let list: List<i32> = List::new();


    let _len = list.len();
    let _is_empty = list.is_empty();


    list.push(10);
    list.push(20);
    list.push(30);

    let _new_len = list.len();
}
