// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::env;
use std::process::Command;
fn main() {
    let home = env::var("HOME");
    let args = env::args();
    let output = Command::new("ls").arg("-la").output();
}
