// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rand;
use rand::Rng;
fn main() {
    let mut rng = rand::thread_rng();
    let choices: Vec<String> = vec!["a".to_string(), "b".to_string(), "c".to_string(), "d".to_string(), "e".to_string()];
    let idx = rng.gen_range(0..(choices.len() as i32));
    let choice: String = choices[(idx) as usize].clone();
    let valid: bool = idx >= 0;
    assert!(valid);
}
