// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::error::Error;
fn inner() -> Result<String, Box<dyn std::error::Error>> {
    Err("inner error".into())
}

fn outer() -> Result<String, Box<dyn std::error::Error>> {
    let result = inner()?;
    Ok(result)
}

fn main() {
    let result = outer();
    let mut got_err: bool = false;
    match result {
        Ok(val) => println!("Success: {}", val),
        Err(e) => got_err = true,
    }
    assert!(got_err == true);
}
