// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::iter::Iterator;
fn main() {
    let nums: Vec<i32> = vec![1, 2, 3];
    let doubled = nums.iter().map(|x| x * 2);
    let total = nums.iter().fold(0, |acc, x| acc + x);
}
