// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rand;
use rand::Rng;
fn main() {
    let mut rng = rand::thread_rng();
    let x: i32 = rng.gen_range(0..5);
    let y: i32 = rng.gen_range(10..20);
    let x_ok: bool = x >= 0;
    let y_ok: bool = y >= 10;
    assert!(x_ok);
    assert!(y_ok);
}
