// Auto-generated by a2r transpiler

use once_cell::sync::Lazy;
use std::sync::Mutex;

static ROOTS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

fn replace_at(ridx: i64, nid: i64) {
    (*ROOTS.lock().unwrap())[(ridx) as usize] = nid;
}
