// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::env;
use std::fs;
fn main() -> Result<(), String> {
    let config_path = std::env::var("CONFIG").ok().unwrap_or("/etc/myapp/config".to_string());
    let config = std::fs::read_to_string(config_path).ok()?;
    println!("Config: {}", config);
    Ok(())
}
