// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use tokio::sync::mpsc::channel;
use tokio::sync::oneshot;
#[derive(Clone, Debug, PartialEq, Eq)]
struct DriverStatus {
    driver_id: u32,
    lat: f64,
    lng: f64,
    update_count: u32,
}

impl DriverStatus {
    fn new(driver_id: u32) -> DriverStatus {
        return DriverStatus { driver_id: driver_id, lat: 0.0, lng: 0.0, update_count: 0 };
    }
}

fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    println!("Actor pattern demo");
    Ok(())
}
