// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::time::Duration;
use std::time::Instant;
async fn main() -> () {
    let start = Instant::now();
    println!("waiting 10 ms...");
    let elapsed = start.elapsed();
    println!("done in {:?}", elapsed);
}
