// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::vec::Vec;
fn main() {
    let mut vec: Vec<i32> = vec![1, 5, 10, 2, 15];
    vec.sort();
    assert!(vec[0].clone() == 1);
    assert!(vec[1].clone() == 2);
    assert!(vec[2].clone() == 5);
    assert!(vec[3].clone() == 10);
    assert!(vec[4].clone() == 15);
}
