// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Animal {
    pub name: String,
}

impl Animal {
    fn speak(&self) {
        println!("Animal sound");
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Dog {
    pub name: String,
    pub breed: String,
}

impl Dog {
    fn bark(&self) {
        println!("Woof!");
    }
    fn speak(&self) {
        println!("Animal sound");
    }
}

fn main() {
    let mut dog = Dog {};
    dog.name = "Buddy".to_string();
    dog.breed = "Labrador".to_string();

    dog.speak();
    dog.bark();
}
