// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Animal {
    name: String,
}

impl Animal {
    fn speak(&self) {
        println!("Animal sound");
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Dog {
    name: String,
    breed: String,
}

impl Dog {
    fn bark(&self) {
        println!("Woof!");
    }
    fn speak(&self) {
        println!("Animal sound");
    }
}

fn main() {
    let mut dog = Dog {};
    dog.name = "Buddy";
    dog.breed = "Labrador";

    dog.speak();
    dog.bark();
}
