// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Point {
    x: i32,
    y: i32,
}

impl Point {
    fn origin(&self) -> Point {
        return Point { x: 0, y: 0 };
    }
}

impl Default for Point {
    fn default(&self) -> Point {
        return Point { x: 0, y: 0 };
    }
}

fn main() {
    let p = Point::default();
    let o = Point::origin();
}
