// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use ndarray::arr2;
use serde_json;
fn main() {
    let json: String = "[[1,2,3],[4,5,6]]".to_string();
    let matrix = serde_json.from_str(json).unwrap();
    println!("Matrix: {}", matrix);
}
