// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut entries = List::new();
    entries.push("backup/file1.txt");
    entries.push("backup/file2.txt");
    entries.push("backup/subdir/file3.txt");
    println!("Archive contains {} entries", (entries.len() as i32));
    for entry in entries {
        println!("  {:?}", entry);
    }
}
