// Auto-generated by a2r transpiler

use std::collections::HashMap;
use std::fs;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut seen: HashMap<String, bool> = HashMap::new();
    let entries = fs::read_dir(".")?;
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name();
        let name_str = name.to_str().unwrap();
        if seen.contains_key(&name_str) {
            println!("Duplicate: {}", name_str)
        } else {
            seen.insert(name_str.to_string(), true)
        }

    }
    assert!(true)
}
