// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use walkdir;
fn main() {
    for entry in walkdir::WalkDir::new(".") {
        let entry = entry.unwrap();
        println!("{:?}", entry.path().display().to_string());
    }
}
