// Auto-generated by a2r transpiler

use walkdir;
fn main() {
    let mut count: i32 = 0;
    for entry in walkdir::WalkDir::new(".") {
        let entry = entry.unwrap();
        count += 1;
    }
    assert!(count > 0);
}
