// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::fs;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut total: u32 = 0;
    let entries = fs.read_dir(".")?;
    for entry in entries {
        let entry: i32 = entry?;
        let meta = entry.metadata()?;
        total = total + (meta.len() as i32);
    }
    println!("Total size: {} bytes", total);
    Ok(())
}
