// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
enum Message {
    Quit,
    Move(i32),
    Write(String),
}


fn handle(msg: Message) -> i32 {
    match msg {
        Message::Quit => 0,
        Message::Move(dist) => {
            println!("Moving:");
            println!("{}", dist);
            return dist;
        },
        Message::Write(text) => {
            println!("{}", text);
            return (text.len() as i32);
        },
    }
}

fn main() {
    let m1 = Message::Move(10);
    let r1 = handle(m1.clone());
    println!("{}", r1);

    let m2 = Message::Write("hello".to_string());
    let r2 = handle(m2.clone());
    println!("{}", r2);
}
