// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

trait Engine {
    fn start(&self);
}


trait Weapon {
    fn fire(&self);
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct WarpDrive {}

impl WarpDrive {
    fn start(&self) {
        println!("WarpDrive engaging");
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct LaserCannon {}

impl LaserCannon {
    fn fire(&self) {
        println!("Pew! Pew!");
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Starship {
    core: WarpDrive,
    weapon: LaserCannon,
}

fn main() {
    let ship = Starship {};
    ship.start();
    ship.fire();
}
