// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use std::sync::{Arc, Mutex};
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Node {
    pub value: i64,
}

fn main() {
    let x = Box::new(42);
    let node = Box::new(Node { value: 10 });
    let shared = Arc::new("hello");
}
