// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use num::Complex;
fn main() {
    let z = Complex::new(3.0, 4.0);
    let r = z.norm();
    let theta = z.arg();
    println!("Complex: {}", z);
    println!("Magnitude: {}", r);
    println!("Phase: {}", theta);
}
