// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use a2r_std::sqlite;
fn main() {
    let db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open("cats_415b.db");
    let n: i64 = db.exec("CREATE TABLE IF NOT EXISTS cats (id INTEGER PRIMARY KEY, name TEXT NOT NULL)");
    db.exec("INSERT INTO cats (name) VALUES ('Michi')");
    let rid: i64 = db.last_insert_rowid();
    println!("{}", rid);
    let rows: Vec<Vec<String>> = db.query("SELECT id, name FROM cats ORDER BY id");
    for row in &rows {
        println!("{}", row[0].clone());
        println!("{}", row[1].clone());
    }
}
