<!-- Generated by AutoUI from widgets/chat_message.at.
     Visual layer derived from shadcn-vue (MIT). See NOTICES. -->
<script setup lang="ts">

const props = defineProps<{
  role?: string
  content?: string
  timestamp?: number
  thinking?: string
  profession_id?: string
  streaming?: boolean
}>()

const roleLabel = computed(() => {
  if (props.role === 'user') return '🧑 You'
  if (props.profession_id) return '🤖 ' + props.profession_id
  return '🤖 AI'
})

const timeLabel = computed(() => {
  if (!props.timestamp) return ''
  const d = new Date(props.timestamp * 1000)
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
})

const isUser = computed(() => props.role === 'user')
</script>

<template>
  <div :class="['flex flex-col gap-0.5 msg-row', isUser ? 'msg-row-user' : 'msg-row-ai']">
    <div :class="['flex items-center gap-2 px-1', isUser ? 'justify-end' : '']">
      <span :class="['text-xs font-semibold', isUser ? 'text-primary' : 'text-muted-foreground']">{{ roleLabel }}</span>
      <span v-if="timeLabel" class="text-xs text-muted-foreground">{{ timeLabel }}</span>
    </div>
    <div :class="[
      'rounded-xl px-3.5 py-2.5 text-sm leading-relaxed break-words',
      isUser
        ? 'bg-primary text-primary-foreground rounded-br-sm self-end max-w-[85%]'
        : 'bg-card border border-border text-foreground rounded-bl-sm self-start max-w-full'
    ]">
      <slot>{{ content }}</slot>
    </div>
    <div v-if="thinking" class="px-1 text-xs text-muted-foreground italic opacity-70">
      💭 {{ thinking }}
    </div>
  </div>
</template>
