// Auto-generated by a2r transpiler

use rand;
use rand::Rng;
fn main() {
    let mut rng = rand::thread_rng();
    let charset: String = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()".to_string();
    let mut password: String = "".to_string();
    for _ in 0..16 {
        let idx = rng.gen_range(0..(charset.len() as i32));
        password = format!("{}{}", password, charset.chars().nth(idx as usize).unwrap_or('\0'));
    }
    assert!((password.len() as i32) == 16);
}
