// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rand::Rng;
use rand::thread_rng;
fn main() {
    let mut rng = thread_rng();
    let charset: String = "abcdefghijklmnopqrstuvwxyz".to_string();
    let mut password: String = "".to_string();
    for _ in 0..16 {
        let idx = rng.gen_range(0..charset.len());
        let ch = charset.chars().nth(idx).unwrap();
        password = password + ch.to_string();
    }
    println!("Password: {}", password);
}
