// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Flyer {
    fn fly(&self);
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Pigeon {}

impl Flyer for Pigeon {
    fn fly(&self) {
        println!("Flap Flap");
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Hawk {}

impl Flyer for Hawk {
    fn fly(&self) {
        println!("Gawk! Gawk!");
    }
}

fn main() {

    let b1 = Pigeon {};
    let b2 = Hawk {};



    let arr: Vec<Box<dyn Flyer>> = vec![Box::new(b1), Box::new(b2)];
    for b in arr {
        b.fly();
    }
}
