// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn calculate() -> MayFloat {
    let pi: f64 = 3.14159;
    Some(pi)
}

fn main() {
    let result: MayFloat = calculate();
}