// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Point {
    pub x: i64,
    pub y: i64,
}

fn mk(x: i64, y: i64) -> Point {
    return Point { x: x, y: y };
}

fn main() {
    let a = mk(3, 4);
    let b = Point { x: a.x * 2, y: a.y * 2 };
    println!("{}", a.x + a.y);
    println!("{}", b.x - b.y);
}
