// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use toml;
use toml::Value;
fn main() {
    let toml_str: String = "name = Alice".to_string();
    let parsed: toml::Value = toml::from_str(toml_str.as_str()).unwrap();
    let name = parsed.get("name").unwrap();
    println!("Parsed: {}", name);
}
