// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let toml_str: String = "name = Alice".to_string();

    assert!(a2r_std::str_contains(toml_str.as_str(), "Alice"));
}
