// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let flag_a: i32 = 1;
    let flag_b: i32 = 2;
    let flag_c: i32 = 4;
    let mut flags: i32 = 0;
    flags = flags + flag_a;
    flags = flags + flag_b;
    println!("Flags: {}", flags);
    println!("Has A: {}", flags % 2 == 1);
    println!("Has C: {}", flags >= flag_c);
    flags = flags - flag_a;
    println!("After clear A: {}", flags);
}
