// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::time::{Instant, Duration};
fn expensive_function() {

    let mut sum: i32 = 0;
    for i in 0..1000000 {
        sum += i;
    }
}

fn main() {
    let start = Instant::now();
    expensive_function();
    let duration = start.elapsed();
    println!("Time elapsed: {}", duration);
}
