// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::sync::atomic::AtomicUsize;
use std::sync::atomic::Ordering;
use std::sync::Arc;
use std::thread;
fn main() {
    let counter = Arc::new(AtomicUsize::new(0));
    let c1 = counter.clone();
    let c2 = counter.clone();
    let t1 = thread::spawn(move |_| { for i in 0..100 { c1.fetch_add(1, Ordering::SeqCst); }});
    let t2 = thread::spawn(move |_| { for i in 0..100 { c2.fetch_add(1, Ordering::SeqCst); }});
    t1.join().unwrap();
    t2.join().unwrap();
    println!("Final count: {}", counter.load(Ordering::SeqCst));
}
