// Auto-generated by a2r transpiler

fn parse_parts(s: &str) {
    let mut parts = s.split(",").map(|s| s.to_string()).collect::<Vec<String>>();
    assert!((parts.len() as i64) == 2);
}

fn main() {
    parse_parts("hello,world");
}
