// Auto-generated by a2r transpiler

fn parse_parts(s: &str) {
    let mut parts = s.split(",").collect::<Vec<_>>();
    assert!((parts.len() as i32) == 2);
}

fn main() {
    parse_parts("hello,world");
}
