// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn parse_parts(s: &str) {
    let mut parts = s.split(",");
    let first = parts.next().unwrap();
    let second = parts.next().unwrap();
    println!("First: {}", first);
    println!("Second: {}", second);
}

fn main() {
    parse_parts("hello,world");
}
