// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let key: String = "secret_key".to_string();
    let msg: String = "important_message".to_string();
    println!("HMAC-SHA256({}) verified with {}", msg, key);
}
