// Auto-generated by a2r transpiler

use sha2::Sha256;
use sha2::Digest;

fn main() {

    let mut inner = Sha256::new();
    inner.update(b { content: "key_padded_inner".to_string() });
    inner.update(b { content: "important_message".to_string() });
    let inner_hash = inner.finalize();

    let mut outer = Sha256::new();
    outer.update(b { content: "key_padded_outer".to_string() });
    outer.update(inner_hash);
    let hmac_result = outer.finalize();

    assert!(true);
}
