// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use ring::hmac;
fn main() {
    let key = hmac.Key.new(hmac.HMAC_SHA256, "secret key".as_bytes());
    let msg = "hello world".as_bytes();
    let result = hmac.sign(key, msg);
    let result_bytes = result.as_ref();
    println!("HMAC tag length: {}", result_bytes.len());
    let valid = hmac.verify(key, msg, result_bytes).is_ok();
    println!("Verification: {}", valid);
}
