// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::path::Path;
fn main() {
    let path1 = Path::new("a.txt");
    let path2 = Path::new("a.txt");
    if path1 == path2 {
        println!("Same path, skipping");
    }
}
