// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4, 5];
    let mut sum: i32 = 0;
    for x in v {
        sum += x * 2;
    }
    assert!(sum == 30);
}
