// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rayon::prelude;
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4, 5];
    let sum = v.par_iter().map(|x| x * 2).sum();
    println!("Sum of doubled: {}", sum);
}
