// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Role {
    #[serde(rename = "role_id")]
    id: i32,
    #[serde(rename = "role_name")]
    name: String,
}

fn main() {
    let r = Role { id: 1, name: "admin".to_string() };
    println!("{}", r.id);
}
