// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Role {
    #[serde(rename = "role_id")]
    pub id: i64,
    #[serde(rename = "role_name")]
    pub name: String,
}

fn main() {
    let r = Role { id: 1, name: "admin".to_string() };
    println!("{}", r.id);
}
