// Auto-generated by a2r transpiler

use rand;
use rand::Rng;
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Color::Red => write!(f, "Red"),
            Color::Green => write!(f, "Green"),
            Color::Blue => write!(f, "Blue"),
        }
    }
}
impl Color {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Red" | "red" => Color::Red,
            "Green" | "green" => Color::Green,
            "Blue" | "blue" => Color::Blue,
            _ => Color::Red
        }
    }
}

fn random_color() -> Color {
    let mut rng = rand::thread_rng();
    let n = rng.gen_range(0..3);
    match n {
        0 => Color::Red,
        1 => Color::Green,
        _ => Color::Blue,
    }
}

impl Color {
    fn debug_str(&self) -> String {
        match self {
            Color::Red => "Red".to_string(),
            Color::Green => "Green".to_string(),
            Color::Blue => "Blue".to_string(),
        }
    }
}

fn main() {
    let color: Color = random_color();
    let name = color.debug_str();

    assert!(name == "Red" || name == "Green" || name == "Blue");
}
