// Auto-generated by a2r transpiler

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Decision {
    Approve = 0,
    Deny = 1,
}

impl std::fmt::Display for Decision {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Decision::Approve => write!(f, "Approve"),
            Decision::Deny => write!(f, "Deny"),
        }
    }
}
impl Decision {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Approve" | "approve" => Decision::Approve,
            "Deny" | "deny" => Decision::Deny,
            _ => Decision::Approve
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Gate {
    pub handler: Option<fn(String) -> Decision>,
}

fn decide(gate: Gate, step_id: &str) -> Decision {
    match gate.handler {
        Some(handler) => return handler(step_id.to_string()),
        None => return Decision::Approve,
    };
    return Decision::Approve;
}

fn needs_val(val: &str) -> bool {
    return (val.len() as i64) > 0;
}

pub fn trim_guard(raw: &str) -> bool {
    return needs_val(raw.trim());
}
