// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::path::PathBuf;
fn main() {
    let p = PathBuf::from("src/main.rs");
    let p2 = p.join("lib.rs");
}
