// Auto-generated by a2r transpiler

/// Plan 610 ⑤: C ABI export face for `add` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod add_c_export {
    #[unsafe(no_mangle)]
    pub extern "C" fn add(a: i32, b: i32) -> i32 {
        super::add(a as i64, b as i64) as i32
    }
}
fn add(a: i64, b: i64) -> i64 {
    return a + b;
}

/// Plan 610 ⑤: C ABI export face for `area` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod area_c_export {
    #[unsafe(no_mangle)]
    pub extern "system" fn area(cols: i32, rows: i32) -> i32 {
        super::area(cols as i64, rows as i64) as i32
    }
}
fn area(cols: i64, rows: i64) -> i64 {
    return cols * rows;
}

fn main() {
    println!("{}", add(2, 3));
    println!("{}", area(4, 5));
}
