// PLAN-715 T-05：首页演示数据。
// 唯一原则：不造证据。source/output/rust 全部来自仓内真实文件，来源/hash/链接
// 记录于此与 docs/reports/p715-website-ui-baseline.md §4（T-01 勘定）。
// - 主示例 csv_delimiter：cookbook 语料三向 parity 族
//   （AutoVM stdout 金样 expected.out + a2r 转译金样 *.expected.rs）。
// - 辅示例 classify.ash：PLAN-713 实跑遗留（站上 18_f2-script-classify.png
//   即实跑证据）；无 a2r 产物，故不提供 Rust 视图。
// git blob hash @ worktree 基线 ff32d7004：
//   csv_delimiter.at        bb1b46d88d06d3dbbd4b0202b2cd529038e18d51
//   expected.out            2b28eacf224b806d67d74254610fd6f6572a3df5
//   csv_delimiter.expected.rs 9a26a7cb39e61f2eb96275a49811bbb52f0466c9
//   classify.ash            3bc80a25564df20d227f261fe615dd3acc7c61e4
const REPO = 'https://github.com/zhaopuming/auto-lang/blob/master'

export interface HomeDemoExample {
  id: string
  file: string
  titleEn: string
  titleZh: string
  descEn: string
  descZh: string
  source: string
  output: string
  rust?: string
  presetEvidenceEn: string
  presetEvidenceZh: string
  sourceHref: string
  outputHref: string
  rustHref?: string
}

export const HOME_DEMO_EXAMPLES: HomeDemoExample[] = [
  {
    id: 'csv-delimiter',
    file: 'csv_delimiter.at',
    titleEn: 'Everyday scripting',
    titleZh: '日常脚本',
    descEn: 'Split, filter and print — no setup, runs in the AutoVM instantly.',
    descZh: '拆分、断言、打印——零配置，AutoVM 即时运行。',
    source: `fn main() {
    let data = "name;age\\nAlice;30\\nBob;25"
    var parts = data.split(";")
    assert(parts.len() >= 2)
    print("Name: Alice, Age: 30")
    print("Name: Bob, Age: 25")
}`,
    output: `Name: Alice, Age: 30
Name: Bob, Age: 25`,
    rust: `// Auto-generated by a2r transpiler

fn main() {
    let data: String = "name;age\\nAlice;30\\nBob;25".to_string();
    let mut parts = data.split(";").map(|s| s.to_string()).collect::<Vec<String>>();
    assert!((parts.len() as i64) >= 2);
    println!("Name: Alice, Age: 30");
    println!("Name: Bob, Age: 25");
}`,
    presetEvidenceEn: 'Preset output from the repository golden file (VM corpus expected.out).',
    presetEvidenceZh: '预置输出来自仓内金样文件（VM 语料 expected.out）。',
    sourceHref: REPO + '/crates/auto-lang/test/cookbook/encoding/007_csv_delimiter/csv_delimiter.at',
    outputHref: REPO + '/crates/auto-lang/test/cookbook/encoding/007_csv_delimiter/expected.out',
    rustHref: REPO + '/crates/auto-lang/test/cookbook/encoding/007_csv_delimiter/csv_delimiter.expected.rs',
  },
  {
    id: 'classify-ash',
    file: 'classify.ash',
    titleEn: 'Functions & loops',
    titleZh: '函数与循环',
    descEn: 'Call a function for every score — the same script runs in the ash shell (observed run).',
    descZh: '对每个分数调用函数——同一脚本在 ash shell 中实跑验证。',
    source: `fn bucket(n) {
    if n >= 80 { return "high" }
    return "low"
}

var values = [95, 82, 61]
for v in values {
    print(v.str() + ":" + bucket(v))
}`,
    output: `95:high
82:high
61:low`,
    presetEvidenceEn: 'Preset output from the observed run on 2026-09-29/30 (see the AutoShell page capture).',
    presetEvidenceZh: '预置输出来自 2026-09-29/30 实跑记录（见 AutoShell 专题页截图）。',
    sourceHref: REPO + '/website/public/apps/autoshell/examples/classify.ash',
    outputHref: '/apps/autoshell/',
  },
]

/** 同源接口路径（dev 由 vite 代理到本地后端；静态部署下请求会诚实失败）。 */
export const DEMO_API_BASE = ''
export const DEMO_TIMEOUT_MS = 10_000
