// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Advisor";

trait RoleTrait {
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Advisor {}

impl RoleTrait for Advisor {
}

impl Advisor {
    pub fn name(&self) -> String {
        return "advisor".to_string();
    }
    pub fn system_prompt(&self) -> String {
        return SOUL;
    }
    pub fn model_tier(&self) -> ModelTier {
        return ModelTier::Max;
    }
    pub fn temperature(&self) -> f64 {
        return 0.3;
    }
    pub fn max_turns(&self) -> u32 {
        return 40;
    }
}

fn main() {
    " The Advisor role.\n Auto port of builtin_roles/advisor.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
