// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Superadvisor";

trait RoleTrait {
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Superadvisor {}

impl RoleTrait for Superadvisor {
}

impl Superadvisor {
    pub fn name(&self) -> String {
        return "super-advisor".to_string();
    }
    pub fn system_prompt(&self) -> String {
        return SOUL;
    }
    pub fn model_tier(&self) -> ModelTier {
        return ModelTier::Max;
    }
    pub fn temperature(&self) -> f64 {
        return 0.3;
    }
    pub fn max_turns(&self) -> u32 {
        return 120;
    }
}

fn main() {
    " The Superadvisor role.\n Auto port of builtin_roles/super_advisor.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
