// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Assistant";

trait RoleTrait {
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Assistant {}

impl RoleTrait for Assistant {
}

impl Assistant {
    pub fn name(&self) -> String {
        return "assistant".to_string();
    }
    pub fn system_prompt(&self) -> String {
        return SOUL;
    }
    pub fn model_tier(&self) -> ModelTier {
        return ModelTier::Mid;
    }
    pub fn temperature(&self) -> f64 {
        return 0.3;
    }
    pub fn max_turns(&self) -> u32 {
        return 20;
    }
    pub fn handoff_to(&self) -> Vec<String> {
        return vec!["coder".to_string(), "architect".to_string(), "reviewer".to_string()];
    }
}

fn main() {
    " The Assistant role.\n Auto port of builtin_roles/assistant.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
