// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Reviewer";

#[derive(Clone, Debug, PartialEq)]
pub struct Reviewer {}

impl Role for Reviewer {
    fn name(&self) -> String {
        return "reviewer".to_string();
    }
    fn system_prompt(&self) -> String {
        return SOUL.to_string();
    }
    fn model_tier(&self) -> ModelTier {
        return ModelTier::Pro;
    }
    fn temperature(&self) -> f64 {
        return 0.2;
    }
    fn max_turns(&self) -> u32 {
        return 50;
    }
}

fn main() {
    " The Reviewer role.\n Auto port of builtin_roles/reviewer.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
