// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Supertester";

#[derive(Clone, Debug, PartialEq)]
pub struct Supertester {}

impl Role for Supertester {
    fn name(&self) -> String {
        return "super-tester".to_string();
    }
    fn system_prompt(&self) -> String {
        return SOUL.to_string();
    }
    fn model_tier(&self) -> ModelTier {
        return ModelTier::Max;
    }
    fn temperature(&self) -> f64 {
        return 0.3;
    }
    fn max_turns(&self) -> u32 {
        return 100;
    }
}

fn main() {
    " The Supertester role.\n Auto port of builtin_roles/super_tester.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
