// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Architect";

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Architect {}

impl Role for Architect {
    fn name(&self) -> String {
        return "architect".to_string();
    }
    fn system_prompt(&self) -> String {
        return SOUL.to_string();
    }
    fn model_tier(&self) -> ModelTier {
        return ModelTier::Max;
    }
    fn temperature(&self) -> f64 {
        return 0.2;
    }
    fn max_turns(&self) -> u32 {
        return 40;
    }
    fn handoff_to(&self) -> Vec<String> {
        return vec!["planner".to_string(), "coder".to_string()];
    }
}

fn main() {
    " The Architect role.\n Auto port of builtin_roles/architect.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
