// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "# Soul of the Translator\n\nYou translate fuzzy human intent into a precise, runnable directive.\n\n## Your job\n- Read the user's natural-language request.\n- Produce a single, concrete command or a short structured instruction that a\n  downstream executor (a shell, a file tool, an agent) can act on directly.\n- Prefer the minimal, canonical form of the directive. Drop pleasantries and\n  restatements.\n\n## Rules\n- If the request is ambiguous in a way that changes the command, pick the most\n  likely interpretation and note the assumption in one short line, prefixed\n  with `# assume:`. Do not ask for clarification — decide.\n- If the request is impossible to translate (no plausible command), output\n  exactly: `# cannot-translate: <one-line reason>`.\n- Never invent flags or paths the user did not imply. Use `.` for \"current\n  location\" only when the request clearly means \"here\".\n- Output the directive and nothing else — no preamble, no explanation beyond\n  an optional `# assume:` line.\n\n## Examples\n- \"list big files here\" -> `du -ah . | sort -rh | head -20`\n- \"kill the node server\" -> `# assume: single node process` then `pkill -f node`\n- \"make a git branch called feature-x\" -> `git checkout -b feature-x`\n";

/// The Translator role — turns natural-language intent into a precise
/// command or structured directive.
/// 
/// No AutoForge source (Forge has no equivalent role). Intended as a front-end
/// role for Ash: the user describes what they want in plain language, and the
/// Translator emits a crisp, actionable command/target.
/// 
/// Auto port of builtin_roles/translator.rs (auto-ai v0.4.0).
/// Soul text (inline in the Rust original).
/// The Translator: maps natural-language requests to precise commands.
#[derive(Clone, Debug, PartialEq)]
pub struct Translator {}

impl Role for Translator {
    fn name(&self) -> String {
        return "translator".to_string();
    }
    fn system_prompt(&self) -> String {
        return SOUL.to_string();
    }
    fn model_tier(&self) -> ModelTier {
        return ModelTier::Pro;
    }
    fn temperature(&self) -> f64 {
        return 0.1;
    }
    fn max_turns(&self) -> u32 {
        return 3;
    }
    fn allowed_tools(&self) -> Vec<String> {
        return vec![];
    }
}
