// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Superadvisor";

#[derive(Clone, Debug, PartialEq)]
pub struct Superadvisor {}

impl Role for Superadvisor {
    fn name(&self) -> String {
        return "super-advisor".to_string();
    }
    fn system_prompt(&self) -> String {
        return SOUL.to_string();
    }
    fn model_tier(&self) -> ModelTier {
        return ModelTier::Max;
    }
    fn temperature(&self) -> f64 {
        return 0.3;
    }
    fn max_turns(&self) -> u32 {
        return 120;
    }
}

fn main() {
    " The Superadvisor role.\n Auto port of builtin_roles/super_advisor.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
