// Auto-generated by a2r transpiler
#![allow(dead_code, unreachable_code, unused_imports, unused_mut, unused_parens, unused_assignments, unused_variables)]

pub use crate::role_def::{Role};
pub use crate::builtin_role_assistant::{Assistant};
pub use crate::builtin_role_coder::{Coder};
pub use crate::builtin_role_architect::{Architect};
pub use crate::builtin_role_tester::{Tester};
pub use crate::builtin_role_reviewer::{Reviewer};
pub use crate::builtin_role_documenter::{Documenter};
pub use crate::builtin_role_translator::{Translator};
pub use crate::builtin_role_runner::{Runner};
pub use crate::builtin_role_advisor::{Advisor};
pub use crate::builtin_role_planner::{Planner};
pub use crate::builtin_role_gofer::{Gofer};
pub use crate::builtin_role_super_advisor::{Superadvisor};
pub use crate::builtin_role_super_coder::{Supercoder};
pub use crate::builtin_role_super_tester::{Supertester};
pub fn builtin_names() -> Vec<String> {
    return vec!["assistant".to_string(), "coder".to_string(), "architect".to_string(), "tester".to_string(), "reviewer".to_string(), "documenter".to_string(), "translator".to_string(), "runner".to_string(), "advisor".to_string(), "planner".to_string(), "gofer".to_string(), "super-advisor".to_string(), "super-coder".to_string(), "super-tester".to_string()];
}

pub fn load_builtin(name: &str) -> Option<Box<dyn Role>> {
    match name {
        "assistant" => return Some(Box::new(Assistant {})),
        "coder" => return Some(Box::new(Coder {})),
        "architect" => return Some(Box::new(Architect {})),
        "tester" => return Some(Box::new(Tester {})),
        "reviewer" => return Some(Box::new(Reviewer {})),
        "documenter" => return Some(Box::new(Documenter {})),
        "translator" => return Some(Box::new(Translator {})),
        "runner" => return Some(Box::new(Runner {})),
        "advisor" => return Some(Box::new(Advisor {})),
        "planner" => return Some(Box::new(Planner {})),
        "gofer" => return Some(Box::new(Gofer {})),
        "super-advisor" => return Some(Box::new(Superadvisor {})),
        "super-coder" => return Some(Box::new(Supercoder {})),
        "super-tester" => return Some(Box::new(Supertester {})),
        _ => return None,
    };
}
