// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Coder";

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Coder {}

impl Role for Coder {
    fn name(&self) -> String {
        return "coder".to_string();
    }
    fn system_prompt(&self) -> String {
        return SOUL.to_string();
    }
    fn model_tier(&self) -> ModelTier {
        return ModelTier::Max;
    }
    fn temperature(&self) -> f64 {
        return 0.3;
    }
    fn max_turns(&self) -> u32 {
        return 40;
    }
    fn handoff_to(&self) -> Vec<String> {
        return vec!["tester".to_string(), "reviewer".to_string()];
    }
}

fn main() {
    " The Coder role.\n Auto port of builtin_roles/coder.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
