// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Supercoder";

trait RoleTrait {
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Supercoder {}

impl RoleTrait for Supercoder {
}

impl Supercoder {
    pub fn name(&self) -> String {
        return "super-coder".to_string();
    }
    pub fn system_prompt(&self) -> String {
        return SOUL;
    }
    pub fn model_tier(&self) -> ModelTier {
        return ModelTier::Max;
    }
    pub fn temperature(&self) -> f64 {
        return 0.3;
    }
    pub fn max_turns(&self) -> u32 {
        return 120;
    }
}

fn main() {
    " The Supercoder role.\n Auto port of builtin_roles/super_coder.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
