// Auto-generated by a2r transpiler

use crate::role_def::{Role};
use crate::ai_config::{ModelTier};
const SOUL: &str = "Soul of the Documenter";

#[derive(Clone, Debug, PartialEq)]
pub struct Documenter {}

impl Role for Documenter {
    fn name(&self) -> String {
        return "documenter".to_string();
    }
    fn system_prompt(&self) -> String {
        return SOUL.to_string();
    }
    fn model_tier(&self) -> ModelTier {
        return ModelTier::Pro;
    }
    fn temperature(&self) -> f64 {
        return 0.4;
    }
    fn max_turns(&self) -> u32 {
        return 40;
    }
}

fn main() {
    " The Documenter role.\n Auto port of builtin_roles/documenter.rs.\n";
    " Soul marker (full soul loaded from resources in Rust original).\n";
}
