// Auto-generated by a2r transpiler
#![allow(dead_code, unreachable_code, unused_imports, unused_mut, unused_parens, unused_assignments, unused_variables)]

pub use crate::role_config::{ConfigRole, RoleConfig, load_role, parse_at_role, parse_tier_field, serialize_at_role, config_role_new, config_role_with_base};
