// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use crate::wire::JsonValue;
use crate::error::ToolError;
use async_trait::async_trait;

/// EchoTool — the simplest possible Tool, for testing the agent tool-calling loop.
/// 
/// Design: `pub type has Tool` with four required methods.  The a2r generator
/// (plan 373 G2 fix) emits a real `impl Tool for EchoTool` (not a synthetic
/// `ToolTrait`), and `~Result` methods become `async fn`.  No hand-edits needed
/// after transpile.
#[derive(Clone, Debug, PartialEq)]
pub struct EchoTool {}

#[async_trait::async_trait]
impl crate::tool::Tool for EchoTool {
    fn name(&self) -> String {
        return "echo".to_string();
    }
    fn description(&self) -> String {
        return "Echo the input text back.  Useful for testing the tool-calling plumbing.".to_string();
    }
    fn parameters(&self) -> JsonValue {
        return a2r_std::json::parse("{\"type\":\"object\",\"properties\":{\"text\":{\"type\":\"string\"}},\"required\":[\"text\"]}");
    }
    async fn execute(&self, args: JsonValue) -> Result<String, ToolError> {
        let v = &args["text"];
        if v.is_null() || v.as_str().unwrap_or("").is_empty() {
            return Err(ToolError::Args("missing 'text' argument".to_string()));
        }
        let text = v.as_str().unwrap_or("");
        return Ok(format!("ECHO: {}", text));
        return Ok(format!("ECHO: {}", text));
    }
}
