// Auto-generated by a2r transpiler

use crate::auto_ai_client::{ClientError};
/// Error types for the agent layer.
/// 
/// [AgentError] is the top-level error returned by [agent.Agent] and
/// [workflow]. It wraps the Layer-2 client error, tool-execution errors, and
/// configuration/parse errors.
/// 
/// Auto port of crates/auto-ai-agent/src/error.rs (auto-ai v0.4.0).
/// Errors raised while executing a tool.
/// The tool's arguments were missing/invalid.
/// The tool ran but failed (e.g. IO error, non-zero exit).
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ToolError {
    Args(String),
    Exec(String),
}


impl ToolError {
    pub fn message(&self) -> String {
        match self {
            ToolError::Args(msg) => return format!("invalid tool arguments: {}", msg),
            ToolError::Exec(msg) => return format!("tool execution failed: {}", msg),
        };
    }
}
impl std::fmt::Display for ToolError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}
impl std::error::Error for ToolError {}


/// Human-readable message (mirrors Rust's Display impl).
/// The unified error type for the agent layer.
/// Propagated from the Layer-2 LLM client.
/// Propagated from a tool invocation.
/// A requested tool was not registered.
/// The ReAct loop exceeded its turn budget without finishing.
/// The loop detected a tool being called identically in a tight cycle.
/// A Role or Workflow configuration was malformed.
#[derive(Debug)]
pub enum AgentError {
    Client(ClientError),
    Tool(ToolError),
    ToolNotFound(String),
    MaxTurnsExceeded(u32),
    LoopDetected(String),
    Config(String),
}

impl From<ClientError> for AgentError {
    fn from(e: ClientError) -> Self {
        AgentError::Client(e)
    }
}

impl From<ToolError> for AgentError {
    fn from(e: ToolError) -> Self {
        AgentError::Tool(e)
    }
}


impl AgentError {
    pub fn message(&self) -> String {
        match self {
            AgentError::Client(e) => return format!("client error: {}", e),
            AgentError::Tool(e) => return format!("tool error: {}", e.message()),
            AgentError::ToolNotFound(name) => return format!("tool not found: {}", name),
            AgentError::MaxTurnsExceeded(n) => return format!("max turns ({}) exceeded without completion", n),
            AgentError::LoopDetected(name) => return format!("loop detected: tool '{}' called with identical args repeatedly", name),
            AgentError::Config(msg) => return format!("config error: {}", msg),
        };
    }
}
impl std::fmt::Display for AgentError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}
impl std::error::Error for AgentError {}
