// Auto-generated by a2r transpiler

/// Flow Specification — declarative pipeline definitions.
/// 
/// A flow is an ordered list of steps that the PipelineEngine executes. The
/// orchestrator is pure Rust state-machine code — zero LLM tokens are spent
/// deciding what to do next.
/// 
/// (Plan 008 Phase 2 — moved from musk relay/flow.rs. The type definitions are
/// generic; app-specific built-in flow instances stay in the app.)
/// 
/// Auto port of crates/auto-ai-agent/src/orchestration/flow.rs (auto-ai v0.4.0).
/// 
/// VARIANT NOTE: the Rust ExitRouting.Loop and GateDecision.Reject are
/// struct-style variants; Auto models them as tuple variants (plan 013 gotcha
/// B3). Field order:
/// - ExitRouting.Loop(target_step_id, max_iterations)
/// - GateDecision.Reject(feedback)
/// Gate type controlling whether a step needs human approval.
/// Proceed automatically.
/// Pause for human approval before executing.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum GateType {
    Auto = 0,
    Human = 1,
}

impl std::fmt::Display for GateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            GateType::Auto => write!(f, "Auto"),
            GateType::Human => write!(f, "Human"),
        }
    }
}
impl GateType {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Auto" | "auto" => GateType::Auto,
            "Human" | "human" => GateType::Human,
            _ => GateType::Auto
        }
    }
}

impl GateType {
    pub fn default() -> GateType {
        return GateType::Auto;
    }
}

/// The default gate is Auto.
/// Routing logic after a step completes.
/// 
/// Tuple variant Loop(target_step_id, max_iterations) — Rust used a struct
/// variant { target_step_id, max_iterations } (plan 013 gotcha B3).
/// Go to the next step in sequence.
/// Loop back to a target step (e.g., coder->tester iteration). Fields:
/// (target_step_id, max_iterations before breaking to next or Paused).
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ExitRouting {
    Next,
    Loop(String, u32),
}


impl ExitRouting {
    pub fn default() -> ExitRouting {
        return ExitRouting::Next;
    }
}

/// The default exit is Next.
/// Decision a human makes at a gate. (The pipeline re-exports this as
/// FlowGateDecision.)
/// 
/// Tuple variant Reject(feedback) — Rust used { feedback } (plan 013 gotcha B3).
/// Approve — continue to next step.
/// Reject — redraft the same step with feedback.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum GateDecision {
    Approve,
    Reject(String),
}


/// A single step in a flow.
#[derive(Clone, Debug, PartialEq)]
pub struct FlowStep {
    pub id: String,
    pub role_id: String,
    pub gate: GateType,
    pub max_turns: Option<u32>,
    pub exit: ExitRouting,
    pub token_budget: Option<u32>,
}

impl FlowStep {
    pub fn new(id: &str, role_id: &str) -> FlowStep {
        return FlowStep { id: id.to_string(), role_id: role_id.to_string(), gate: GateType::Auto, max_turns: None, exit: ExitRouting::Next, token_budget: None };
    }
    pub fn with_gate(&mut self, mut gate: GateType) -> FlowStep {
        self.gate = gate;
        return self.clone();
    }
    pub fn with_exit(&mut self, mut exit: ExitRouting) -> FlowStep {
        self.exit = exit;
        return self.clone();
    }
    pub fn with_budget(&mut self, budget: u32) -> FlowStep {
        self.token_budget = Some(budget);
        return self.clone();
    }
}

/// Which role/profession executes this step (e.g. "coder", "reviewer").
/// Gate type controlling whether a step needs human approval.
/// Max LLM turns before forced handoff (overrides role default).
/// How to route after this step completes.
/// Optional per-step token budget (overrides role default).
/// Builder: set the gate type.
/// Builder: set the exit routing.
/// Builder: set a per-step token budget.
/// A flow is an ordered list of steps with routing logic.
#[derive(Clone, Debug, PartialEq)]
pub struct FlowSpec {
    pub id: String,
    pub steps: Vec<FlowStep>,
}

impl FlowSpec {
    pub fn new(id: &str) -> FlowSpec {
        return FlowSpec { id: id.to_string(), steps: vec![] };
    }
    pub fn add_step(&mut self, step: FlowStep) -> FlowSpec {
        self.steps.push(step.clone());
        return self.clone();
    }
    pub fn get_step(&self, step_id: &str) -> Option<FlowStep> {
        for s in self.steps.clone() {
            if s.id == step_id {
                return Some(s);
            }
        }
        return None;
    }
    pub fn get_step_index(&self, step_id: &str) -> Option<u32> {
        let mut i: u32 = 0 as u32;
        for s in self.steps.clone() {
            if s.id == step_id {
                return Some(i as u32);
            }
            i = i + 1;
        }
        return None;
    }
}
