// Auto-generated by a2r transpiler

/// Handoff Document — the token-efficiency mechanism for multi-agent pipelines.
/// 
/// When an agent finishes its step, its work is compressed into a structured
/// HandoffDocument — NOT raw chat history — which the next agent consumes.
/// This keeps context bounded as the pipeline grows.
/// 
/// (Plan 008 Phase 1 — moved from musk relay/handoff.rs, generic version:
/// dropped forge-specific fields: spec_updates, generated_report,
/// arch_change_flag, checkpoint_id, run_id.)
/// 
/// Auto port of crates/auto-ai-agent/src/orchestration/handoff.rs (auto-ai v0.4.0).
/// A decision made during a pipeline step.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Decision {
    pub title: String,
    pub status: String,
    pub rationale: String,
}

/// An open question for the next agent or user.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Question {
    pub text: String,
    pub assigned_to: Option<String>,
}

/// A file or artifact produced by a step.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct WorkProduct {
    pub path: String,
    pub description: String,
    pub lines: Option<u32>,
}

/// Pointers to help the next agent.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct ContextPointers {
    pub files_to_read: Vec<String>,
    pub files_to_test: Vec<String>,
    pub warnings: Vec<String>,
}

impl ContextPointers {
    pub fn default() -> ContextPointers {
        return ContextPointers { files_to_read: vec![], files_to_test: vec![], warnings: vec![] };
    }
}

/// Files the previous agent wrote/edited that should be tested.
/// Token usage for a step.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct TokenUsage {
    pub step_tokens: u32,
    pub cumulative: u32,
    pub budget_remaining: u32,
}

impl TokenUsage {
    pub fn default() -> TokenUsage {
        return TokenUsage { step_tokens: 0, cumulative: 0, budget_remaining: 0 };
    }
}

/// A structured handoff between agents.
/// 
/// RESERVED-WORD NOTE: the Rust field `to` is renamed `target` here because
/// `to` is a reserved keyword in Auto (range syntax). This is a faithful
/// behavioral port; the rename is the only API divergence (plan 013 gotcha,
/// same workaround as TierRouting.routes -> entries).
#[derive(Clone, Debug, PartialEq)]
pub struct HandoffDocument {
    pub from: String,
    pub target: String,
    pub summary: String,
    pub decisions: Vec<Decision>,
    pub open_questions: Vec<Question>,
    pub work_product: Vec<WorkProduct>,
    pub context_for_next: ContextPointers,
    pub token_usage: TokenUsage,
}

impl HandoffDocument {
    pub fn new(from: &str, target: &str) -> HandoffDocument {
        return HandoffDocument { from: from.to_string(), target: target.to_string(), summary: "".to_string(), decisions: vec![], open_questions: vec![], work_product: vec![], context_for_next: ContextPointers::default(), token_usage: TokenUsage::default() };
    }
    pub fn render(&self) -> String {
        let mut lines: Vec<String> = vec![];





        let header: String = format!("# Handoff: {} to {}", self.from, self.target);
        lines.push(header);
        lines.push("".to_string());

        lines.push("## Summary".to_string());
        lines.push(self.summary.clone());
        lines.push("".to_string());

        if self.decisions.is_empty() == false {
            lines.push("## Decisions Made".to_string());
            for d in self.decisions.clone() {
                let line: String = format!("- **{}**: {}", d.status, d.title);
                lines.push(line);
                if d.rationale.is_empty() == false {
                    let rat: String = format!("  - Rationale: {}", d.rationale);
                    lines.push(rat);
                }
            }
            lines.push("".to_string());
        }

        if self.open_questions.is_empty() == false {
            lines.push("## Open Questions".to_string());
            for q in self.open_questions.clone() {
                lines.push(format!("- {}", q.text));
            }
            lines.push("".to_string());
        }

        if self.work_product.is_empty() == false {
            lines.push("## Work Product".to_string());
            for wp in self.work_product.clone() {
                let size = format_size(wp.lines);
                let line: String = format!("- `{}`{}{}", wp.path, size, wp.description);
                lines.push(line);
            }
            lines.push("".to_string());
        }

        let ctx: ContextPointers = self.context_for_next.clone();
        if ctx_has_content(ctx.clone()) {
            lines.push("## Context for Next Agent".to_string());
            if ctx.files_to_read.is_empty() == false {
                lines.push("\n### Files to Read".to_string());
                for f in ctx.files_to_read {
                    lines.push(format!("- {}", f));
                }
            }            if ctx.files_to_test.is_empty() == false {
                lines.push("\n### Files to Test".to_string());
                for f in ctx.files_to_test {
                    lines.push(format!("- `{}`", f));
                }
            }            if ctx.warnings.is_empty() == false {
                lines.push("\n### Warnings".to_string());
                for w in ctx.warnings {
                    lines.push(format!("- ⚠️ {}", w));
                }
            }            lines.push("".to_string());
        }

        let spend: String = format!("## Token Spend
- This step: {} tokens
- Cumulative: {} tokens
", self.token_usage.step_tokens, self.token_usage.cumulative);
        lines.push(spend);

        return lines.join("\n");
    }
}

/// Source role name (e.g. "architect").
/// Target role name (e.g. "coder"). (Rust: `to`.)
/// One-sentence summary of the work done.
/// Key decisions made during this step.
/// Questions left open for the next agent or user.
/// Files or artifacts produced.
/// Pointers to help the next agent get started.
/// Token usage for this step + cumulative.
/// Create a new handoff document between two roles.
/// Render as markdown for the next agent's consumption.
/// " (N lines)" when lines is Some(n), else "".
fn format_size(lines: Option<u32>) -> String {
    match lines {
        Some(n) => return format!(" ({} lines)", n),
        None => return "".to_string(),
    };
}

/// True when any of the context pointer lists is non-empty.
fn ctx_has_content(ctx: ContextPointers) -> bool {
    if ctx.files_to_read.is_empty() == false {
        return true;
    }
    if ctx.files_to_test.is_empty() == false {
        return true;
    }
    if ctx.warnings.is_empty() == false {
        return true;
    }
    return false;
}
