// Auto-generated by a2r transpiler

use crate::wire::{Message};
/// Conversation memory for an [agent.Agent].
/// 
/// A thin ring buffer over [wire.Message] that keeps the system message(s)
/// plus the most recent turns, trimming older history once the Role's
/// `memory_limit` is exceeded.
/// 
/// Auto port of crates/auto-ai-agent/src/memory.rs (auto-ai v0.4.0).
/// Bounded conversation history.
/// 
/// "Turns" are counted as user+assistant message pairs (a tool round-trip is
/// two messages but counts as one turn). [Memory.trim] enforces the limit,
/// always preserving leading system messages.
#[derive(Clone, Debug)]
pub struct Memory {
    pub messages: Vec<Message>,
    pub limit: Option<u32>,
}

impl Memory {
    pub fn new(limit: Option<u32>) -> Memory {
        return Memory { messages: vec![], limit: limit };
    }
    pub fn add(&mut self, role: &str, content: &str) {



        if role == "assistant" {
            self.add_message(Message::assistant(content))
        } else {
            if role == "system" {
                self.add_message(Message::system(content))
            } else {
                self.add_message(Message::user(content))
            }
        }

    }
    pub fn add_message(&mut self, msg: Message) {
        self.messages.push(msg.clone());
        self.trim();
    }
    pub fn extend_pairs(&mut self, pairs: Vec<(String, String)>) {
        for pair in pairs {
            
            self.add(pair.0.as_str(), pair.1.as_str());
        }
    }
    pub fn messages(&self) -> Vec<Message> {
        return self.messages.clone();
    }
    pub fn to_messages(&self) -> Vec<Message> {
        return self.messages.clone();
    }
    pub fn len(&self) -> u32 {
        return ((self.messages.len() as i32) as u32);
    }
    pub fn is_empty(&self) -> bool {
        return (self.messages.len() as i32) == 0;
    }
    pub fn non_system_count(&self) -> u32 {
        let mut count: u32 = 0 as u32;
        for m in self.messages.clone() {
            if m.role.to_string() != "system" {
                count = count + 1
            }
        }
        return count;
    }
    pub fn trim(&mut self) {

        if self.limit.is_none() {
            return;
        }



        let mut limit: u32 = 0 as u32;
        match self.limit.clone() {
            Some(n) => limit = n,
            None => {},
        };
        if limit == 0 {
            

            let mut kept: Vec<Message> = vec![];
            for m in self.messages.clone() {
                if m.role.to_string() == "system" {
                    kept.push(m.clone());
                }
            }
            self.messages = kept;
            return;
        }

        let max_non_system: u32 = limit * 2;
        while self.non_system_count() > max_non_system {
            
            let start = self.first_non_system_index();
            if start < 0 {
                break;
            }
            let s = start.clone();
            


            let mut end: i32 = s + 1;
            if self.messages[(s) as usize].clone().role.to_string() == "assistant" {
                while end < ((self.messages.len() as i32) as i32) && self.messages[(end) as usize].clone().role.to_string() == "user" {
                    end = end + 1;
                }
            }
            
            self.messages = self.remove_range(s, end);
        }
    }
    pub fn first_non_system_index(&self) -> i32 {
        let mut i: i32 = 0;
        for m in self.messages.clone() {
            if m.role.to_string() != "system" {
                return i;
            }
            i = i + 1;
        }
        return -1;
    }
    pub fn remove_range(&self, from: i32, up_to: i32) -> Vec<Message> {
        let mut out: Vec<Message> = vec![];
        let mut i: i32 = 0;
        for m in self.messages.clone() {
            

            if i < from {
                out.push(m.clone())
            } else {
                if i >= up_to {
                    out.push(m.clone());
                }            }

            i = i + 1;
        }
        return out;
    }
}
