// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use std::path::PathBuf;
use std::fs;
use std::fs::DirEntry;
use std::sync::Arc;
use crate::ai_config::{ModelTier};
use crate::role_def::{Role};
use crate::error::{AgentError};
use crate::builtin_roles::{builtin_names, load_builtin};
use crate::config::{RoleConfig, parse_at_role, serialize_at_role, load_role, config_role_new};
/// Agent Role registry — user-configurable, persistable roles that generalize
/// the compiled-in [Role] library.
/// 
/// A Role is the same idea as a built-in Role (soul prompt + tier + tools +
/// temperature + …) but **editable at runtime**: roles live as role { … }
/// blocks in ~/.config/autoos/roles/<name>.at, with an optional sidecar Soul
/// markdown file (<name>.soul.md). Built-in professions act as read-only
/// defaults and as inherit: bases for user roles.
/// 
/// (Plan 004 — Agent Roles.)
/// 
/// Auto port of crates/auto-ai-agent/src/roles.rs (auto-ai v0.4.0).
/// 
/// a2r-FIRST NOTE: like validate.at, this bridges dirs::home_dir() and the
/// std::fs / std::path crates. The pure AutoVM cannot resolve the bridged
/// types or list a filesystem directory, so the runtime path runs under cargo
/// (a2r→Rust). The public API (RoleRegistry.load / resolve_role / list / get /
/// save / delete + RoleSummary / RoleDetail) is stable; when Auto gains native
/// fs support, drop the use.rust lines and swap the bridged calls.
/// Directory holding user roles: ~/.config/autoos/roles/. None when the home
/// directory can't be determined.
fn roles_dir() -> Option<PathBuf> {
    match dirs::home_dir() {
        Some(h) => return Some(h.join(".config/autoos/roles")),
        None => return None,
    }
}

/// A role's .at file path: <roles_dir>/<name>.at. None when home is
/// unknown.
fn role_at_path(name: &str) -> Option<PathBuf> {
    match roles_dir() {
        Some(d) => return Some(d.join(format!("{}.at", name))),
        None => return None,
    }
}

/// A role's sidecar Soul markdown path: <roles_dir>/<name>.soul.md.
fn role_soul_path(name: &str) -> Option<PathBuf> {
    match roles_dir() {
        Some(d) => return Some(d.join(format!("{}.soul.md", name))),
        None => return None,
    }
}

/// A flat summary of a role, for listing. Built-in roles are flagged so the UI
/// can render them read-only.
#[derive(Clone, Debug, PartialEq)]
pub struct RoleSummary {
    pub name: String,
    pub description: String,
    pub tier: ModelTier,
    pub allowed_tiers: Vec<ModelTier>,
    pub skills: Vec<String>,
    pub token_budget: Option<u32>,
    pub is_builtin: bool,
}

impl RoleSummary {
    pub fn empty() -> RoleSummary {
        return RoleSummary { name: "".to_string(), description: "".to_string(), tier: ModelTier::Mid, allowed_tiers: vec![], skills: vec![], token_budget: None, is_builtin: false };
    }
}

/// Full detail of a single role, including the Soul markdown body (loaded from
/// the sidecar file when present, else the inline system_prompt).
#[derive(Clone, Debug, PartialEq)]
pub struct RoleDetail {
    pub summary: RoleSummary,
    pub soul: String,
    pub soul_from_file: bool,
    pub config: RoleConfig,
}

/// The Soul / system-prompt markdown in full.
/// Whether the Soul came from a sidecar .soul.md (vs inline).
/// The raw parsed config (for the editor to bind to form fields).
/// Read a built-in [Role]'s trait methods back into a config struct, so the
/// UI/API can present built-ins uniformly alongside user roles.
/// 
/// (Ports the private profession_to_config helper from roles.rs.)
fn profession_to_config(prof: Box<dyn Role>) -> RoleConfig {
    let t = prof.allowed_tools();
    let at = prof.allowed_tiers();
    let s = prof.skills();
    let mut tools: Option<Vec<String>> = None;
    if t.is_empty() == false {
        tools = Some(t)
    }
    let mut tiers: Option<Vec<ModelTier>> = None;
    if at.is_empty() == false {
        tiers = Some(at)
    }
    let mut skills: Option<Vec<String>> = None;
    if s.is_empty() == false {
        skills = Some(s)
    }
    return RoleConfig { name: Some(prof.name()), description: None, model: Some(prof.model()), model_tier: Some(prof.model_tier()), temperature: Some(prof.temperature()), max_turns: Some(prof.max_turns()), system_prompt: Some(prof.system_prompt()), system_prompt_append: None, tools: tools, tools_append: None, inherit: None, memory_limit: prof.memory_limit(), allowed_tiers: tiers, skills: skills, token_budget: prof.token_budget(), soul_file: None };
}

/// Registry of roles: built-in professions (read-only) + user .at roles
/// (which may override a same-named built-in). Mirrors ModeRegistry's shape.
/// 
/// NOTE (plan 013 gotcha B5): Auto's VM Map has no iteration API, so a parallel
/// names List<str> is kept alongside roles for ordering/listing. Fields are
/// pub (B12).
#[derive(Clone, Debug, PartialEq)]
pub struct RoleRegistry {
    pub roles: std::collections::HashMap<String, RoleDetail>,
    pub names: Vec<String>,
}

impl RoleRegistry {
    pub fn new() -> RoleRegistry {
        return RoleRegistry { roles: std::collections::HashMap::new(), names: vec![] };
    }
    pub fn load() -> RoleRegistry {
        let mut roles: std::collections::HashMap<String, RoleDetail> = std::collections::HashMap::new();
        let mut names: Vec<String> = vec![];


        for name in builtin_names() {
            load_one_builtin(name.as_str(), &mut roles, &mut names);
        }


        load_user_roles(&mut roles, &mut names);

        return RoleRegistry { roles: roles, names: names };
    }
    pub fn resolve_role(&self, name: &str) -> Option<Arc<Box<dyn Role>>> {



        if let Some(detail) = self.roles.get(name) {
            if detail.summary.is_builtin == false {
                let src = serialize_at_role(detail.config.clone());
                match load_role(&src) {
                    Ok(_cfg) => {
                        



                        let role = config_role_new(detail.config.clone());
                        return Some(Arc::new(Box::new(role) as Box<dyn Role>));
                    },
                    Err(_e) => {
                        

                    },
                }
            }        }

        match load_builtin(name) {
            Some(b) => return Some(Arc::new(b)),
            None => return None,
        }
    }
    pub fn list(&self) -> Vec<RoleSummary> {
        let mut user_list: Vec<RoleSummary> = vec![];
        let mut builtin_list: Vec<RoleSummary> = vec![];
        for name in &self.names {
            if let Some(d) = self.roles.get(name) {
                if d.summary.is_builtin {
                    builtin_list.push(d.summary.clone());
                } else {
                    user_list.push(d.summary.clone());
                }
            }
        }
        user_list.sort_by_key(|s| s.name.clone());
        builtin_list.sort_by_key(|s| s.name.clone());
        let mut out: Vec<RoleSummary> = vec![];
        for s in user_list {
            out.push(s.clone());
        }
        for s in builtin_list {
            out.push(s.clone());
        }
        return out;
    }
    pub fn get(&self, name: &str) -> Option<RoleDetail> {
        if let Some(d) = self.roles.get(name) {
            return Some(d.clone());
        }
        return None;
    }
    pub fn save(&self, name: &str, cfg: RoleConfig, soul_md: Option<String>) -> Result<(), AgentError> {
        if load_builtin(name).is_some() {
            return Err(AgentError::Config(format!("cannot overwrite built-in role '{}'; choose a different name or use inherit", name)));
        }

        let mut out: RoleConfig = cfg.clone();
        out.name = Some(name.to_string());

        match roles_dir() {
            None => return Err(AgentError::Config("could not determine home directory for roles".to_string())),
            Some(dir) => {
                match fs::create_dir_all(&dir) {
                    Err(e) => return Err(AgentError::Config(format!("failed to create roles dir {}: {}", dir.display(), e))),
                    Ok(_) => {},
                }
                


                match soul_md {
                    Some(md) => {
                        let soul_path = dir.join(format!("{}.soul.md", name));
                        if !a2r_std::fs::write(soul_path.to_str().unwrap(), md.as_str()) {
                            return Err(AgentError::Config(format!("failed to write {}", soul_path.display())));
                        }
                        out.soul_file = Some(format!("{}.soul.md", name));
                    },
                    None => {},
                }
                


                let at_path = dir.join(format!("{}.at", name));
                let src = serialize_at_role(out);
                if a2r_std::fs::write(at_path.to_str().unwrap(), src.as_str()) {
                    return Ok(());
                } else {
                    return Err(AgentError::Config(format!("failed to write {}", at_path.display())));
                }
            },
        }
    }
    pub fn delete(&self, name: &str) -> Result<(), AgentError> {
        if load_builtin(name).is_some() {
            return Err(AgentError::Config(format!("cannot delete built-in role '{}'", name)));
        }
        match role_at_path(name) {
            None => return Err(AgentError::Config("could not determine home directory".to_string())),
            Some(at_path) => {
                let existed = at_path.exists();
                if existed {
                    match fs::remove_file(&at_path) {
                        Err(e) => return Err(AgentError::Config(format!("failed to delete {}: {}", at_path.display(), e))),
                        Ok(_) => {},
                    }
                }
                

                match role_soul_path(name) {
                    Some(p) => {
                        let _ = fs::remove_file(p);
                    },
                    None => {},
                }
                if existed == false {
                    return Err(AgentError::Config(format!("role '{}' not found", name)));
                }
                return Ok(());
            },
        }
    }
}

/// name -> detail. Built-ins are flagged is_builtin = true in the detail.
/// Parallel key list (kept in sync with roles) so we can iterate.
/// Empty registry (Default).
/// Load all roles: built-in professions first, then user .at files (which
/// override same-named built-ins). Single-role parse failures are warned +
/// skipped — never fatal (mirrors ModeRegistry).
/// Resolve a role by name into a live Role (for agent building).
/// User-defined roles (.at files) take precedence over compiled-in
/// built-ins with the same name, so ~/.config/autoos/roles/assistant.at
/// can override the built-in assistant role's model_tier and other fields.
/// List all role summaries (built-in + user), sorted: user roles first
/// (alphabetical), then built-ins (alphabetical). Mirrors Rust's
/// sort_by with b.is_builtin.cmp(&a.is_builtin).then(name.cmp).
/// Full detail for one role.
/// Save (create or overwrite) a user role. Writes the .at and, when
/// soul_md is Some, the sidecar .soul.md. Built-in roles cannot be
/// overwritten — returns an error.
/// Delete a user role (.at + sidecar .soul.md). Built-in roles cannot be
/// deleted — returns an error.
/// Load one built-in profession into the registry (step 1 of load()).
/// Unknown names are silently skipped.
fn load_one_builtin(name: &str, roles: &mut std::collections::HashMap<String, RoleDetail>, names: &mut Vec<String>) {
    match load_builtin(name) {
        Some(prof) => {
            let pname = prof.name();
            let ptier = prof.model_tier();
            let patiers = prof.allowed_tiers();
            let pskills = prof.skills();
            let pbudget = prof.token_budget();
            let psoul = prof.system_prompt();
            let cfg = profession_to_config(prof);
            let summary = RoleSummary { name: pname, description: "".to_string(), tier: ptier, allowed_tiers: patiers, skills: pskills, token_budget: pbudget, is_builtin: true };
            let detail = RoleDetail { summary: summary, soul: psoul, soul_from_file: false, config: cfg };
            roles.insert(name.to_string(), detail);
            names.push(name.to_string());
        },
        None => {},
    }
}

/// Load all user .at roles from the roles directory (step 2 of load()).
/// Missing/unreadable directory → no user roles (not fatal).
fn load_user_roles(roles: &mut std::collections::HashMap<String, RoleDetail>, names: &mut Vec<String>) {
    match roles_dir() {
        Some(dir) => scan_roles_dir(dir.clone(), &mut *roles, &mut *names),
        None => {},
    }
}

/// Iterate one roles directory, loading each *.at entry.
fn scan_roles_dir(dir: PathBuf, roles: &mut std::collections::HashMap<String, RoleDetail>, names: &mut Vec<String>) {
    match fs::read_dir(dir) {
        Ok(entries) => {
            for entry in entries {
                match entry {
                    Ok(e) => handle_dir_entry(e, &mut *roles, &mut *names),
                    Err(_) => {},
                }
            }
        },
        Err(_e) => {
            

        },
    }
}

/// Handle one read_dir result: skip errors, load .at files.
fn handle_dir_entry(entry: DirEntry, roles: &mut std::collections::HashMap<String, RoleDetail>, names: &mut Vec<String>) {
    let path = entry.path();
    if is_at_file(path.clone()) {
        load_user_at_file(path.clone(), &mut *roles, &mut *names);
    }
}

/// True when path's extension is exactly "at".
fn is_at_file(path: PathBuf) -> bool {
    let ext = path.extension();
    match ext {
        Some(e) => return e == "at",
        None => return false,
    }
}

/// Read + parse one user .at role file, inserting it into roles/names
/// (overriding any same-named built-in). Parse/read failures are warned +
/// skipped — never fatal. (Mirrors the inline body of Rust's load() loop.)
fn load_user_at_file(path: PathBuf, roles: &mut std::collections::HashMap<String, RoleDetail>, names: &mut Vec<String>) {
    let content = a2r_std::fs::read_to_string(path.to_str().unwrap());
    if content.is_empty() {
        return;
    }
    match parse_at_role(&content) {
        Err(_e) => {


        },
        Ok(cfg) => {


            let mut name: String = "".to_string();
            match cfg.name.clone() {
                Some(n) => name = n,
                None => {
                    match path.file_stem() {
                        Some(stem) => {
                            match stem.to_str() {
                                Some(s) => name = s.to_string(),
                                None => name = "unnamed".to_string(),
                            }
                        },
                        None => name = "unnamed".to_string(),
                    }
                },
            }



            let soul = resolve_soul(cfg.clone(), path.clone());
            let summary = RoleSummary { name: name.to_string(), description: cfg.description.clone().unwrap_or("".to_string()).to_string(), tier: cfg.model_tier.unwrap_or(ModelTier::Mid), allowed_tiers: cfg.allowed_tiers.clone().unwrap_or_default(), skills: cfg.skills.clone().unwrap_or_default(), token_budget: cfg.token_budget, is_builtin: false };
            let detail = RoleDetail { summary: summary, soul: soul.markdown.to_string(), soul_from_file: soul.from_file, config: cfg };
            if roles.contains_key(&name) == false {
                names.push(name.clone());
            }
            roles.insert(name.to_string(), detail);
        },
    }
}

/// The result of resolving a role's Soul markdown.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct SoulResolve {
    pub markdown: String,
    pub from_file: bool,
}

/// Resolve a role's Soul markdown: sidecar file first (if soul_file set and
/// exists), else the inline system_prompt, else empty. Returns
/// (markdown, came_from_file).
fn resolve_soul(cfg: RoleConfig, at_path: PathBuf) -> SoulResolve {
    match cfg.soul_file {
        Some(rel) => {
            

            match at_path.parent() {
                Some(d) => {
                    let sidecar = d.join(rel);
                    let md = a2r_std::fs::read_to_string(sidecar.to_str().unwrap());
                    if md.is_empty() {
                        return SoulResolve { markdown: cfg.system_prompt.unwrap_or("".to_string()).to_string(), from_file: false };
                    }
                    return SoulResolve { markdown: md, from_file: true };
                },
                None => {
                    let sidecar = PathBuf::from(rel);
                    let md = a2r_std::fs::read_to_string(sidecar.to_str().unwrap());
                    if md.is_empty() {
                        return SoulResolve { markdown: cfg.system_prompt.unwrap_or("".to_string()).to_string(), from_file: false };
                    }
                    return SoulResolve { markdown: md, from_file: true };
                },
            }
        },
        None => return SoulResolve { markdown: cfg.system_prompt.unwrap_or("".to_string()).to_string(), from_file: false },
    }
}
