// Auto-generated by a2r transpiler

use auto_atom::*;
use auto_val::*;
use crate::error::{AgentError};
use crate::role_def::{Role};
use crate::builtin_roles::{load_builtin};
use crate::ai_config::{ModelTier};
/// Parsing + inherit/merge for `.at` Role config files.
/// 
/// Auto port of config/role_config.rs (auto-ai v0.4.0).
/// 
/// BRIDGE NOTE (plan 013): like loader.at, this bridges auto_atom/auto_val.
/// a2r-first — AutoVM can't resolve the bridged types; runs under cargo.
/// The parsed representation of a `role { … }` block. Every field is optional
/// so an `inherit`-based config only overrides what it sets.
#[derive(Clone, Debug, PartialEq)]
pub struct RoleConfig {
    pub name: Option<String>,
    pub description: Option<String>,
    pub model: Option<String>,
    pub model_tier: Option<ModelTier>,
    pub temperature: Option<f64>,
    pub max_turns: Option<u32>,
    pub system_prompt: Option<String>,
    pub system_prompt_append: Option<String>,
    pub tools: Option<Vec<String>>,
    pub tools_append: Option<Vec<String>>,
    pub inherit: Option<String>,
    pub memory_limit: Option<u32>,
    pub allowed_tiers: Option<Vec<ModelTier>>,
    pub skills: Option<Vec<String>>,
    pub token_budget: Option<u32>,
    pub soul_file: Option<String>,
}

impl RoleConfig {
    pub fn empty() -> RoleConfig {
        return RoleConfig { name: None, description: None, model: None, model_tier: None, temperature: None, max_turns: None, system_prompt: None, system_prompt_append: None, tools: None, tools_append: None, inherit: None, memory_limit: None, allowed_tiers: None, skills: None, token_budget: None, soul_file: None };
    }
    pub fn merge_over(&self, base: RoleConfig) -> RoleConfig {
        let mut r: RoleConfig = base.clone();

        match self.name.clone() {
            Some(v) => r.name = Some(v),
            None => {},
        }
        match self.description.clone() {
            Some(v) => r.description = Some(v),
            None => {},
        }
        match self.model.clone() {
            Some(v) => r.model = Some(v),
            None => {},
        }
        match self.model_tier.clone() {
            Some(v) => r.model_tier = Some(v),
            None => {},
        }
        match self.temperature.clone() {
            Some(v) => r.temperature = Some(v),
            None => {},
        }
        match self.max_turns.clone() {
            Some(v) => r.max_turns = Some(v),
            None => {},
        }
        match self.system_prompt.clone() {
            Some(v) => r.system_prompt = Some(v),
            None => {},
        }
        match self.memory_limit.clone() {
            Some(v) => r.memory_limit = Some(v),
            None => {},
        }
        match self.inherit.clone() {
            Some(v) => r.inherit = Some(v),
            None => {},
        }
        match self.allowed_tiers.clone() {
            Some(v) => r.allowed_tiers = Some(v),
            None => {},
        }
        match self.skills.clone() {
            Some(v) => r.skills = Some(v),
            None => {},
        }
        match self.token_budget.clone() {
            Some(v) => r.token_budget = Some(v),
            None => {},
        }
        match self.soul_file.clone() {
            Some(v) => r.soul_file = Some(v),
            None => {},
        }

        match base.system_prompt_append {
            Some(extra) => {
                match self.system_prompt_append.clone() {
                    Some(mine) => r.system_prompt_append = Some(format!("{}
{}", extra, mine)),
                    None => r.system_prompt_append = Some(extra),
                }
            },
            None => r.system_prompt_append = self.system_prompt_append,
        }

        match self.tools.clone() {
            Some(replace) => r.tools = Some(replace),
            None => {},
        }
        match self.tools_append.clone() {
            Some(extra) => {
                let mut combined: Option<Vec<String>> = r.tools.unwrap_or_default();
                for t in extra {
                    combined.push(t.clone());
                }
                r.tools = Some(combined);
            },
            None => {},
        }
        return r;
    }
}

/// Merge self over base, applying design-doc §4.4 rules:
/// - scalar fields override when Some;
/// - system_prompt_append accumulates;
/// - tools replaces; tools_append extends.
/// A Role whose behavior is driven by a parsed RoleConfig. When a field is
/// None, it falls back to the inherited base Role (if any).
trait RoleTrait {
}

#[allow(dead_code)]
pub struct ConfigRole {
    pub cfg: RoleConfig,
    pub base: Option<Box<dyn Role>>,
}

impl RoleTrait for ConfigRole {
}

impl ConfigRole {
    pub fn name(&self) -> String {
        match self.cfg.name {
            Some(n) => return n,
            None => return self.base_name(),
        }
    }
    pub fn system_prompt(&self) -> String {
        let mut prompt: Option<String> = self.cfg.system_prompt.unwrap_or(self.base_prompt());
        match self.cfg.system_prompt_append {
            Some(extra) => return format!("{}
{}", prompt, extra),
            None => return prompt,
        }
    }
    pub fn model_tier(&self) -> ModelTier {
        match self.cfg.model_tier {
            Some(t) => return t,
            None => return self.base_tier(),
        }
    }
    pub fn model(&self) -> String {
        return self.cfg.model.unwrap_or(self.base_model_str());
    }
    pub fn temperature(&self) -> f64 {
        match self.cfg.temperature {
            Some(t) => return t,
            None => return self.base_temp(),
        }
    }
    pub fn max_turns(&self) -> u32 {
        match self.cfg.max_turns {
            Some(n) => return n,
            None => return self.base_turns(),
        }
    }
    pub fn allowed_tools(&self) -> Vec<String> {
        return self.cfg.tools.unwrap_or_default();
    }
    pub fn memory_limit(&self) -> Option<u32> {
        match self.cfg.memory_limit {
            Some(n) => return Some(n as u32),
            None => return self.base_mem(),
        }
    }
    pub fn skills(&self) -> Vec<String> {
        return self.cfg.skills.unwrap_or_default();
    }
    pub fn base_name(&self) -> String {
        match self.base.clone() {
            Some(b) => return b.name(),
            None => return "unnamed".to_string(),
        }
    }
    pub fn base_prompt(&self) -> String {
        match self.base.clone() {
            Some(b) => return b.system_prompt(),
            None => return "".to_string(),
        }
    }
    pub fn base_tier(&self) -> ModelTier {
        match self.base.clone() {
            Some(b) => return b.model_tier(),
            None => return ModelTier::Mid,
        }
    }
    pub fn base_model_str(&self) -> String {
        match self.base.clone() {
            Some(b) => return b.model(),
            None => return "".to_string(),
        }
    }
    pub fn base_temp(&self) -> f64 {
        match self.base.clone() {
            Some(b) => return b.temperature(),
            None => return 0.3,
        }
    }
    pub fn base_turns(&self) -> u32 {
        match self.base.clone() {
            Some(b) => return b.max_turns(),
            None => return 10,
        }
    }
    pub fn base_mem(&self) -> Option<u32> {
        match self.base.clone() {
            Some(b) => return b.memory_limit(),
            None => return Some(20),
        }
    }
}

pub fn config_role_new(cfg: RoleConfig) -> ConfigRole {
    return ConfigRole { cfg: cfg, base: None };
}

pub fn config_role_with_base(cfg: RoleConfig, base: Box<dyn Role>) -> ConfigRole {
    return ConfigRole { cfg: cfg, base: Some(base) };
}

pub fn parse_at_role(content: &str) -> Result<RoleConfig, AgentError> {
    match auto_atom::AtomParser::parse(content) {
        Ok(atom) => {
            match atom {
                Atom::Node(node) => {
                    let mut cfg = RoleConfig::empty();
                    cfg.name = opt_str(*(*node).clone(), "name");
                    cfg.description = opt_str(*(*node).clone(), "description");
                    cfg.model = opt_str(*(*node).clone(), "model");
                    let tier_str = opt_str(*(*node).clone(), "model_tier");
                    match tier_str {
                        Some(s) => {
                            match parse_tier_field(s.as_str()) {
                                Some(t) => cfg.model_tier = Some(t),
                                None => {},
                            }
                        },
                        None => {},
                    }
                    cfg.temperature = opt_float(*(*node).clone(), "temperature");
                    cfg.max_turns = opt_uint(*(*node).clone(), "max_turns");
                    cfg.memory_limit = opt_uint(*(*node).clone(), "memory_limit");
                    cfg.system_prompt = opt_str(*(*node).clone(), "system_prompt");
                    cfg.system_prompt_append = opt_str(*(*node).clone(), "system_prompt_append");
                    cfg.tools = opt_str_list(*(*node).clone(), "tools");
                    cfg.tools_append = opt_str_list(*(*node).clone(), "tools_append");
                    cfg.inherit = opt_str(*(*node).clone(), "inherit");
                    cfg.soul_file = opt_str(*(*node).clone(), "soul_file");
                    return Ok(cfg);
                },
                _ => return Err(AgentError::Config("expected a 'role' node")),
            }
        },
        Err(e) => return Err(AgentError::Config(format!("failed to parse role .at: {}", e))),
    }
}

pub fn load_role(content: &str) -> Result<RoleConfig, AgentError> {
    match parse_at_role(content) {
        Ok(cfg) => {
            let mut result = cfg;
            

            match cfg.inherit {
                Some(name) => {
                    match builtin_roles::load_builtin(name) {
                        Some(base_role) => {
                            




                        },
                        None => return Err(AgentError::Config(format!("inherit: unknown role '{}'", name))),
                    }
                },
                None => {},
            }
            return Ok(result);
        },
        Err(e) => return Err(e),
    }
}

pub fn parse_tier_field(s: &str) -> Option<ModelTier> {
    return ModelTier::parse_name(s);
}

pub fn serialize_at_role(cfg: RoleConfig) -> String {
    let mut lines: Vec<String> = vec!["role {".to_string()];
    match cfg.name {
        Some(v) => lines.push(format!("    name : \"{}\"", v)),
        None => {},
    }
    match cfg.model {
        Some(v) => lines.push(format!("    model : \"{}\"", v)),
        None => {},
    }
    match cfg.model_tier {
        Some(t) => lines.push(format!("    model_tier : {}", t.display_name())),
        None => {},
    }
    match cfg.temperature {
        Some(v) => lines.push(format!("    temperature : {}", v)),
        None => {},
    }
    match cfg.max_turns {
        Some(v) => lines.push(format!("    max_turns : {}", v)),
        None => {},
    }
    match cfg.system_prompt {
        Some(v) => lines.push(format!("    system_prompt : \"{}\"", v)),
        None => {},
    }
    match cfg.inherit {
        Some(v) => lines.push(format!("    inherit : \"{}\"", v)),
        None => {},
    }
    lines.push("}".to_string());
    return lines.join("\n");
}

/// Factory: create a ConfigRole from a parsed config.
/// Factory: create a ConfigRole with an inherited base Role.
/// Parse a single `role { … }` block from `.at` source.
/// Load a Role (as ConfigRole) from `.at` source, resolving `inherit` chains.
/// Parse a tier field string → ModelTier. Returns None for unrecognized.
/// Serialize a RoleConfig back to `.at` format.
fn opt_str(node: auto_val::Node, key: &str) -> Option<String> {
    let val = node.get_prop_of(key);
    match val {
        Value::Str(s) => return Some(s.to_string()),
        Value::String(s) => return Some(s.to_string()),
        auto_val::Value.Nil => return None,
        _ => return Some(val.to_astr().to_string()),
    }
}

fn opt_float(node: auto_val::Node, key: &str) -> Option<f64> {
    let val = node.get_prop_of(key);
    match val {
        Value::Float(f) => return Some(f),
        Value::Double(d) => return Some(d),
        Value::Int(i) => return Some(i.to_float()),
        _ => return None,
    }
}

fn opt_uint(node: auto_val::Node, key: &str) -> Option<u32> {
    let val = node.get_prop_of(key);
    match val {
        Value::Uint(u) => return Some(u as u32),
        Value::Int(i) => {
            if i >= 0 {
                return Some(i as u32);
            }
            return None;
        },
        _ => return None,
    }
}

fn opt_str_list(node: auto_val::Node, key: &str) -> Option<Vec<String>> {
    let val = node.get_prop_of(key);
    match val {
        Value::Array(arr) => {
            let mut out: Vec<String> = vec![];
            for el in arr.values {
                match el {
                    Value::Str(s) => out.push(s.to_string()),
                    _ => {},
                }
            }
            return Some(out);
        },
        _ => return None,
    }
}

fn parse_tier(s: &str) -> Option<ModelTier> {
    return ModelTier::parse_name(s);
}
