// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use std::path::PathBuf;
use std::fs;
use std::sync::Arc;
use serde_json;
use serde_json::Value;

use crate::error::{ToolError};
use crate::tool::{Tool};
use crate::wire::{JsonValue};
/// Skill system — a "skill" is a markdown prompt fragment the model loads
/// on demand by calling the SkillTool.
/// 
/// A skill is a prompt fragment (SKILL.md) with two metadata fields
/// (name, description) that the model loads when it decides the skill applies,
/// then follows as best-effort instructions. There is no enforced procedure —
/// the ordering, gates, and checklists all live inside the prompt text.
/// 
/// Discovery: SkillRegistry.scan walks a directory for `*/SKILL.md` files,
/// parses the frontmatter, and stores {name -> Skill}.
/// 
/// Auto port of crates/auto-ai-agent/src/skill.rs (auto-ai v0.4.0).
/// 
/// a2r-FIRST NOTE: this bridges `std::fs` / `std::path` (read_dir,
/// read_to_string, is_file/is_dir, join) and `serde_json::Value`. The pure
/// AutoVM cannot resolve the bridged types or list a filesystem directory, so
/// the runtime path runs under cargo (a2r->Rust). The public API
/// (Skill / SkillRegistry / SkillTool) is stable.
/// 
/// PARSER NOTE: Auto's `is`-pattern matcher must not match a *method call*
/// directly (e.g. `is raw.strip_prefix(...) {...}`): the parser mis-terminates
/// the block and swallows following code. Bind the call result to a local var
/// first, then match the var. All Option-returning string/path calls below
/// follow this rule. (Plan 013 gotcha.)
/// One skill: a name, a trigger description, and the full prompt body.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Skill {
    pub name: String,
    pub description: String,
    pub content: String,
    pub path: PathBuf,
}

/// Skill name (unique in a registry). From frontmatter name:.
/// When to use this skill (third-person). From frontmatter description:.
/// This is the trigger — the model reads it to decide whether to call.
/// The full SKILL.md body (everything after the frontmatter --- block).
/// Path to the source SKILL.md (for diagnostics).
/// Registry of skills keyed by name, built by scanning a directory.
/// 
/// NOTE (plan 013 gotcha B5): Auto's VM Map has no iteration API, so a parallel
/// `names List<str>` is kept alongside `skills` for ordering/listing. Fields
/// are `pub` (B12).
#[derive(Clone, Debug, PartialEq)]
pub struct SkillRegistry {
    pub skills: std::collections::HashMap<String, Skill>,
    pub names: Vec<String>,
}

impl SkillRegistry {
    pub fn new() -> SkillRegistry {
        return SkillRegistry { skills: std::collections::HashMap::new(), names: vec![] };
    }
    pub fn scan(dir: PathBuf) -> SkillRegistry {
        let mut skills: std::collections::HashMap<String, Skill> = std::collections::HashMap::new();
        let mut names: Vec<String> = vec![];
        match fs::read_dir(dir) {
            Ok(entries) => {
                for entry in entries {
                    scan_one_entry(entry.clone(), skills.clone(), names);
                }
            },
            Err(_e) => {
                

            },
        }
        return SkillRegistry { skills: skills, names: names };
    }
    pub fn get(&self, name: &str) -> Option<Skill> {
        if self.skills.contains_key(name) {
            return Some(self.skills.get(name));
        }
        return None;
    }
    pub fn retain(&mut self, whitelist: Vec<String>) {
        let mut kept: std::collections::HashMap<String, Skill> = std::collections::HashMap::new();
        let mut kept_names: Vec<String> = vec![];
        for name in self.names {
            if whitelist.contains(&name) {
                let s = self.skills.get(name);
                kept.insert(name, s);
                kept_names.push(name.clone());
            }
        }
        self.skills = kept;
        self.names = kept_names;
    }
    pub fn names(&self) -> Vec<String> {
        return self.names.clone();
    }
    pub fn descriptions(&self) -> Vec<(String, String)> {
        let mut out: Vec<(String, String)> = vec![];
        for name in self.names {
            let s = self.skills.get(name);
            out.push((s.name, s.description));
        }
        out.sort_by_key(|pair| pair[0].clone());
        return out;
    }
    pub fn len(&self) -> u32 {
        return (self.names.len() as i32);
    }
    pub fn is_empty(&self) -> bool {
        return (self.names.len() as i32) == 0;
    }
}

/// Empty registry (no skills configured).
/// Scan `dir` for `<skill-name>/SKILL.md` files and load them.
/// 
/// Fault-tolerant: a directory whose SKILL.md is missing or fails to parse
/// is skipped (logged at warn), not fatal — one broken skill shouldn't
/// disable the whole registry.
/// Look up a skill by name.
/// Keep only skills whose name is in `whitelist` (in place). Used by the
/// Plan 004 Roles feature: a role's skills whitelist restricts which
/// installed skills are exposed to an agent.
/// All skill names (no order guarantee).
/// (name, description) pairs for all skills — sorted by name. Used to build
/// the `<available_skills>` bootstrap block injected into the system prompt.
/// Number of loaded skills.
/// Handle one read_dir entry: skip non-directories, and for each subdirectory
/// try to load its SKILL.md.
fn scan_one_entry(entry: DirEntry, skills: std::collections::HashMap<String, Skill>, names: Vec<String>) {
    let sub = entry.path();
    let is_dir = sub.is_dir();
    if is_dir == false {
        return;
    }
    let skill_md = sub.join("SKILL.md");
    let is_file = skill_md.is_file();
    if is_file == false {
        return;
    }
    match parse_skill_file(skill_md.clone()) {
        Ok(skill) => {
            if skill.name.is_empty() == false {
                if skills.contains_key(&skill.name) == false {
                    names.push(skill.name);
                }                skills.insert(skill.name, skill);
            }
        },
        Err(_e) => {
            

        },
    }
}

/// Parse a single SKILL.md file into a Skill.
/// 
/// Expects a leading YAML-ish frontmatter block delimited by `---` lines.
/// Only name and description are extracted; everything after the closing
/// `---` is the body. No full YAML parser — these are two string fields.
fn parse_skill_file(path: PathBuf) -> Result<Skill, String> {
    match a2r_std::fs::read_to_string(path.as_str()) {
        Err(e) => return Err(Box::new(format!("read: {}", e))),
        Ok(raw) => {
            let parsed = parse_frontmatter(raw.as_str());
            if parsed.name.is_empty() {
                return Err("frontmatter is missing 'name:'".into());
            }
            return Ok(Skill { name: parsed.name.to_string(), description: parsed.description.to_string(), content: parsed.content.to_string(), path: path });
        },
    }
}

/// The parsed frontmatter result.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Frontmatter {
    pub name: String,
    pub description: String,
    pub content: String,
}

/// Split a SKILL.md into (name, description, body).
/// 
/// - If a leading `---\n...\n---` block exists, parse name:/description: from
/// it; the body is everything after the closing `---`.
/// - If no frontmatter, name is empty (caller falls back to the dir name),
/// description is empty, and the whole file is the body.
fn parse_frontmatter(raw: &str) -> Frontmatter {


    let stripped = strip_bom(raw);
    let open = stripped.strip_prefix("---\n");
    match open {
        None => {
            

            return Frontmatter { name: "".to_string(), description: "".to_string(), content: stripped.to_string() };
        },
        Some(after_open) => return parse_frontmatter_body(after_open.as_str()),
    }
}

/// Parse the body after the opening `---\n`.
fn parse_frontmatter_body(after_open: &str) -> Frontmatter {
    let close_idx = find_close_marker(after_open);
    match close_idx {
        None => {
            

            let name = extract_field(after_open, "name");
            let desc = extract_field(after_open, "description");
            return Frontmatter { name: name.to_string(), description: desc.to_string(), content: "".to_string() };
        },
        Some(idx) => {
            let lines = after_open.lines();
            let fm = take_lines_joined(lines, idx);
            let body_start = body_offset(after_open, idx);
            let body = slice_and_trim(after_open, body_start);
            let name = extract_field(fm.as_str(), "name");
            let desc = extract_field(fm.as_str(), "description");
            return Frontmatter { name: name.to_string(), description: desc.to_string(), content: body.to_string() };
        },
    }
}

/// Strip a leading UTF-8 BOM (\u{feff}) if present.
fn strip_bom(raw: &str) -> String {
    let p = raw.strip_prefix("\\u{feff}");
    match p {
        Some(rest) => return rest,
        None => return raw.to_string(),
    }
}

/// Index of the line (within `after_open`) whose trimmed content is `---`, or
/// None if no such line exists.
fn find_close_marker(after_open: &str) -> Option<u32> {
    let mut i: u32 = 0;
    for line in after_open.lines() {
        if line.trim_end() == "---" {
            return Some(i as u32);
        }
        i = i + 1;
    }
    return None;
}

/// Join the first `count` lines of `lines` with newlines.
fn take_lines_joined(lines: Vec<String>, count: u32) -> String {
    let mut out: Vec<String> = vec![];
    let mut i: u32 = 0;
    for line in lines {
        if i < count {
            out.push(line.clone());
        }
        i = i + 1;
    }
    return out.join("\n");
}

/// Byte offset of the line just past the closing `---` (the start of the body).
fn body_offset(after_open: &str, close_idx: u32) -> u32 {
    let mut acc: u32 = 0;
    let mut i: u32 = 0;
    for line in after_open.lines() {
        if i <= close_idx {
            

            acc = acc + (line.len() as i32) + 1
        }
        i = i + 1;
    }
    return acc;
}

/// Return the substring of `s` starting at `start`, leading whitespace trimmed.
/// Clamped to s length.
fn slice_and_trim(s: &str, start: u32) -> String {
    let end = (s.len() as i32);
    let mut lo: u32 = start;
    if lo > end as u32 {
        lo = end
    }
    let slice = s.substring(lo, end);
    return slice.trim_start();
}

/// Extract a `key: value` field from frontmatter text. Handles quoted values
/// ("..."/'...') and strips a trailing comment. Returns "" if absent.
fn extract_field(frontmatter: &str, key: &str) -> String {
    let prefix: String = format!("{}:", key);
    for line in frontmatter.lines() {
        let trimmed = line.trim().to_string();
        let rest = trimmed.strip_prefix(prefix);
        match rest {
            Some(r) => return clean_field_value(r.trim().as_str()),
            None => {},
        }
    }
    return "".to_string();
}

/// Strip surrounding quotes (if any) from a frontmatter value.
fn clean_field_value(val: &str) -> String {
    if val.starts_with(&'"') && a2r_std::str_ends_with(val, '"'.as_str()) {
        return unquote(val);
    }
    if val.starts_with("'") && a2r_std::str_ends_with(val, "'") {
        return unquote(val);
    }
    return val.to_string();
}

/// Remove the first and last character (used after the quote-pair check).
fn unquote(val: &str) -> String {
    let end: i32 = (val.len() as i32) - 1;
    return val.substring(1, end);
}

/// The tool that exposes skills to the model. The model calls
/// `skill(skill_name=...)` to load a skill's content on demand.
/// 
/// Its description() is built once at construction (from the registry) so the
/// model sees a directory of available skills + their triggers every turn.
trait ToolTrait {
}

#[derive(Clone, Debug, PartialEq)]
pub struct SkillTool {
    pub registry: Arc<SkillRegistry>,
    pub description_cache: String,
    pub parameters_cache: JsonValue,
}

impl ToolTrait for SkillTool {
}

impl SkillTool {
    pub fn name(&self) -> String {
        return "skill".to_string();
    }
    pub fn description(&self) -> String {
        return self.description_cache.clone();
    }
    pub fn parameters(&self) -> JsonValue {
        return self.parameters_cache.clone();
    }
    pub async fn execute(&self, args: JsonValue) -> Result<String, ToolError> {
        let v = args.get(&"skill_name").as_string();
        if v.is_empty() {
            return Err(Box::new(ToolError::Args("missing 'skill_name' argument")));
        }
        let name = v.clone();
        match self.registry.get(name) {
            Some(skill) => return Ok(format!("# Skill: {}

{}", skill.name, skill.content)),
            None => {
                let available = self.registry.names().join(", ");
                return Err(Box::new(ToolError::Exec(format!("skill '{}' not found; available: {}", name, available))));
            },
        }
    }
    pub fn new(registry: Arc<SkillRegistry>) -> SkillTool {
        return SkillTool { registry: registry, description_cache: build_description(registry.clone()).to_string(), parameters_cache: build_parameters(registry.clone()) };
    }
    pub fn registry(&self) -> SkillRegistry {
        return self.registry.clone();
    }
    pub fn available_skills_block(&self) -> String {
        let descs = self.registry.descriptions();
        if descs.is_empty() {
            return "".to_string();
        }
        let mut out: String = "\n\n<available_skills>\n".to_string();
        out = format!("{}{}", out, "You have access to skills — reusable techniques you load on demand.\n");
        out = format!("{}{}", out, "To use a skill, call the `skill` tool with its name; its content will be\n");
        out = format!("{}{}", out, "returned to you, and you follow its instructions directly.\n\n");
        for pair in descs {
            out = format!("{}{}", out, format!("- {}: {}
", pair[0].clone(), pair[1].clone()));
        }
        out = format!("{}{}", out, "\nInvoke a skill whenever its trigger applies, even slightly.\n");
        out = format!("{}{}", out, "</available_skills>");
        return out;
    }
}

/// Cached description (built from the registry; stable for the tool's life).
/// Cached parameters schema (includes the skill-name enum).
/// Load a skill's content by name. Errors if the skill isn't registered.
/// Build a SkillTool over a shared registry. Caches the description and the
/// parameters schema (which embeds the skill-name enum) for the tool's life.
/// A read-only view of the registry (for bootstrap injection).
/// Build the `<available_skills>` block appended to the system prompt so the
/// model knows what skills it can invoke.
/// Build the tool description string from the registry's skill list.
fn build_description(registry: SkillRegistry) -> String {
    let descs = registry.descriptions();
    if descs.is_empty() {
        return "Load a skill's instructions. No skills are currently configured.".to_string();
    }
    let mut out: String = "Load a skill's instructions by name. Call this whenever a skill's trigger applies.\n\nAvailable skills:\n".to_string();
    for pair in descs {
        out = format!("{}{}", out, format!("- {}: {}
", pair[0].clone(), pair[1].clone()));
    }
    return out;
}

/// Build the parameters JSON schema, embedding the registry's skill names as
/// the `skill_name` enum. Uses json.parse over a stringified schema (the
/// Auto VM's generic json.encode[T] is unreliable — plan 013 gotcha B4).
fn build_parameters(registry: SkillRegistry) -> JsonValue {
    let mut enum_parts: Vec<String> = vec![];
    for n in registry.names() {
        enum_parts.push(format!("\"{}\"", n));
    }
    let enum_list = enum_parts.join(", ");


    let schema: String = format!("{}{}", format!("{}{}", "{\"type\":\"object\",\"properties\":{\"skill_name\":{\"type\":\"string\",\"description\":\"Name of the skill to load\",\"enum\":[", enum_list), "]}},\"required\":[\"skill_name\"]}");
    return a2r_std::json::parse(schema.as_str());
}
