// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

/// Workflow output validators — quality gates for step outputs.
/// 
/// Ported-of-spirit from auto-forge's relay/flow.rs StepValidator. A validator
/// checks a step's textual output and passes/fails it. Validators compose with
/// Validator.All / Validator.Any.
/// 
/// Used by the workflow engine: when a step finishes, its validators run; if
/// any fail (and the step has an on_fail retry), the engine loops back.
/// 
/// Auto port of crates/auto-ai-agent/src/workflow_validator.rs (auto-ai v0.4.0).
/// 
/// VARIANT NOTE: the Rust original uses struct-style enum variants
/// (`OutputContains { pattern }`, `All { validators }`). Auto's AutoVM does not
/// yet implement destructuring of struct-style variants (plan 013 gotcha B3),
/// so the Auto port models them as tuple variants with positional fields
/// (pattern/validators carried positionally). Construction is
/// `Validator.OutputContains("OK")`; matching is `Validator.OutputContains(p)`.
/// A validator that checks a step's output.
/// 
/// Field order (positional tuple variants):
/// - OutputContains(pattern)        — output must contain pattern.
/// - OutputNotContains(pattern)     — output must NOT contain pattern.
/// - OutputMinLength(min)           — output must be at least min chars.
/// - All(validators)                — all inner validators must pass.
/// - Any(validators)                — at least one inner validator must pass.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Validator {
    OutputContains(String),
    OutputNotContains(String),
    OutputMinLength(u32),
    All(Vec<Validator>),
    Any(Vec<Validator>),
}


impl Validator {
    pub fn check(&self, output: &str) -> Result<(), String> {
        match self {
            Validator::OutputContains(pattern) => {
                if a2r_std::str_contains(output, pattern.as_str()) {
                    return Ok(());
                }
                return Err(Box::new(format!("output must contain '{}' (it doesn't)", pattern)));
            },
            Validator::OutputNotContains(pattern) => {
                if a2r_std::str_contains(output, pattern.as_str()) == false {
                    return Ok(());
                }
                return Err(Box::new(format!("output must NOT contain '{}' (it does)", pattern)));
            },
            Validator::OutputMinLength(min) => {
                if (output.len() as i32) >= min {
                    return Ok(());
                }
                return Err(Box::new(format!("output is {} chars, must be at least {}", (output.len() as i32), min)));
            },
            Validator::All(validators) => return check_all(validators, output),
            Validator::Any(validators) => return check_any(validators, output),
        }
    }
}

pub fn check_all(validators: Vec<Validator>, output: &str) -> Result<(), String> {
    for v in validators {
        match v.check(output.as_str()) {
            Ok(_) => {},
            Err(msg) => return Err(msg),
        }
    }
    return Ok(());
}

pub fn check_any(validators: Vec<Validator>, output: &str) -> Result<(), String> {
    let mut failures: u32 = 0;
    for v in validators {
        match v.check(output.as_str()) {
            Ok(_) => return Ok(()),
            Err(_msg) => failures = failures + 1,
        }
    }
    if failures < (validators.len() as u32) {
        

        return Ok(());
    }
    return Err(Box::new(format!("none of {} validators passed", (validators.len() as i32))));
}
