// Auto-generated by a2r transpiler

fn main() {
    let x: i32 = 10;

    match x {
        0 => println!("zero"),
        1 => {
            let msg: String = "one".to_string();
            println!("{}", msg);
        },
        _ => println!("other"),
    }
}
