// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Box {
    pub vals: Vec<i64>,
}

fn mk() -> Vec<i64> {
    let mut l: Vec<i64> = Vec::new();
    l.push(3);
    l.push(4);
    return l;
}

fn sum(mut xs: Vec<i64>) -> i64 {
    let mut t: i64 = 0;
    let mut i: i64 = 0;
    while i < xs.len() as i64 {
        t = t + xs[(i) as usize].clone();
        i = i + 1;
    }
    return t;
}

fn main() {
    let mut l: Vec<i64> = mk();
    println!("{:?}", (l.len() as i64));
    println!("{}", sum(l.clone()));
    let mut rows: Vec<Vec<i64>> = Vec::new();
    let mut row: Vec<i64> = Vec::new();
    row.push(1);
    rows.push(row);
    let mut b: Box = Box { vals: Vec::new() };
    b.vals.push(9);
    println!("{}", b.vals[(0) as usize].clone());
    println!("{:?}", (rows[(0) as usize].clone().len() as i64));
}
