// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn get_float() -> MayFloat {
    let x: f64 = 3.14;
    Some(x)
}

fn main() {
    let a: MayFloat = get_float();
}