// Auto-generated by a2r transpiler

use std::time::{Instant, Duration};
fn expensive_function() -> i64 {
    let mut sum: i64 = 0;
    for i in 0..100000 {
        sum += i;
    }
    sum
}

fn main() {
    let start = Instant::now();
    let result = expensive_function();
    let duration = start.elapsed();

    assert!(result == 704982704);


}
