// Auto-generated by a2r transpiler

pub fn test() -> i64 {
    let mut base_secs: i64 = 1;
    let mut i: i64 = 0;
    while i < 3 {
        base_secs = base_secs * 2;
        i = i + 1;
    }
    return base_secs;
}
