// Auto-generated by a2r transpiler

pub fn test() -> i32 {
    let mut base_secs: i32 = 1;
    let mut i: i32 = 0;
    while i < 3 {
        base_secs = base_secs * 2;
        i = i + 1;
    }
    return base_secs;
}
