// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Cat {
    id: i32,
    name: String,
    color: String,
}

fn main() {
    let mut cats: Vec<Cat> = List::new();
    cats.push(Cat { id: 1, name: "Michi".to_string(), color: "Black".to_string() });
    cats.push(Cat { id: 2, name: "Nori".to_string(), color: "Orange".to_string() });
    cats.push(Cat { id: 3, name: "Bacon".to_string(), color: "Brown".to_string() });

    for cat in cats {
        println!("Found cat {} ({}) with id {}", cat.name, cat.color, cat.id);
    }
}
