// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use rusqlite::Connection;
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Cat {
    id: i32,
    name: String,
    color: String,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let conn = Connection::open("cats.db")?;
    conn.execute("CREATE TABLE IF NOT EXISTS cats (id INTEGER PRIMARY KEY, name TEXT NOT NULL, color TEXT NOT NULL)")?;

    conn.execute("INSERT INTO cats (name, color) VALUES ('Michi', 'Black')")?;
    conn.execute("INSERT INTO cats (name, color) VALUES ('Nori', 'Orange')")?;
    conn.execute("INSERT INTO cats (name, color) VALUES ('Bacon', 'Brown')")?;

    let stmt = conn.prepare("SELECT id, name, color FROM cats")?;
    let cats = stmt.query_map(|row| { return Cat { id: row.get(0).cloned(), name: row.get(1).cloned(), color: row.get(2).cloned() }; })?;

    for cat in cats {
        println!("Found cat {} ({}) with id {}", cat.name, cat.color, cat.id);
    }
    Ok(())
}
