// Auto-generated by a2r transpiler

fn main() {
    let name: String = "AutoLang".to_string();
    let age: i64 = 1;


    let greeting: String = format!("Hello, {}", name);
    println!("{}", greeting);


    let info: String = format!("Name: {}, Age: {}", name, age);
    println!("{}", info);


    let x: i64 = 10;
    let y: i64 = 20;
    let result: String = format!("Result: {}", x + y);
    println!("{}", result);


    let msg: String = format!("The value is {} and {}", x, y * 2);
    println!("{}", msg);


    println!("Direct: {} is {} years old", name, age);


    let a: i64 = 5;
    let b: i64 = 3;
    println!("Sum: {}, Product: {}", a + b, a * b);
}
