// AutoVM Persistent Session (Revised - Efficient)
//
// **Plan 068 Phase 9.6**: Persistent AutoVM REPL with state management
//
// **Architecture**:
// - Keep a single AutoVM instance across inputs (preserves heap_objects, arrays, etc.)
// - Keep a single main task across inputs (preserves stack state)
// - Reuse the same Codegen object (preserves locals, exports, strings, etc.)

use crate::error::{AutoError, AutoResult};
use crate::vm::codegen::Codegen;
use crate::vm::engine::AutoVM;
use crate::vm::opcode::OpCode;
use crate::vm::task::TaskId;
use crate::vm::virt_memory::VirtualFlash;
use crate::Parser;
use std::collections::HashMap;
use std::sync::Arc;

/// Persistent AutoVM REPL session
///
/// **Efficient Implementation**: Reuses Codegen to avoid allocations
pub struct AutovmReplSession {
    /// Single VM instance (persistent across inputs)
    vm: AutoVM,

    /// Main task ID (persistent across inputs)
    main_task_id: TaskId,

    /// Reusable Codegen (contains locals, exports, strings, etc.)
    /// Option allows moving it out during run() and moving it back
    codegen: Option<Codegen>,

    /// All bytecode compiled so far (for flash updates)
    bytecode: Vec<u8>,

    /// Object keys metadata
    object_keys: Vec<Vec<auto_val::ValueKey>>,

    /// Object types metadata
    object_types: Vec<Vec<crate::vm::codegen::ObjectType>>,

    /// Last result from the previous REPL input (Plan 080)
    /// Stores the result value for access in subsequent inputs
    last_result: Option<i32>,
}

impl AutovmReplSession {
    /// Create a new persistent AutoVM REPL session
    pub fn new() -> Self {
        // Create initial Codegen
        let mut codegen = Codegen::new();

        // Start with HALT opcode
        let bytecode = vec![OpCode::HALT as u8];
        let flash = VirtualFlash::new_with_code(bytecode.clone());

        // Create VM
        let mut vm = AutoVM::new(flash, 1024);
        vm.load_strings(Vec::new());

        // Spawn main task
        let task_id = vm.spawn_task(0, 1024);

        // Plan 080: Set bp=1 to reserve space for return address
        // This ensures local variables start at bp+1, not bp+0
        let task_arc = vm.tasks.get(&task_id).unwrap().clone();
        let mut task = task_arc.blocking_lock();
        task.bp = 1;
        drop(task);

        Self {
            vm,
            main_task_id: task_id,
            codegen: Some(codegen),  // Store Codegen for reuse
            bytecode,
            object_keys: Vec::new(),
            object_types: Vec::new(),
            last_result: None,  // Plan 080: Initialize last_result
        }
    }

    /// Execute code with persistent state
    ///
    /// **Efficient**: Reuses Codegen to avoid allocations
    pub fn run(&mut self, code: &str) -> AutoResult<String> {
        // 1. Parse the code
        let mut parser = Parser::from(code);

        // Plan 080: Enable skip_check for REPL mode
        // This allows using undefined variables (e.g., "x" as a statement)
        // Variables will be checked at runtime by the VM
        parser = parser.skip_check();

        let ast = parser.parse()?;

        // Debug: Print AST
        eprintln!("DEBUG: Parsed {} statements from: '{}'", ast.stmts.len(), code);
        for (i, stmt) in ast.stmts.iter().enumerate() {
            eprintln!("DEBUG:   Stmt {}: {:?}", i, stmt);
        }

        if ast.stmts.is_empty() {
            return Ok(String::new());
        }

        // 2. Take Codegen (move out for efficient reuse)
        let mut codegen = self.codegen.take().unwrap();

        // Debug: Print scope_stack before compilation
        eprintln!("DEBUG: Before compilation, scope_stack = {:?}", codegen.scope_stack);

        // Clear previous bytecode (IMPORTANT: don't accumulate!)
        codegen.code.clear();

        // 3. Compile new statements (reuses locals, exports, strings, etc.)
        for stmt in &ast.stmts {
            codegen.compile_stmt(stmt)?;
        }

        // 4. Add HALT at the end
        codegen.code.push(OpCode::HALT as u8);

        // Debug: Print generated bytecode (hex dump)
        eprintln!("DEBUG: Generated {} bytes of bytecode", codegen.code.len());
        let mut i = 0;
        while i < codegen.code.len() {
            let opcode = OpCode::from(codegen.code[i]);
            eprint!("DEBUG:   [{:04x}] {:02x} {:?}", i, codegen.code[i], opcode);
            i += 1;
            // Print immediate values based on opcode
            match opcode {
                OpCode::CONST_I32 | OpCode::CONST_U8 | OpCode::LOAD_LOCAL | OpCode::STORE_LOCAL => {
                    if i < codegen.code.len() {
                        eprint!(" (imm: {:02x})", codegen.code[i]);
                        i += 1;
                    }
                }
                _ => {}
            }
            eprintln!();
        }

        // 5. Check if all relocations can be resolved (before modifying code)
        // Collect symbols to check first
        let undefined_symbols: Vec<String> = codegen.relocs.iter()
            .filter(|reloc| !codegen.exports.contains_key(&reloc.symbol_name))
            .map(|reloc| reloc.symbol_name.clone())
            .collect();

        if !undefined_symbols.is_empty() {
            // Put Codegen back before returning error
            self.codegen = Some(codegen);
            return Err(AutoError::Msg(format!(
                "Undefined function: {}",
                undefined_symbols[0]
            )));
        }

        // 6. Resolve relocations using existing symbols
        // Note: We need to clone the code to avoid moving from codegen
        let new_code = codegen.code.clone();
        for reloc in &codegen.relocs {
            if let Some(&addr) = codegen.exports.get(&reloc.symbol_name) {
                let bytes = addr.to_le_bytes();
                let offset = reloc.offset as usize;
                for (i, b) in bytes.iter().enumerate() {
                    unsafe {
                        let code_ptr = new_code.as_ptr() as *mut u8;
                        code_ptr.add(offset + i).write(*b);
                    }
                }
            }
        }

        // 6. Update bytecode
        eprintln!("DEBUG: Before bytecode update - bytecode.len()={}", self.bytecode.len());
        self.bytecode.pop();
        let new_code_start = self.bytecode.len();
        self.bytecode.extend_from_slice(&new_code);
        eprintln!("DEBUG: After bytecode update - bytecode.len()={}, new_code_start={}", self.bytecode.len(), new_code_start);

        // 7. Update metadata (clone to avoid move)
        self.object_keys.extend(codegen.object_keys.clone());
        self.object_types.extend(codegen.object_types.clone());

        // 8. Update flash and strings
        let mut flash = VirtualFlash::new_with_code(self.bytecode.clone());
        flash.object_keys = self.object_keys.clone();
        flash.object_types = self.object_types.clone();

        // Update VM's flash and strings
        self.vm.flash = Arc::new(flash);
        self.vm.strings = Arc::new(std::sync::RwLock::new(codegen.strings.clone()));

        // 9. Put Codegen back (preserves locals, exports, strings, etc.)
        self.codegen = Some(codegen);

        // 10. Reuse the same task (DO NOT create new task - preserves stack!)
        let task_arc = self.vm.tasks.get(&self.main_task_id)
            .ok_or_else(|| AutoError::Msg("Main task not found".to_string()))?
            .clone();

        let mut task = task_arc.blocking_lock();

        // 11. Reset task status to Ready (it may be Terminated from previous execution)
        task.status = crate::vm::task::TaskStatus::Ready;

        // Plan 080: Reset stack pointer to (bp + 1 + num_locals)
        // Stack frame layout: [unused, local0, local1, ..., temps...]
        //                     bp-1     bp     bp+1
        // Local variables occupy bp+1 to bp+num_locals
        // Stack temps MUST start AFTER all locals: at bp + 1 + num_locals
        // NOT at bp + num_locals (which would overlap with the last variable!)
        let num_locals = self.codegen.as_ref()
            .and_then(|c| c.scope_stack.last())
            .map(|scope| scope.len())
            .unwrap_or(0);
        task.ram.sp = task.bp + 1 + num_locals;

        // Debug: Print state BEFORE execution
        eprintln!("DEBUG: BEFORE execution - bp={}, sp={}, ip={}, num_locals={}, raw[0..5]={:?}",
            task.bp, task.ram.sp, task.ip, num_locals, &task.ram.raw[0..5]);

        // 12. Update IP to point to new code, but KEEP STACK (bp, sp, ram unchanged)
        task.ip = new_code_start;

        // 12. Execute the code
        drop(task); // Release lock before execution
        let rt = tokio::runtime::Runtime::new()?;
        rt.block_on(async {
            self.vm.run_task_loop().await;
        });

        // 13. Get result from the task (re-acquire lock after execution)
        let task_arc = self.vm.tasks.get(&self.main_task_id)
            .ok_or_else(|| AutoError::Msg("Main task not found after execution".to_string()))?
            .clone();

        let mut task = task_arc.blocking_lock();

        // Debug: Print stack state AFTER execution
        eprintln!("DEBUG: AFTER execution - bp={}, sp={}, ip={}, raw[0..5]={:?}",
            task.bp, task.ram.sp, task.ip, &task.ram.raw[0..5]);

        // Plan 080: Get number of local variables
        let num_locals = self.codegen.as_ref()
            .and_then(|c| c.scope_stack.last())
            .map(|scope| scope.len())
            .unwrap_or(0);

        // Calculate target stack pointer (bp + 1 + num_locals)
        // Stack frame layout: [unused, local0, local1, ..., localN, temps...]
        //                     bp-1    bp     bp+1    bp+2   bp+N+1
        // Local variables occupy bp+1 to bp+num_locals
        // Stack temps start at bp + 1 + num_locals (NOT bp + num_locals!)
        let target_sp = task.bp + 1 + num_locals;

        eprintln!("DEBUG: num_locals={}, bp={}, target_sp={}, current_sp={}",
            num_locals, task.bp, target_sp, task.ram.sp);

        // Check if there's a temporary result on stack (sp > target_sp)
        if task.ram.sp > target_sp {
            // Save the result to last_result (Plan 080)
            let result = task.ram.pop_i32();
            self.last_result = Some(result);
            eprintln!("DEBUG: Saved result to last_result: {}", result);
        }

        // Reset stack pointer to target_sp (clear all temporary values)
        task.ram.sp = target_sp;

        eprintln!("DEBUG: After stack cleanup - sp={}, raw[0..5]={:?}", task.ram.sp, &task.ram.raw[0..5]);

        // Return empty string (REPL will display last_result)
        Ok(String::new())

    }

    /// Get session statistics
    pub fn stats(&self) -> AutovmReplStats {
        let total_locals = self.codegen.as_ref()
            .map(|c| c.locals.len())
            .unwrap_or(0);
        let total_exports = self.codegen.as_ref()
            .map(|c| c.exports.len())
            .unwrap_or(0);
        let total_strings = self.codegen.as_ref()
            .map(|c| c.strings.len())
            .unwrap_or(0);

        AutovmReplStats {
            total_functions: total_exports,
            total_locals,
            bytecode_size: self.bytecode.len(),
            total_strings,
            heap_objects: self.vm.heap_objects.len(),
            arrays: self.vm.arrays.len(),
        }
    }

    /// Clear all state (start fresh)
    pub fn reset(&mut self) {
        // Reset bytecode
        self.bytecode = vec![OpCode::HALT as u8];
        self.object_keys.clear();
        self.object_types.clear();

        // Reset Codegen (recreate fresh one)
        self.codegen = Some(Codegen::new());

        // Clear VM registries
        self.vm.closures.clear();
        self.vm.iterators.clear();
        self.vm.channels.clear();
        self.vm.heap_objects.clear();
        self.vm.arrays.clear();
        self.vm.objects.clear();
        self.vm.nodes.clear();
    }

    /// Get list of defined functions
    pub fn functions(&self) -> Vec<String> {
        self.codegen.as_ref()
            .map(|c| c.exports.keys().cloned().collect())
            .unwrap_or_default()
    }

    /// Get list of local variables
    pub fn locals(&self) -> Vec<String> {
        self.codegen.as_ref()
            .map(|c| c.locals.keys().cloned().collect())
            .unwrap_or_default()
    }

    /// Get the last result (Plan 080)
    ///
    /// Returns the result from the previous REPL input, if any.
    /// This is used by the REPL to display results to the user.
    pub fn get_last_result(&self) -> Option<i32> {
        self.last_result
    }
}

/// REPL session statistics
#[derive(Debug, Clone)]
pub struct AutovmReplStats {
    pub total_functions: usize,
    pub total_locals: usize,
    pub bytecode_size: usize,
    pub total_strings: usize,
    pub heap_objects: usize,
    pub arrays: usize,
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_autovm_session_create() {
        let session = AutovmReplSession::new();
        assert!(session.codegen.is_some());
        assert_eq!(session.bytecode.len(), 1); // Just HALT
    }

    #[test]
    fn test_autovm_session_stats() {
        let session = AutovmReplSession::new();
        let stats = session.stats();
        assert_eq!(stats.total_functions, 0);
        assert_eq!(stats.total_locals, 0);
        assert_eq!(stats.bytecode_size, 1);
    }

    #[test]
    fn test_autovm_session_reset() {
        let mut session = AutovmReplSession::new();
        session.bytecode.push(OpCode::ADD as u8);
        assert_eq!(session.bytecode.len(), 2);

        session.reset();
        assert_eq!(session.bytecode.len(), 1); // Just HALT
        assert!(session.codegen.is_some()); // Codegen recreated
    }

    #[test]
    fn test_autovm_session_functions() {
        let session = AutovmReplSession::new();
        let funcs = session.functions();
        assert_eq!(funcs.len(), 0);

        let locals = session.locals();
        assert_eq!(locals.len(), 0);
    }

    #[test]
    fn test_autovm_session_simple_arithmetic() {
        let mut session = AutovmReplSession::new();

        // Simple arithmetic
        let result = session.run("1 + 2");
        assert!(result.is_ok());
    }

    #[test]
    fn test_autovm_task_reuse_variable_persistence() {
        let mut session = AutovmReplSession::new();

        // Define variable
        let result = session.run("let x = 10");
        assert!(result.is_ok());

        // Access variable in next input (should return 11 if task reuse works)
        let result = session.run("x + 1");
        assert!(result.is_ok());

        // Debug: Print result to see actual value
        if let Ok(s) = &result {
            println!("x + 1 = {}", s);
            // Currently expected to be "1" (bug), should be "11" (fixed)
        }

        // Note: This test currently expected to fail until we implement
        // proper stack frame management or global variables
        // After fix, result should be "11" instead of "1"
    }

    #[test]
    fn test_autovm_task_stack_state() {
        let mut session = AutovmReplSession::new();

        // Define two variables
        let _ = session.run("let a = 5");
        let _ = session.run("let b = 10");

        // Access both variables
        let result1 = session.run("a + b");
        assert!(result1.is_ok());

        if let Ok(s) = &result1 {
            println!("a + b = {} (expected: 15)", s);
        }

        // Define third variable using first variable
        let _ = session.run("let c = a * 2");
        let result2 = session.run("c");
        assert!(result2.is_ok());

        if let Ok(s) = &result2 {
            println!("c = {} (expected: 10)", s);
        }
    }

    #[test]
    fn test_autovm_simple_persistence_check() {
        let mut session = AutovmReplSession::new();

        // Define x
        let r1 = session.run("let x = 10");
        assert!(r1.is_ok(), "let x = 10 should succeed");

        // Try to access x
        let r2 = session.run("x + 1");
        assert!(r2.is_ok(), "x + 1 should succeed");

        // Check the result
        match r2 {
            Ok(s) => {
                // If this is "11", variable persistence works!
                // If this is "1", variable is not persisted (current bug)
                assert_eq!(s, "11", "Variable x should persist with value 10, so x+1=11");
            }
            Err(e) => {
                panic!("x + 1 failed: {:?}", e);
            }
        }
    }
}
