// Auto-generated by a2r transpiler

trait Store<T> {
    type Item;
    fn make(&self, v: T) -> Self::Item;
    fn first(&self) -> Self::Item;
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct IntStore {
    pub data: Vec<String>,
}

impl Store<i64> for IntStore {
    type Item = String;
    fn make(&self, v: i64) -> String {
        return format!("{}{}", "box:", format!("{:?}", v));
    }
    fn first(&self) -> String {
        return self.data[0].clone();
    }
}

pub fn main() {
    let mut s = IntStore { data: vec!["a".to_string(), "b".to_string()] };
    println!("{}", s.make(7));
    println!("{}", s.first());
}
