// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::boxed::Box;
use std::cell::RefCell;
fn main() {
    let b = Box::new(42);
    let cell = RefCell::new(0);
    let mut val = cell.borrow_mut();
    val = val + 1;
}
