// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

async fn fetch_body(url: &str) -> String {
    let res = a2r_std::http::post_async(url, "async-ping").await;
    return a2r_std::str::from_bytes(res.body_bytes());
}

#[tokio::main]
async fn main() {
    let base = a2r_std::env::get("PLAN727_URL");
    let dst = a2r_std::env::get("PLAN727_DST");

    let t = a2r_std::http::transfer_download(base.as_str(), dst.as_str(), "{}");
    let receipt = a2r_std::http::transfer_wait_async(&t).await;
    println!("receipt: {}", receipt);

    let up = a2r_std::http::transfer_upload(base.as_str(), dst.as_str(), "{}");
    let p = a2r_std::http::transfer_next_progress(&up);
    println!("progress: {}", p);
    a2r_std::http::transfer_cancel(&up);
    let up_receipt = a2r_std::http::transfer_wait_async(&up).await;
    println!("cancelled: {}", up_receipt);

    let body = fetch_body(base.as_str()).await;
    println!("body: {}", body);
}
