// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use rayon::prelude::*;
fn main() {
    let v: Vec<i32> = vec![1, 2, 3, 4, 5];
    let has_even = v.par_iter().any(|x| x % 2 == 0);
    let all_positive = v.par_iter().all(|x| x > 0);
    assert!(has_even == true);
    assert!(all_positive == true);
}
