// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let addr: String = "127.0.0.1:8080".to_string();
    println!("Listening on {}", addr);
    println!("Ready to accept connections");
}
