// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::vec::Vec;
fn main() {
    let mut vec: Vec<f64> = vec![1.1, 1.15, 5.5, 1.123, 2.0];
    vec.sort_by(|a, b| a.total_cmp(b));
    println!("{:?}", vec);
}
