// Auto-generated by a2r transpiler

#[zbus::interface(name = "com.system76.CosmicSession")]
impl CosmicSession {
    fn ping(&self) -> String {
        return "pong".to_string();
    }
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct CosmicSession2 {}

#[zbus::interface(name = "com.system76.CosmicSession2")]
impl CosmicSession2 {
    fn state(&self) -> String {
        return "idle".to_string();
    }
}

#[tokio::main]
fn main() {
    return;
}
