// Auto-generated by a2r transpiler

trait Container {
    type Item;
    fn get(&self, i: i64) -> Self::Item;
    fn first(&self) -> Self::Item;
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct IntBox {
    pub data: Vec<i64>,
}

impl Container for IntBox {
    type Item = i64;
    fn get(&self, i: i64) -> i64 {
        return self.data[(i) as usize].clone();
    }
    fn first(&self) -> i64 {
        let mut x: i64 = self.data[0].clone();
        return x;
    }
}

pub fn main() {
    let mut b = IntBox { data: vec![7, 8, 9] };
    println!("{}", b.get(1));
    println!("{}", b.first());
}
