// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Val {
    VI(i64),
    VS(String),
    VN,
}


fn main() {
    let v = Val::VI(42);
    match v {
        Val::VI(x) => println!("{}", x),
        _ => println!("{}", 0),
    };
}
