// Auto-generated by a2r transpiler

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum K {
    A = 0,
    B = 1,
    C = 2,
}

impl std::fmt::Display for K {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            K::A => write!(f, "A"),
            K::B => write!(f, "B"),
            K::C => write!(f, "C"),
        }
    }
}
impl K {
    pub fn from_id(id: &str) -> Self {
        match id {
            "A" | "a" => K::A,
            "B" | "b" => K::B,
            "C" | "c" => K::C,
            _ => K::A
        }
    }
}

fn classify(n: i64) -> K {
    if n == 1 {
        return K::B;
    }
    if n == 2 {
        return K::C;
    }
    return K::A;
}

fn main() {
    let mut total: i64 = 0;
    let mut i: i64 = 0;
    while i < 10 {
        let mut k = classify(i);
        match k {
            K::A => {
                total = total + i;
                i = i + 1;
            },
            K::B => {
                i = i + 1;
                continue;
            },
            _ => {
                break;
            },
        };
    }
    println!("{}", total);
}
