// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Counter {
    pub value: i64,
}

impl Counter {
    fn get(&self) -> i64 {
        return self.value;
    }
    fn add(&self, n: i64) -> i64 {
        return self.value + n;
    }
}

fn main() {
    let mut c = Counter { value: 10 };
    println!("{}", c.get());
    println!("{}", c.add(5));
}
