// Auto-generated by a2r transpiler

fn main() {
    let mut l: Vec<i64> = Vec::new();
    l.push(10);
    l.push(20);
    println!("{:?}", (l.len() as i64));
    println!("{:?}", l[(0) as usize].clone());
    println!("{:?}", l[(1) as usize].clone());
    l[(0) as usize] = 99;
    println!("{:?}", l[(0) as usize].clone());
}
