// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn add_values() -> MayInt {
    let a: i32 = 10;
    let b: i32 = 20;
    let result: i32 = a + b;
    Some(result)
}

fn main() {
    let sum: MayInt = add_values();
}