// Auto-generated by a2r transpiler

use regex::Regex;
fn main() {
    let re = Regex::new("ERROR: .+").unwrap();
    let log: String = "INFO: started\nERROR: file not found\nWARN: retrying\nERROR: disk full".to_string();
    let matches = re.captures_iter(log);
    assert!((matches.len() as i32) == 2);
}
