// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

type List<T> = List<T>;

fn main() {
    let list = List::new();
    list.push(1);
    list.push(2);
}
