// Auto-generated by a2r transpiler

use std::collections::HashMap;
fn main() {
    let x: i32 = 42;
    let y: i32 = x + 8;
    println!("Answer: {}", y);

    let mut scores: HashMap<String, i32> = HashMap::new();
    scores.insert("alice".to_string(), 100);
    scores.insert("bob".to_string(), 95);

    for (k, v) in &scores {
        println!("{}: {}", k, v);
    }
}
