// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Stargazer {
    login: String,
    id: u32,
    starred_at: String,
}

fn main() {
    let mut stargazers: Vec<Stargazer> = List::new();
    stargazers.push(Stargazer { login: "user1".to_string(), id: 1, starred_at: "2024-01-01".to_string() });
    stargazers.push(Stargazer { login: "user2".to_string(), id: 2, starred_at: "2024-01-02".to_string() });

    for sg in stargazers {
        println!("{} starred at {}", sg.login, sg.starred_at);
    }
}
