// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use reqwest;
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Stargazer {
    login: String,
    id: u32,
    starred_at: String,
}

#[tokio::main]
async fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    let client = reqwest.Client.new();
    let response = client.get("https://api.github.com/repos/rust-lang/rust/stargazers").cloned().header("User-Agent", "reqwest-example").send().await?;

    let stargazers = response.json(List<Stargazer>).await?;
    for sg in stargazers {
        println!("{} starred at {}", sg.login, sg.starred_at);
    }
    Ok(())
}
