// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use reqwest;
fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    let client = reqwest.Client.new();

    let response = client.post("https://api.github.com/gists").header("User-Agent", "reqwest-example").basic_auth("user", "token").send().await?;

    println!("Status: {}", response.status());
    Ok(())
}
