// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use reqwest;
use std::time::Duration;
#[tokio::main]
async fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    let client = reqwest.Client.builder().timeout(Duration::from_secs(5)).build()?;

    let response = client.head("https://httpbin.org/get").send().await?;
    println!("Status: {}", response.status());

    for (key, value) in &response.headers() {
        println!("{}: {}", key, value);
    }
    Ok(())
}
