// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct MyStruct<T> {
    value: *mut T,
}

fn main() {
    let _x: i32 = 42;
}
