// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Counter {
    pub value: i64,
}

impl Counter {
    fn new(v: i64) -> Counter {
        return Counter { value: v };
    }
    fn get(&self) -> i64 {
        return self.value;
    }
}

fn main() {
    let c = Counter::new(10);
    println!("{}", c.get());
    let d = Counter { value: 7 };
    println!("{}", d.get());
}
