// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

pub fn test() -> i32 {
    let file_ext: String = ".rs".to_string();
    return 0;
}
