// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Name {
    value: String,
}

impl From<String> for Name {
    fn from(s: String) -> Name {
        return Name { value: s };
    }
}

fn main() {
    let n = Name::from("hello");
}
