// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use unicode_segmentation::UnicodeSegmentation;
fn main() {
    let text: String = "hello world".to_string();
    let count = (text.len() as i32);
    assert!(count == 11);
}
