// Auto-generated by a2r transpiler

use unicode_segmentation::UnicodeSegmentation;
fn main() {
    let text: String = "hello world".to_string();
    let count = (text.len() as i64);
    assert!(count == 11);
}
