// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Counter {
    pub value: i64,
}

impl Counter {
    fn get(&self) -> i64 {
        return self.value;
    }
    fn add(&self, n: i64) -> i64 {
        return self.value + n;
    }
    fn new(v: i64) -> Counter {
        return Counter { value: v };
    }
    fn bump(&mut self) {
        self.value = self.value + 1;
    }
    fn double(&self) -> i64 {
        return self.value * 2;
    }
}

fn main() {
    let mut c = Counter::new(20);
    println!("{}", c.get());
    println!("{}", c.add(5));
    c.bump();
    println!("{}", c.double());
    println!("{}", c.get());
}
