// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use once_cell::sync::Lazy;
use std::sync::Mutex;

static COUNTER: Lazy<Mutex<i32>> = Lazy::new(|| Mutex::new(0));

static APP_NAME: Lazy<Mutex<&str>> = Lazy::new(|| Mutex::new("AutoLang"));

fn main() {
    *COUNTER.lock().unwrap() += 1;
    say(APP_NAME.lock().unwrap());
    say(COUNTER.lock().unwrap());
}
