// Auto-generated by a2r transpiler

use std::sync::Mutex;

static COUNTER: Mutex<i64> = Mutex::new(0);

static APP_NAME: Mutex<&str> = Mutex::new("AutoLang");

fn main() {
    { let __a2r_gv = 1; *COUNTER.lock().unwrap() += __a2r_gv; };
    say(*APP_NAME.lock().unwrap());
    say(*COUNTER.lock().unwrap());
}
