// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use serde_json;
use serde_json::Value;
fn main() {
    let json_str: String = "{\"name\": \"Alice\", \"age\": 30}".to_string();
    let parsed = serde_json::from_str(json_str.as_str());
    println!("Parsed: {}", parsed);
    let encoded = serde_json.to_string("hello world");
    assert!(a2r_std::str_contains(encoded.as_str(), "hello"));
}
