// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use std::fs;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let entries = fs::read_dir(".")?;
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name();
        let name_str = name.to_str().unwrap();
        println!("File: {}", name_str);
    }
    Ok(())
}
