// Auto-generated by a2r transpiler

fn check_str(name: &str, actual: &str, expected: &str) {
    if actual == expected {
        println!("{}", format!("{}{}", "ok - ", name));
    } else {
        println!("{}", format!("{}{}", format!("{}{}", format!("{}{}", "not ok - ", name), " got "), actual));
    }

}

fn greet(who: &str) -> String {
    return format!("{}{}", "hello ", who);
}

fn relay(label: &str, got: &str) {

    check_str(label, got, "hello relay");
}

fn main() {



    let tagged: String = greet("world");
    check_str("tagged_local", tagged.as_str(), "hello world");


    let inferred = greet("auto");
    check_str("inferred_local", inferred.as_str(), "hello auto");


    check_str("literal", "hello lit", "hello lit");


    relay("param_relay", "hello relay");




    let prefix_source: String = "admin-panel".to_string();
    match prefix_source.strip_prefix("admin-") {
        Some(rest) => check_str("some_binding", rest, "panel"),
        None => check_str("some_binding", "none_arm", "none_arm"),
    };
}
