// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use walkdir::WalkDir;
use std::fs;
fn main() {
    for entry in WalkDir::new("src").into_iter() {
        let e = entry.ok();
        if e.file_type().is_file() {
            let meta = fs.metadata(e.path()).unwrap();
            let modified = meta.modified().unwrap();
            println!("{}: {}", e.path().display(), modified);
        }
    }
}
