//! Hard-coded manifest definitions for the 5 standard C headers.
//!
//! Plan 216 takes the recommended approach: manifests are pre-generated by
//! developers rather than requiring libclang/bindgen at build time.

use crate::manifest::*;

/// Return the manifest for a well-known standard header, or `None`.
pub fn get_builtin_manifest(header: &str) -> Option<CHeaderManifest> {
    match header {
        "string.h" | "<string.h>" => Some(string_manifest()),
        "math.h" | "<math.h>" => Some(math_manifest()),
        "stdio.h" | "<stdio.h>" => Some(stdio_manifest()),
        "stdlib.h" | "<stdlib.h>" => Some(stdlib_manifest()),
        "time.h" | "<time.h>" => Some(time_manifest()),
        _ => None,
    }
}

fn p(name: &str, ty: CTypeDesc) -> CParam {
    CParam { name: name.to_string(), ty }
}

fn string_manifest() -> CHeaderManifest {
    CHeaderManifest {
        header: "string.h".into(),
        library: "c".into(),
        functions: vec![
            CFunction {
                name: "strlen".into(),
                params: vec![p("s", CTypeDesc::CStr)],
                return_type: CTypeDesc::Size,
                variadic: false,
            },
            CFunction {
                name: "strcmp".into(),
                params: vec![p("s1", CTypeDesc::CStr), p("s2", CTypeDesc::CStr)],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "strncmp".into(),
                params: vec![p("s1", CTypeDesc::CStr), p("s2", CTypeDesc::CStr), p("n", CTypeDesc::Size)],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "strcpy".into(),
                params: vec![p("dest", CTypeDesc::PtrMut), p("src", CTypeDesc::CStr)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
            CFunction {
                name: "strcat".into(),
                params: vec![p("dest", CTypeDesc::PtrMut), p("src", CTypeDesc::CStr)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
            CFunction {
                name: "strdup".into(),
                params: vec![p("s", CTypeDesc::CStr)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
            CFunction {
                name: "memset".into(),
                params: vec![p("s", CTypeDesc::PtrMut), p("c", CTypeDesc::Int), p("n", CTypeDesc::Size)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
            CFunction {
                name: "memcpy".into(),
                params: vec![p("dest", CTypeDesc::PtrMut), p("src", CTypeDesc::Ptr), p("n", CTypeDesc::Size)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
        ],
    }
}

fn math_manifest() -> CHeaderManifest {
    CHeaderManifest {
        header: "math.h".into(),
        library: "m".into(),
        functions: vec![
            CFunction {
                name: "abs".into(),
                params: vec![p("x", CTypeDesc::Int)],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "sqrt".into(),
                params: vec![p("x", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "sin".into(),
                params: vec![p("x", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "cos".into(),
                params: vec![p("x", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "tan".into(),
                params: vec![p("x", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "ceil".into(),
                params: vec![p("x", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "floor".into(),
                params: vec![p("x", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "pow".into(),
                params: vec![p("x", CTypeDesc::Double), p("y", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "fmin".into(),
                params: vec![p("x", CTypeDesc::Double), p("y", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "fmax".into(),
                params: vec![p("x", CTypeDesc::Double), p("y", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
        ],
    }
}

fn stdio_manifest() -> CHeaderManifest {
    CHeaderManifest {
        header: "stdio.h".into(),
        library: "c".into(),
        functions: vec![
            CFunction {
                name: "puts".into(),
                params: vec![p("s", CTypeDesc::CStr)],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "getchar".into(),
                params: vec![],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "fopen".into(),
                params: vec![p("path", CTypeDesc::CStr), p("mode", CTypeDesc::CStr)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
            CFunction {
                name: "fclose".into(),
                params: vec![p("stream", CTypeDesc::Ptr)],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "fgets".into(),
                params: vec![p("s", CTypeDesc::PtrMut), p("size", CTypeDesc::Int), p("stream", CTypeDesc::Ptr)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
            CFunction {
                name: "fputs".into(),
                params: vec![p("s", CTypeDesc::CStr), p("stream", CTypeDesc::Ptr)],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
        ],
    }
}

fn stdlib_manifest() -> CHeaderManifest {
    CHeaderManifest {
        header: "stdlib.h".into(),
        library: "c".into(),
        functions: vec![
            CFunction {
                name: "malloc".into(),
                params: vec![p("size", CTypeDesc::Size)],
                return_type: CTypeDesc::Ptr,
                variadic: false,
            },
            CFunction {
                name: "free".into(),
                params: vec![p("ptr", CTypeDesc::Ptr)],
                return_type: CTypeDesc::Void,
                variadic: false,
            },
            CFunction {
                name: "atoi".into(),
                params: vec![p("s", CTypeDesc::CStr)],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "atof".into(),
                params: vec![p("s", CTypeDesc::CStr)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
            CFunction {
                name: "rand".into(),
                params: vec![],
                return_type: CTypeDesc::Int,
                variadic: false,
            },
            CFunction {
                name: "srand".into(),
                params: vec![p("seed", CTypeDesc::UInt)],
                return_type: CTypeDesc::Void,
                variadic: false,
            },
            CFunction {
                name: "exit".into(),
                params: vec![p("code", CTypeDesc::Int)],
                return_type: CTypeDesc::Void,
                variadic: false,
            },
        ],
    }
}

fn time_manifest() -> CHeaderManifest {
    CHeaderManifest {
        header: "time.h".into(),
        library: "c".into(),
        functions: vec![
            CFunction {
                name: "time".into(),
                params: vec![p("tloc", CTypeDesc::PtrMut)],
                return_type: CTypeDesc::Long,
                variadic: false,
            },
            CFunction {
                name: "clock".into(),
                params: vec![],
                return_type: CTypeDesc::Long,
                variadic: false,
            },
            CFunction {
                name: "difftime".into(),
                params: vec![p("end", CTypeDesc::Double), p("begin", CTypeDesc::Double)],
                return_type: CTypeDesc::Double,
                variadic: false,
            },
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_builtin_manifests_exist() {
        assert!(get_builtin_manifest("string.h").is_some());
        assert!(get_builtin_manifest("math.h").is_some());
        assert!(get_builtin_manifest("stdio.h").is_some());
        assert!(get_builtin_manifest("stdlib.h").is_some());
        assert!(get_builtin_manifest("time.h").is_some());
        assert!(get_builtin_manifest("<string.h>").is_some());
        assert!(get_builtin_manifest("nonexistent.h").is_none());
    }

    #[test]
    fn test_string_manifest_serializes() {
        let m = string_manifest();
        let json = serde_json::to_string_pretty(&m).unwrap();
        let back: CHeaderManifest = serde_json::from_str(&json).unwrap();
        assert_eq!(back.header, "string.h");
        assert_eq!(back.functions.len(), 8);
    }

    #[test]
    fn test_math_manifest_functions() {
        let m = math_manifest();
        assert_eq!(m.functions.len(), 10);
        let sqrt = m.functions.iter().find(|f| f.name == "sqrt").unwrap();
        assert_eq!(sqrt.params.len(), 1);
        assert_eq!(sqrt.params[0].ty, CTypeDesc::Double);
        assert_eq!(sqrt.return_type, CTypeDesc::Double);
    }
}
