// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use reqwest;
#[tokio::main]
async fn main() -> Result<Future<()>, Box<dyn std::error::Error>> {
    let client = reqwest.Client.new();
    let response = client.get("https://httpbin.org/basic-auth/user/pass").cloned().basic_auth("user", "pass").send().await?;

    let body = response.text().await?;
    println!("Body: {}", body);
    Ok(())
}
