// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let mut x: i32 = 0;
    loop {
        x = x + 1;
        if x >= 3 {
            println!("{}", x);
            break;
        }
    }
    println!("done");
}
