// Auto-generated by a2r transpiler

fn main() {
    let mut x: i32 = 0;
    loop {
        x = x + 1;
        if x >= 3 {
            println!("{}", x);
            break;
        }
    }
    println!("done");
}
