// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::fs;
fn main() -> Result<(), String> {
    let content: String = "line1\nline2\nline3".to_string();
    let path: String = "test_temp.txt".to_string();
    std::fs::write(path, content).is_ok()?;
    let lines = std::fs::read_to_string(path).ok()?;
    for line in lines.lines() {
        println!("Line: {}", line);
    }
    fs.remove_file(path)?
}
