// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use rand::Rng;
#[derive(Clone, Debug, PartialEq)]
enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}

impl std::fmt::Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Color::Red => write!(f, "Red"),
            Color::Green => write!(f, "Green"),
            Color::Blue => write!(f, "Blue"),
        }
    }
}

fn main() {
    let mut rng = thread_rng();
    let colors = vec![Color::Red, Color::Green, Color::Blue];
    let idx = rng.gen_range(0..3);
    let color = colors[(idx) as usize];
    match color {
        Color::Red => println!("Red"),
        Color::Green => println!("Green"),
        Color::Blue => println!("Blue"),
    }
}
