// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use cc::Build;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    Build::new().file("src/hello.c").compile("hello")?;
    println!("Compiled hello.c");
    Ok(())
}
