// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use cc::Build;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    Build::new().cpp(true).file("src/hello.cpp").compile("hello_cpp")?;
    println!("Compiled hello.cpp");
    Ok(())
}
