// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let version: String = "0.1.0".to_string();
    println!("Built with version {}", version);
}
