// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn get_double() -> MayDouble {
    let x: f64 = 2.718;
    Some(x)
}

fn main() {
    let a: MayDouble = get_double();
}