// Auto-generated by a2r transpiler

use std::boxed::Box;
use fake_core::{FakeTerm, EventListener, Dimensions, FakeMaster, RealMaster};
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct GridSize {
    pub cols: i64,
    pub rows: i64,
}

impl Dimensions for GridSize {
    fn area(&self) -> i64 {
        return self.cols * self.rows;
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
enum Damage {
    Full,
    Lines(Vec<i64>),
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct ChannelListener {
    pub hits: i64,
}

impl EventListener for ChannelListener {
    fn on_event(&self, code: i64) -> i64 {
        return self.hits + code;
    }
}

struct TermSession {
    pub term: FakeTerm<ChannelListener>,
    pub size: GridSize,
    pub master: Box<dyn FakeMaster + Send>,
}

fn main() {
    let mut term = FakeTerm::new(Box::new(ChannelListener { hits: 5 }));
    let size = GridSize { cols: 80, rows: 24 };
    let mut area = size.area();
    term.feed(3);
    let mut drained = term.drained();
    let mut echo = term.echo();
    println!("area= {}", area);
    println!("drained= {}", drained);
    println!("echo= {}", echo);
    let session = TermSession { term: term, size: size, master: Box::new(RealMaster::new()) };
    println!("session_ok  {}", session.term.echo());
}
