// Auto-generated by a2r transpiler

trait Comparable<T> {
    fn compare(&self, other: T) -> i64;
}


#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct ScoreCmp {
    pub score: i64,
}

impl Comparable<i64> for ScoreCmp {
    fn compare(&self, other: i64) -> i64 {
        return self.score - other;
    }
}

pub fn main() {
    let mut a = ScoreCmp { score: 10 };
    println!("{}", a.compare(5));
}
