// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Flyer {
    fn fly(&self);
}


struct Pigeon {}

impl Pigeon {
    fn fly(&self) {
        println!("Flap Flap");
    }
}

struct Hawk {}

impl Hawk {
    fn fly(&self) {
        println!("Gawk! Gawk!");
    }
}

fn main() {

    let b1 = Pigeon {};
    let b2 = Hawk {};



    let arr: &[Flyer] = [b1, b2];
    for b in arr {
        b.fly();
    }
}
