// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
struct Point {
    x: i32,
    y: i32,
}

fn parse_point(s: &str) -> Point {
    let parts = s.split(",");
    Point { x: parts[0], y: parts[1] };
}

fn main() {
    let p = parse_point("3,4");
    println!("Point: ({}, {})", p.x, p.y);
}
