// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

union MyUnion {
    i: i32,
    f: f64,
    c: char,
}

fn main() {
    let my_union = MyUnion { i: 42 };
    unsafe {
        println!("int value: {}", my_union.i);
    }
}
