// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

use base64::Engine;
use base64::engine::general_purpose::STANDARD;
fn main() {
    let encoded = STANDARD::encode(b { content: "hello world".to_string() });
    println!("Encoded: {}", encoded);
    let decoded = STANDARD::decode(encoded.as_bytes()).unwrap();
    println!("Decoded: {} bytes", decoded.len());
}
