// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn main() {
    let text: String = "hello".to_string();
    println!("Original: {}", text);
    let upper = text.to_uppercase();
    println!("Uppercase: {}", upper);
    let lower = upper.to_lowercase();
    println!("Lowercase: {}", lower);
}
