// Auto-generated by a2r transpiler

fn main() {
    let name: String = "cosmic".to_string();
    let count: i32 = 3;


    let f = move |n: i32| { println!("{}", n); };
    f(count);


    let g = move || { println!("{}", name); };
    g();
}
