// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
enum Coin {
    Penny = 0,
    Nickel = 1,
    Dime = 2,
    Quarter = 3,
}

impl std::fmt::Display for Coin {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Coin::Penny => write!(f, "Penny"),
            Coin::Nickel => write!(f, "Nickel"),
            Coin::Dime => write!(f, "Dime"),
            Coin::Quarter => write!(f, "Quarter"),
        }
    }
}
impl Coin {
    pub fn from_id(id: &str) -> Self {
        match id {
            "Penny" | "penny" => Coin::Penny,
            "Nickel" | "nickel" => Coin::Nickel,
            "Dime" | "dime" => Coin::Dime,
            "Quarter" | "quarter" => Coin::Quarter,
            _ => Coin::Penny
        }
    }
}

fn main() {
    let c = Coin::Penny;
    match c {
        Coin::Penny => println!("Penny!"),
        Coin::Nickel => println!("Nickel!"),
        _ => println!("Other"),
    }
}
