// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std;
use auto_lang::a2r_std::*;

fn mean(data: &[i32]) -> Option<f64> {
    let count = data.len();
    if count == 0 {
        return None;
    }
    let mut sum: i32 = 0;
    for val in data {
        sum += val;
    }
    Some((sum as f64) / (count as f64))
}

fn main() {
    let data: Vec<i32> = vec![3, 1, 6, 1, 5, 8, 1, 8, 10, 11];

    let m = mean(data);
    println!("Mean: {}", m);
}
