// Auto-generated by a2r transpiler

fn mean(data: &[i64]) -> Option<f64> {
    let count = (data.len() as i64);
    if count == 0 {
        return None;
    }
    let mut sum: i64 = 0;
    for val in &data {
        sum += val;
    }
    Some((sum as f64) / (count as f64))
}

fn main() {
    let data: Vec<i64> = vec![3, 1, 6, 1, 5, 8, 1, 8, 10, 11];


    let mut sum: i64 = 0;
    for val in &data {
        sum += val;
    }
    let count = (data.len() as i64);
    assert!(sum == 54);
    assert!(count == 10);



}
