// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct ClientScalars {
    pub default_provider: String,
}

pub fn main() {

    let n = "42".parse::<u32>();

    let m = pair::<i32, String>(1, "a");

    let node = Node("x");
    let s = node.deserialize::<ClientScalars>();

    let c: bool = a < b;

    let t = List<str>;
}
